`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 07:03:12 CST (May 25 2023 23:03:12 UTC)

module SobelFilter_Add_24Ux14U_25S_4(in2, in1, out1);
  input [23:0] in2;
  input [13:0] in1;
  output [24:0] out1;
  wire [23:0] in2;
  wire [13:0] in1;
  wire [24:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_9, add_23_2_n_10, add_23_2_n_11,
       add_23_2_n_12, add_23_2_n_13, add_23_2_n_14, add_23_2_n_15;
  wire add_23_2_n_16, add_23_2_n_17, add_23_2_n_18, add_23_2_n_19,
       add_23_2_n_20, add_23_2_n_21, add_23_2_n_22, add_23_2_n_23;
  wire add_23_2_n_24, add_23_2_n_25, add_23_2_n_26, add_23_2_n_27,
       add_23_2_n_28, add_23_2_n_29, add_23_2_n_30, add_23_2_n_31;
  wire add_23_2_n_32, add_23_2_n_33, add_23_2_n_34, add_23_2_n_35,
       add_23_2_n_36, add_23_2_n_37, add_23_2_n_38, add_23_2_n_39;
  wire add_23_2_n_40, add_23_2_n_41, add_23_2_n_42, add_23_2_n_43,
       add_23_2_n_44, add_23_2_n_45, add_23_2_n_46, add_23_2_n_47;
  wire add_23_2_n_48, add_23_2_n_49, add_23_2_n_50, add_23_2_n_51,
       add_23_2_n_52, add_23_2_n_54, add_23_2_n_55, add_23_2_n_56;
  wire add_23_2_n_57, add_23_2_n_59, add_23_2_n_60, add_23_2_n_61,
       add_23_2_n_62, add_23_2_n_64, add_23_2_n_67, add_23_2_n_68;
  wire add_23_2_n_69, add_23_2_n_70, add_23_2_n_71, add_23_2_n_75,
       add_23_2_n_76, add_23_2_n_77, add_23_2_n_78, add_23_2_n_79;
  wire add_23_2_n_80, add_23_2_n_82, add_23_2_n_83, add_23_2_n_84,
       add_23_2_n_90, add_23_2_n_91, add_23_2_n_92, add_23_2_n_93;
  wire add_23_2_n_94, add_23_2_n_97, add_23_2_n_98;
  XNOR2X1 add_23_2_g497(.A (in2[23]), .B (add_23_2_n_97), .Y
       (out1[23]));
  XNOR2X1 add_23_2_g498(.A (in2[15]), .B (add_23_2_n_98), .Y
       (out1[15]));
  XNOR2X1 add_23_2_g499(.A (in2[19]), .B (add_23_2_n_91), .Y
       (out1[19]));
  XNOR2X1 add_23_2_g500(.A (in2[21]), .B (add_23_2_n_92), .Y
       (out1[21]));
  XNOR2X1 add_23_2_g501(.A (in2[17]), .B (add_23_2_n_0), .Y (out1[17]));
  XNOR2X1 add_23_2_g502(.A (in2[14]), .B (add_23_2_n_94), .Y
       (out1[14]));
  XNOR2X1 add_23_2_g503(.A (add_23_2_n_41), .B (add_23_2_n_90), .Y
       (out1[13]));
  XNOR2X1 add_23_2_g504(.A (add_23_2_n_38), .B (add_23_2_n_84), .Y
       (out1[11]));
  XNOR2X1 add_23_2_g505(.A (in2[22]), .B (add_23_2_n_93), .Y
       (out1[22]));
  NAND2BX1 add_23_2_g506(.AN (add_23_2_n_94), .B (in2[14]), .Y
       (add_23_2_n_98));
  NAND2BX1 add_23_2_g507(.AN (add_23_2_n_93), .B (in2[22]), .Y
       (add_23_2_n_97));
  XOR2XL add_23_2_g508(.A (in2[18]), .B (add_23_2_n_83), .Y (out1[18]));
  XOR2XL add_23_2_g509(.A (in2[20]), .B (add_23_2_n_82), .Y (out1[20]));
  NAND2X1 add_23_2_g510(.A (in2[20]), .B (add_23_2_n_82), .Y
       (add_23_2_n_92));
  NAND2X1 add_23_2_g511(.A (in2[18]), .B (add_23_2_n_83), .Y
       (add_23_2_n_91));
  OAI21X1 add_23_2_g512(.A0 (add_23_2_n_22), .A1 (add_23_2_n_80), .B0
       (add_23_2_n_5), .Y (add_23_2_n_90));
  AOI21X1 add_23_2_g513(.A0 (add_23_2_n_44), .A1 (add_23_2_n_79), .B0
       (add_23_2_n_48), .Y (add_23_2_n_94));
  NAND2BX1 add_23_2_g514(.AN (add_23_2_n_11), .B (add_23_2_n_82), .Y
       (add_23_2_n_93));
  XNOR2X1 add_23_2_g515(.A (add_23_2_n_34), .B (add_23_2_n_78), .Y
       (out1[10]));
  XNOR2X1 add_23_2_g516(.A (add_23_2_n_39), .B (add_23_2_n_80), .Y
       (out1[12]));
  XNOR2X1 add_23_2_g517(.A (in2[16]), .B (add_23_2_n_75), .Y
       (out1[16]));
  XNOR2X1 add_23_2_g518(.A (add_23_2_n_43), .B (add_23_2_n_77), .Y
       (out1[9]));
  XNOR2X1 add_23_2_g519(.A (add_23_2_n_31), .B (add_23_2_n_76), .Y
       (out1[7]));
  OAI21X1 add_23_2_g520(.A0 (add_23_2_n_8), .A1 (add_23_2_n_78), .B0
       (add_23_2_n_9), .Y (add_23_2_n_84));
  NOR2X1 add_23_2_g521(.A (add_23_2_n_28), .B (add_23_2_n_75), .Y
       (add_23_2_n_83));
  NOR2X1 add_23_2_g522(.A (add_23_2_n_37), .B (add_23_2_n_75), .Y
       (add_23_2_n_82));
  NOR4X1 add_23_2_g524(.A (add_23_2_n_75), .B (add_23_2_n_37), .C
       (add_23_2_n_15), .D (add_23_2_n_11), .Y (out1[24]));
  INVX1 add_23_2_g525(.A (add_23_2_n_80), .Y (add_23_2_n_79));
  AOI2BB1X1 add_23_2_g526(.A0N (add_23_2_n_50), .A1N (add_23_2_n_70),
       .B0 (add_23_2_n_56), .Y (add_23_2_n_80));
  AOI21X1 add_23_2_g527(.A0 (add_23_2_n_36), .A1 (add_23_2_n_69), .B0
       (add_23_2_n_47), .Y (add_23_2_n_78));
  OAI21X1 add_23_2_g528(.A0 (add_23_2_n_20), .A1 (add_23_2_n_70), .B0
       (add_23_2_n_6), .Y (add_23_2_n_77));
  OAI21X1 add_23_2_g529(.A0 (add_23_2_n_1), .A1 (add_23_2_n_67), .B0
       (add_23_2_n_21), .Y (add_23_2_n_76));
  AOI221X1 add_23_2_g531(.A0 (add_23_2_n_51), .A1 (add_23_2_n_56), .B0
       (add_23_2_n_14), .B1 (add_23_2_n_48), .C0 (add_23_2_n_71), .Y
       (add_23_2_n_75));
  XNOR2X1 add_23_2_g532(.A (add_23_2_n_33), .B (add_23_2_n_70), .Y
       (out1[8]));
  XNOR2X1 add_23_2_g533(.A (add_23_2_n_32), .B (add_23_2_n_67), .Y
       (out1[6]));
  XNOR2X1 add_23_2_g534(.A (add_23_2_n_30), .B (add_23_2_n_68), .Y
       (out1[5]));
  NOR3BX1 add_23_2_g535(.AN (add_23_2_n_51), .B (add_23_2_n_70), .C
       (add_23_2_n_50), .Y (add_23_2_n_71));
  INVX1 add_23_2_g536(.A (add_23_2_n_70), .Y (add_23_2_n_69));
  AOI31X1 add_23_2_g537(.A0 (add_23_2_n_61), .A1 (add_23_2_n_45), .A2
       (add_23_2_n_35), .B0 (add_23_2_n_57), .Y (add_23_2_n_70));
  OAI21X1 add_23_2_g538(.A0 (add_23_2_n_4), .A1 (add_23_2_n_62), .B0
       (add_23_2_n_17), .Y (add_23_2_n_68));
  AOI21X1 add_23_2_g539(.A0 (add_23_2_n_35), .A1 (add_23_2_n_61), .B0
       (add_23_2_n_49), .Y (add_23_2_n_67));
  XNOR2X1 add_23_2_g540(.A (add_23_2_n_40), .B (add_23_2_n_62), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g541(.A (add_23_2_n_42), .B (add_23_2_n_64), .Y
       (out1[3]));
  OAI2BB1X1 add_23_2_g542(.A0N (add_23_2_n_19), .A1N (add_23_2_n_59),
       .B0 (add_23_2_n_2), .Y (add_23_2_n_64));
  XNOR2X1 add_23_2_g543(.A (add_23_2_n_29), .B (add_23_2_n_59), .Y
       (out1[2]));
  INVX1 add_23_2_g544(.A (add_23_2_n_61), .Y (add_23_2_n_62));
  OAI211X1 add_23_2_g545(.A0 (add_23_2_n_2), .A1 (add_23_2_n_18), .B0
       (add_23_2_n_60), .C0 (add_23_2_n_27), .Y (add_23_2_n_61));
  NAND3BXL add_23_2_g546(.AN (add_23_2_n_18), .B (add_23_2_n_59), .C
       (add_23_2_n_19), .Y (add_23_2_n_60));
  ADDFX1 add_23_2_g547(.A (add_23_2_n_52), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_59), .S (out1[1]));
  OAI211X1 add_23_2_g548(.A0 (add_23_2_n_21), .A1 (add_23_2_n_23), .B0
       (add_23_2_n_55), .C0 (add_23_2_n_25), .Y (add_23_2_n_57));
  OAI211X1 add_23_2_g549(.A0 (add_23_2_n_9), .A1 (add_23_2_n_24), .B0
       (add_23_2_n_54), .C0 (add_23_2_n_13), .Y (add_23_2_n_56));
  NAND2XL add_23_2_g550(.A (add_23_2_n_45), .B (add_23_2_n_49), .Y
       (add_23_2_n_55));
  NAND2XL add_23_2_g551(.A (add_23_2_n_46), .B (add_23_2_n_47), .Y
       (add_23_2_n_54));
  ADDHX1 add_23_2_g552(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_52),
       .S (out1[0]));
  AND2XL add_23_2_g553(.A (add_23_2_n_14), .B (add_23_2_n_44), .Y
       (add_23_2_n_51));
  NAND2X1 add_23_2_g554(.A (add_23_2_n_46), .B (add_23_2_n_36), .Y
       (add_23_2_n_50));
  OAI21X1 add_23_2_g555(.A0 (add_23_2_n_17), .A1 (add_23_2_n_7), .B0
       (add_23_2_n_26), .Y (add_23_2_n_49));
  OAI21X1 add_23_2_g556(.A0 (add_23_2_n_5), .A1 (add_23_2_n_16), .B0
       (add_23_2_n_12), .Y (add_23_2_n_48));
  OAI21X1 add_23_2_g557(.A0 (add_23_2_n_6), .A1 (add_23_2_n_3), .B0
       (add_23_2_n_10), .Y (add_23_2_n_47));
  NOR2X1 add_23_2_g558(.A (add_23_2_n_24), .B (add_23_2_n_8), .Y
       (add_23_2_n_46));
  NOR2X1 add_23_2_g559(.A (add_23_2_n_23), .B (add_23_2_n_1), .Y
       (add_23_2_n_45));
  NAND2BX1 add_23_2_g560(.AN (add_23_2_n_3), .B (add_23_2_n_10), .Y
       (add_23_2_n_43));
  NAND2BX1 add_23_2_g561(.AN (add_23_2_n_18), .B (add_23_2_n_27), .Y
       (add_23_2_n_42));
  NAND2BX1 add_23_2_g562(.AN (add_23_2_n_16), .B (add_23_2_n_12), .Y
       (add_23_2_n_41));
  NOR2BX1 add_23_2_g563(.AN (add_23_2_n_17), .B (add_23_2_n_4), .Y
       (add_23_2_n_40));
  NOR2BX1 add_23_2_g564(.AN (add_23_2_n_5), .B (add_23_2_n_22), .Y
       (add_23_2_n_39));
  NAND2BX1 add_23_2_g565(.AN (add_23_2_n_24), .B (add_23_2_n_13), .Y
       (add_23_2_n_38));
  NOR2X1 add_23_2_g566(.A (add_23_2_n_16), .B (add_23_2_n_22), .Y
       (add_23_2_n_44));
  NAND3BXL add_23_2_g567(.AN (add_23_2_n_28), .B (in2[19]), .C
       (in2[18]), .Y (add_23_2_n_37));
  NOR2BX1 add_23_2_g568(.AN (add_23_2_n_9), .B (add_23_2_n_8), .Y
       (add_23_2_n_34));
  NOR2BX1 add_23_2_g569(.AN (add_23_2_n_6), .B (add_23_2_n_20), .Y
       (add_23_2_n_33));
  NOR2BX1 add_23_2_g570(.AN (add_23_2_n_21), .B (add_23_2_n_1), .Y
       (add_23_2_n_32));
  NAND2BX1 add_23_2_g571(.AN (add_23_2_n_23), .B (add_23_2_n_25), .Y
       (add_23_2_n_31));
  NAND2BX1 add_23_2_g572(.AN (add_23_2_n_7), .B (add_23_2_n_26), .Y
       (add_23_2_n_30));
  NOR2X1 add_23_2_g573(.A (add_23_2_n_3), .B (add_23_2_n_20), .Y
       (add_23_2_n_36));
  NAND2X1 add_23_2_g574(.A (add_23_2_n_2), .B (add_23_2_n_19), .Y
       (add_23_2_n_29));
  NOR2X1 add_23_2_g575(.A (add_23_2_n_7), .B (add_23_2_n_4), .Y
       (add_23_2_n_35));
  NAND2X1 add_23_2_g576(.A (in2[23]), .B (in2[22]), .Y (add_23_2_n_15));
  NAND2X1 add_23_2_g577(.A (in2[17]), .B (in2[16]), .Y (add_23_2_n_28));
  NAND2X1 add_23_2_g578(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_27));
  NAND2X1 add_23_2_g579(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_26));
  NAND2X1 add_23_2_g580(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_25));
  NOR2X1 add_23_2_g581(.A (in2[11]), .B (in1[11]), .Y (add_23_2_n_24));
  NOR2X1 add_23_2_g582(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_23));
  NOR2X1 add_23_2_g583(.A (in2[12]), .B (in1[12]), .Y (add_23_2_n_22));
  NAND2X1 add_23_2_g584(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_21));
  NOR2X1 add_23_2_g585(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_20));
  OR2X1 add_23_2_g586(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_19));
  NOR2X1 add_23_2_g587(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_18));
  NAND2X1 add_23_2_g588(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_17));
  NOR2X1 add_23_2_g589(.A (in2[13]), .B (in1[13]), .Y (add_23_2_n_16));
  AND2XL add_23_2_g590(.A (in2[15]), .B (in2[14]), .Y (add_23_2_n_14));
  NAND2X1 add_23_2_g591(.A (in2[11]), .B (in1[11]), .Y (add_23_2_n_13));
  NAND2X1 add_23_2_g592(.A (in2[13]), .B (in1[13]), .Y (add_23_2_n_12));
  NAND2X1 add_23_2_g593(.A (in2[21]), .B (in2[20]), .Y (add_23_2_n_11));
  NAND2X1 add_23_2_g594(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_10));
  NAND2X1 add_23_2_g595(.A (in2[10]), .B (in1[10]), .Y (add_23_2_n_9));
  NOR2X1 add_23_2_g596(.A (in2[10]), .B (in1[10]), .Y (add_23_2_n_8));
  NOR2X1 add_23_2_g597(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_7));
  NAND2X1 add_23_2_g598(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_6));
  NAND2X1 add_23_2_g599(.A (in2[12]), .B (in1[12]), .Y (add_23_2_n_5));
  NOR2X1 add_23_2_g600(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_4));
  NOR2X1 add_23_2_g601(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_3));
  NAND2X1 add_23_2_g602(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_2));
  NOR2X1 add_23_2_g603(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_1));
  NAND2BX1 add_23_2_g2(.AN (add_23_2_n_75), .B (in2[16]), .Y
       (add_23_2_n_0));
endmodule

