`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 07:03:18 CST (May 25 2023 23:03:18 UTC)

module SobelFilter_Add_6Sx5U_7S_1(in2, in1, out1);
  input [5:0] in2;
  input [4:0] in1;
  output [6:0] out1;
  wire [5:0] in2;
  wire [4:0] in1;
  wire [6:0] out1;
  wire add_23_2_n_1, add_23_2_n_6, add_23_2_n_7, add_23_2_n_8,
       add_23_2_n_9, add_23_2_n_10, add_23_2_n_11, add_23_2_n_12;
  wire add_23_2_n_13, add_23_2_n_14, add_23_2_n_15, add_23_2_n_16,
       add_23_2_n_17, add_23_2_n_18, add_23_2_n_19, add_23_2_n_20;
  wire add_23_2_n_21, add_23_2_n_22, add_23_2_n_23, add_23_2_n_24,
       add_23_2_n_25, add_23_2_n_26, add_23_2_n_27, add_23_2_n_28;
  wire add_23_2_n_30;
  MXI2X1 add_23_2_g110(.A (add_23_2_n_6), .B (in2[5]), .S0
       (add_23_2_n_30), .Y (out1[5]));
  NAND2X1 add_23_2_g111(.A (add_23_2_n_14), .B (add_23_2_n_28), .Y
       (add_23_2_n_30));
  AOI21X1 add_23_2_g112(.A0 (add_23_2_n_15), .A1 (add_23_2_n_26), .B0
       (add_23_2_n_21), .Y (out1[6]));
  NAND2X1 add_23_2_g115(.A (add_23_2_n_15), .B (add_23_2_n_26), .Y
       (add_23_2_n_28));
  OAI21X1 add_23_2_g116(.A0 (add_23_2_n_13), .A1 (add_23_2_n_24), .B0
       (add_23_2_n_8), .Y (add_23_2_n_27));
  NAND2X2 add_23_2_g118(.A (add_23_2_n_22), .B (add_23_2_n_25), .Y
       (add_23_2_n_26));
  NAND2X2 add_23_2_g119(.A (add_23_2_n_19), .B (add_23_2_n_23), .Y
       (add_23_2_n_25));
  INVX1 add_23_2_g120(.A (add_23_2_n_23), .Y (add_23_2_n_24));
  OAI21X4 add_23_2_g121(.A0 (add_23_2_n_7), .A1 (add_23_2_n_9), .B0
       (add_23_2_n_11), .Y (add_23_2_n_23));
  AOI2BB1X1 add_23_2_g124(.A0N (add_23_2_n_8), .A1N (add_23_2_n_10),
       .B0 (add_23_2_n_16), .Y (add_23_2_n_22));
  NAND2X1 add_23_2_g126(.A (in2[5]), .B (add_23_2_n_14), .Y
       (add_23_2_n_21));
  NAND2X1 add_23_2_g128(.A (add_23_2_n_14), .B (add_23_2_n_15), .Y
       (add_23_2_n_20));
  NOR2X1 add_23_2_g129(.A (add_23_2_n_10), .B (add_23_2_n_13), .Y
       (add_23_2_n_19));
  NOR2X1 add_23_2_g131(.A (add_23_2_n_16), .B (add_23_2_n_10), .Y
       (add_23_2_n_18));
  NAND2X1 add_23_2_g133(.A (add_23_2_n_8), .B (add_23_2_n_12), .Y
       (add_23_2_n_17));
  AND2X6 add_23_2_g135(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_16));
  OR2X1 add_23_2_g136(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_15));
  NAND2X1 add_23_2_g137(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_14));
  INVX1 add_23_2_g138(.A (add_23_2_n_13), .Y (add_23_2_n_12));
  NOR2X4 add_23_2_g139(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_13));
  NAND2X2 add_23_2_g141(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_11));
  NOR2X4 add_23_2_g142(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_10));
  NOR2X6 add_23_2_g143(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_9));
  NAND2X2 add_23_2_g144(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_8));
  NAND2X6 add_23_2_g145(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_7));
  INVX1 add_23_2_g146(.A (in2[5]), .Y (add_23_2_n_6));
  XNOR2X1 add_23_2_g2(.A (add_23_2_n_7), .B (add_23_2_n_1), .Y
       (out1[1]));
  XNOR2X1 add_23_2_g148(.A (add_23_2_n_20), .B (add_23_2_n_26), .Y
       (out1[4]));
  XOR2XL add_23_2_g149(.A (add_23_2_n_18), .B (add_23_2_n_27), .Y
       (out1[3]));
  XNOR2X1 add_23_2_g150(.A (add_23_2_n_17), .B (add_23_2_n_23), .Y
       (out1[2]));
  NOR2BX1 add_23_2_g151(.AN (add_23_2_n_11), .B (add_23_2_n_9), .Y
       (add_23_2_n_1));
  XOR2XL add_23_2_g152(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
endmodule

