`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:07:43 CST (May 25 2023 22:07:43 UTC)

module SobelFilter_N_Mux_32_3_69_1(in4, in3, in2, ctrl1, out1);
  input [31:0] in4;
  input [8:0] in3, in2;
  input [5:0] ctrl1;
  output [31:0] out1;
  wire [31:0] in4;
  wire [8:0] in3, in2;
  wire [5:0] ctrl1;
  wire [31:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_237, n_239, n_240, n_242;
  OAI2BB1X1 g3974(.A0N (in4[6]), .A1N (n_129), .B0 (n_158), .Y
       (out1[6]));
  OAI2BB1X1 g3975(.A0N (in4[7]), .A1N (n_130), .B0 (n_160), .Y
       (out1[7]));
  OAI2BB1X1 g3976(.A0N (in4[8]), .A1N (n_132), .B0 (n_168), .Y
       (out1[8]));
  OAI2BB1X1 g3977(.A0N (in4[5]), .A1N (n_128), .B0 (n_159), .Y
       (out1[5]));
  OAI2BB1X1 g3978(.A0N (in4[2]), .A1N (n_125), .B0 (n_164), .Y
       (out1[2]));
  OAI2BB1X1 g3979(.A0N (in4[3]), .A1N (n_126), .B0 (n_157), .Y
       (out1[3]));
  OAI2BB1X1 g3980(.A0N (in4[4]), .A1N (n_127), .B0 (n_161), .Y
       (out1[4]));
  OAI2BB1X1 g3981(.A0N (in4[1]), .A1N (n_124), .B0 (n_163), .Y
       (out1[1]));
  OAI2BB1X1 g3982(.A0N (in4[0]), .A1N (n_133), .B0 (n_167), .Y
       (out1[0]));
  AOI221X1 g4006(.A0 (in4[8]), .A1 (n_166), .B0 (in3[8]), .B1 (n_165),
       .C0 (n_120), .Y (n_168));
  AOI221X1 g3999(.A0 (in4[0]), .A1 (n_166), .B0 (in3[0]), .B1 (n_165),
       .C0 (n_113), .Y (n_167));
  AOI221X1 g4012(.A0 (in4[2]), .A1 (n_166), .B0 (in2[2]), .B1 (n_162),
       .C0 (n_118), .Y (n_164));
  AOI221X1 g4013(.A0 (in4[1]), .A1 (n_166), .B0 (in2[1]), .B1 (n_162),
       .C0 (n_114), .Y (n_163));
  AOI221X1 g4010(.A0 (in4[4]), .A1 (n_166), .B0 (in3[4]), .B1 (n_165),
       .C0 (n_115), .Y (n_161));
  AOI221X1 g4007(.A0 (in4[7]), .A1 (n_166), .B0 (in3[7]), .B1 (n_165),
       .C0 (n_122), .Y (n_160));
  AOI221X1 g4009(.A0 (in4[5]), .A1 (n_166), .B0 (in2[5]), .B1 (n_162),
       .C0 (n_119), .Y (n_159));
  AOI221X1 g4008(.A0 (in4[6]), .A1 (n_166), .B0 (in3[6]), .B1 (n_165),
       .C0 (n_123), .Y (n_158));
  AOI221X1 g4011(.A0 (in4[3]), .A1 (n_166), .B0 (in3[3]), .B1 (n_165),
       .C0 (n_116), .Y (n_157));
  AOI21X1 g3995(.A0 (n_75), .A1 (n_77), .B0 (n_20), .Y (out1[26]));
  AOI21X1 g3983(.A0 (n_58), .A1 (n_91), .B0 (n_11), .Y (out1[30]));
  AOI21X1 g3998(.A0 (n_63), .A1 (n_88), .B0 (n_16), .Y (out1[29]));
  AOI21X1 g3984(.A0 (n_62), .A1 (n_86), .B0 (n_24), .Y (out1[28]));
  AOI21X1 g3990(.A0 (n_70), .A1 (n_84), .B0 (n_13), .Y (out1[27]));
  AOI21X1 g3993(.A0 (n_72), .A1 (n_98), .B0 (n_22), .Y (out1[31]));
  AOI21X1 g4014(.A0 (n_55), .A1 (n_79), .B0 (n_1), .Y (out1[25]));
  AOI21X1 g4002(.A0 (n_64), .A1 (n_108), .B0 (n_10), .Y (out1[24]));
  AOI21X1 g4005(.A0 (n_76), .A1 (n_99), .B0 (n_18), .Y (out1[23]));
  AOI21X1 g3987(.A0 (n_68), .A1 (n_90), .B0 (n_5), .Y (out1[22]));
  AOI21X1 g3988(.A0 (n_65), .A1 (n_89), .B0 (n_23), .Y (out1[21]));
  AOI21X1 g4001(.A0 (n_61), .A1 (n_111), .B0 (n_8), .Y (out1[13]));
  AOI21X1 g3991(.A0 (n_56), .A1 (n_85), .B0 (n_4), .Y (out1[19]));
  AOI21X1 g3992(.A0 (n_66), .A1 (n_83), .B0 (n_21), .Y (out1[18]));
  AOI21X1 g3996(.A0 (n_57), .A1 (n_78), .B0 (n_19), .Y (out1[16]));
  AOI21X1 g3997(.A0 (n_54), .A1 (n_112), .B0 (n_3), .Y (out1[15]));
  AOI21X1 g4000(.A0 (n_53), .A1 (n_80), .B0 (n_14), .Y (out1[14]));
  AOI21X1 g3989(.A0 (n_52), .A1 (n_87), .B0 (n_2), .Y (out1[20]));
  AOI21X1 g4003(.A0 (n_59), .A1 (n_82), .B0 (n_17), .Y (out1[12]));
  AOI21X1 g4004(.A0 (n_71), .A1 (n_93), .B0 (n_0), .Y (out1[11]));
  AOI21X1 g3985(.A0 (n_69), .A1 (n_107), .B0 (n_7), .Y (out1[10]));
  AOI21X1 g3986(.A0 (n_67), .A1 (n_92), .B0 (n_26), .Y (out1[9]));
  AOI21X1 g3994(.A0 (n_60), .A1 (n_81), .B0 (n_15), .Y (out1[17]));
  NAND2XL g4017(.A (n_131), .B (n_106), .Y (n_133));
  NAND2XL g4016(.A (n_131), .B (n_105), .Y (n_132));
  NAND2XL g4015(.A (n_131), .B (n_101), .Y (n_130));
  NAND2XL g4018(.A (n_131), .B (n_100), .Y (n_129));
  NAND2XL g4021(.A (n_131), .B (n_97), .Y (n_128));
  NAND2XL g4020(.A (n_131), .B (n_96), .Y (n_127));
  NAND2XL g4019(.A (n_131), .B (n_95), .Y (n_126));
  NAND2XL g4022(.A (n_131), .B (n_94), .Y (n_125));
  NAND2XL g4023(.A (n_131), .B (n_102), .Y (n_124));
  NOR2BX1 g4027(.AN (in2[6]), .B (n_121), .Y (n_123));
  NOR2BX1 g4026(.AN (in2[7]), .B (n_121), .Y (n_122));
  NOR2BX1 g4025(.AN (in2[8]), .B (n_121), .Y (n_120));
  NOR2BX1 g4028(.AN (in3[5]), .B (n_117), .Y (n_119));
  NOR2BX1 g4031(.AN (in3[2]), .B (n_117), .Y (n_118));
  NOR2BX1 g4030(.AN (in2[3]), .B (n_121), .Y (n_116));
  NOR2BX1 g4029(.AN (in2[4]), .B (n_121), .Y (n_115));
  NOR2BX1 g4032(.AN (in3[1]), .B (n_117), .Y (n_114));
  NOR2BX1 g4024(.AN (in2[0]), .B (n_121), .Y (n_113));
  NOR2XL g4061(.A (n_110), .B (n_109), .Y (n_112));
  NOR2XL g4062(.A (n_110), .B (n_109), .Y (n_111));
  NOR2XL g4063(.A (n_110), .B (n_109), .Y (n_108));
  NOR2XL g4064(.A (n_110), .B (n_109), .Y (n_107));
  NOR2XL g4033(.A (n_104), .B (n_103), .Y (n_106));
  NOR2XL g4035(.A (n_104), .B (n_103), .Y (n_105));
  NOR2XL g4034(.A (n_104), .B (n_103), .Y (n_102));
  NOR2XL g4036(.A (n_104), .B (n_103), .Y (n_101));
  NOR2XL g4037(.A (n_104), .B (n_103), .Y (n_100));
  NOR2XL g4043(.A (n_110), .B (n_109), .Y (n_99));
  NOR2XL g4042(.A (n_110), .B (n_109), .Y (n_98));
  NOR2XL g4038(.A (n_104), .B (n_103), .Y (n_97));
  NOR2XL g4039(.A (n_104), .B (n_103), .Y (n_96));
  NOR2XL g4040(.A (n_104), .B (n_103), .Y (n_95));
  NOR2XL g4041(.A (n_104), .B (n_103), .Y (n_94));
  CLKINVX3 g4080(.A (n_121), .Y (n_162));
  INVX3 g4081(.A (n_117), .Y (n_165));
  NOR2XL g4044(.A (n_110), .B (n_109), .Y (n_93));
  NOR2XL g4045(.A (n_110), .B (n_109), .Y (n_92));
  NOR2XL g4046(.A (n_110), .B (n_109), .Y (n_91));
  NOR2XL g4047(.A (n_110), .B (n_109), .Y (n_90));
  NOR2XL g4048(.A (n_110), .B (n_109), .Y (n_89));
  NOR2XL g4049(.A (n_110), .B (n_109), .Y (n_88));
  NOR2XL g4050(.A (n_110), .B (n_109), .Y (n_87));
  NOR2XL g4051(.A (n_110), .B (n_109), .Y (n_86));
  NOR2XL g4052(.A (n_110), .B (n_109), .Y (n_85));
  NOR2XL g4053(.A (n_110), .B (n_109), .Y (n_84));
  NOR2XL g4054(.A (n_110), .B (n_109), .Y (n_83));
  NOR2XL g4055(.A (n_110), .B (n_109), .Y (n_82));
  NOR2XL g4056(.A (n_110), .B (n_109), .Y (n_81));
  NOR2XL g4057(.A (n_110), .B (n_109), .Y (n_80));
  NOR2XL g4058(.A (n_110), .B (n_109), .Y (n_79));
  NOR2XL g4059(.A (n_110), .B (n_109), .Y (n_78));
  NOR2XL g4060(.A (n_110), .B (n_109), .Y (n_77));
  NOR2XL g4070(.A (n_74), .B (n_73), .Y (n_76));
  NOR2XL g4065(.A (n_74), .B (n_73), .Y (n_75));
  NOR2XL g4066(.A (n_74), .B (n_73), .Y (n_72));
  NOR2XL g4067(.A (n_74), .B (n_73), .Y (n_71));
  NOR2XL g4068(.A (n_74), .B (n_73), .Y (n_70));
  NOR2XL g4069(.A (n_74), .B (n_73), .Y (n_69));
  NOR2XL g4073(.A (n_74), .B (n_73), .Y (n_68));
  NOR2XL g4071(.A (n_74), .B (n_73), .Y (n_67));
  NOR2XL g4072(.A (n_74), .B (n_73), .Y (n_66));
  NOR2XL g4075(.A (n_74), .B (n_73), .Y (n_65));
  NOR2XL g4077(.A (n_74), .B (n_73), .Y (n_64));
  NOR2XL g4074(.A (n_74), .B (n_73), .Y (n_63));
  NOR2XL g4078(.A (n_74), .B (n_73), .Y (n_62));
  NOR2XL g4090(.A (n_74), .B (n_73), .Y (n_61));
  NOR2XL g4089(.A (n_74), .B (n_73), .Y (n_60));
  NOR2XL g4082(.A (n_74), .B (n_73), .Y (n_59));
  NOR2XL g4083(.A (n_74), .B (n_73), .Y (n_58));
  NOR2XL g4084(.A (n_74), .B (n_73), .Y (n_57));
  NOR2XL g4085(.A (n_74), .B (n_73), .Y (n_56));
  NOR2XL g4086(.A (n_74), .B (n_73), .Y (n_55));
  NOR2XL g4087(.A (n_74), .B (n_73), .Y (n_54));
  NOR2XL g4088(.A (n_74), .B (n_73), .Y (n_53));
  NOR2XL g4076(.A (n_74), .B (n_73), .Y (n_52));
  NAND2X4 g4094(.A (n_36), .B (n_51), .Y (n_117));
  NAND2X4 g4091(.A (n_28), .B (n_49), .Y (n_121));
  NOR2X2 g4079(.A (n_41), .B (n_74), .Y (n_131));
  NAND2X4 g4092(.A (n_50), .B (n_44), .Y (n_104));
  NAND2X4 g4095(.A (n_30), .B (n_48), .Y (n_110));
  NAND2X2 g4093(.A (n_32), .B (n_47), .Y (n_103));
  NAND2X4 g4096(.A (n_40), .B (n_46), .Y (n_109));
  NOR2X4 g4101(.A (n_29), .B (n_33), .Y (n_51));
  NAND2X4 g4100(.A (n_50), .B (n_42), .Y (n_73));
  NOR2X6 g4103(.A (n_38), .B (n_34), .Y (n_49));
  NAND2X6 g4104(.A (n_27), .B (n_35), .Y (n_74));
  NOR2X2 g4097(.A (n_43), .B (n_31), .Y (n_48));
  NOR2X2 g4098(.A (n_39), .B (n_45), .Y (n_47));
  NOR2X2 g4099(.A (n_45), .B (n_166), .Y (n_46));
  AOI21X4 g4102(.A0 (ctrl1[0]), .A1 (n_237), .B0 (n_43), .Y (n_44));
  INVX1 g4105(.A (n_41), .Y (n_42));
  INVX1 g4114(.A (n_39), .Y (n_40));
  NAND2X8 g4118(.A (ctrl1[5]), .B (n_240), .Y (n_38));
  NOR2X2 g4108(.A (n_6), .B (n_12), .Y (n_36));
  NAND2X2 g4110(.A (ctrl1[3]), .B (n_239), .Y (n_35));
  NAND2X4 g4117(.A (ctrl1[2]), .B (n_9), .Y (n_34));
  NAND2X4 g4116(.A (ctrl1[2]), .B (n_25), .Y (n_33));
  INVX1 g4115(.A (n_31), .Y (n_32));
  NAND2X1 g4122(.A (ctrl1[0]), .B (n_242), .Y (n_30));
  NAND2X2 g4121(.A (ctrl1[1]), .B (n_237), .Y (n_50));
  NAND2X4 g4106(.A (ctrl1[4]), .B (ctrl1[3]), .Y (n_29));
  NOR2X1 g4107(.A (ctrl1[1]), .B (ctrl1[0]), .Y (n_28));
  NOR2X2 g4111(.A (ctrl1[5]), .B (ctrl1[1]), .Y (n_45));
  NOR2X2 g4123(.A (ctrl1[5]), .B (ctrl1[3]), .Y (n_31));
  NAND2X2 g4109(.A (ctrl1[5]), .B (ctrl1[4]), .Y (n_27));
  NOR2X2 g4119(.A (ctrl1[5]), .B (ctrl1[2]), .Y (n_39));
  NOR2X1 g4112(.A (ctrl1[4]), .B (ctrl1[2]), .Y (n_41));
  NOR2X2 g4120(.A (ctrl1[5]), .B (ctrl1[4]), .Y (n_43));
  NOR2X4 g4113(.A (ctrl1[5]), .B (ctrl1[0]), .Y (n_166));
  INVX1 g4129(.A (in4[9]), .Y (n_26));
  CLKINVX3 g4151(.A (ctrl1[5]), .Y (n_25));
  INVX1 g4148(.A (in4[28]), .Y (n_24));
  INVX1 g4132(.A (in4[21]), .Y (n_23));
  INVX1 g4140(.A (in4[31]), .Y (n_22));
  INVX1 g4125(.A (in4[18]), .Y (n_21));
  INVX1 g4126(.A (in4[26]), .Y (n_20));
  INVX1 g4138(.A (in4[16]), .Y (n_19));
  INVX1 g4127(.A (in4[23]), .Y (n_18));
  INVX1 g4146(.A (in4[12]), .Y (n_17));
  INVX1 g4147(.A (in4[29]), .Y (n_16));
  INVX1 g4144(.A (in4[17]), .Y (n_15));
  INVX1 g4124(.A (in4[14]), .Y (n_14));
  INVX1 g4149(.A (in4[27]), .Y (n_13));
  INVX1 g4134(.A (ctrl1[0]), .Y (n_12));
  INVX1 g4143(.A (in4[30]), .Y (n_11));
  INVX1 g4137(.A (in4[24]), .Y (n_10));
  CLKINVX4 g4135(.A (ctrl1[3]), .Y (n_9));
  INVX1 g4142(.A (in4[13]), .Y (n_8));
  INVX1 g4145(.A (in4[10]), .Y (n_7));
  INVX1 g4150(.A (ctrl1[1]), .Y (n_6));
  INVX1 g4128(.A (in4[22]), .Y (n_5));
  INVX1 g4141(.A (in4[19]), .Y (n_4));
  INVX1 g4133(.A (in4[15]), .Y (n_3));
  INVX1 g4139(.A (in4[20]), .Y (n_2));
  INVX1 g4131(.A (in4[25]), .Y (n_1));
  INVX1 g4130(.A (in4[11]), .Y (n_0));
  CLKINVX2 fopt(.A (ctrl1[4]), .Y (n_237));
  CLKINVX3 fopt4152(.A (ctrl1[4]), .Y (n_239));
  CLKINVX12 fopt4153(.A (ctrl1[4]), .Y (n_240));
  INVXL fopt4154(.A (ctrl1[4]), .Y (n_242));
endmodule

