`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 05:59:52 CST (May 25 2023 21:59:52 UTC)

module SobelFilter_N_Mux_32_4_60_4(in5, in4, in3, in2, ctrl1, out1);
  input [31:0] in5;
  input [8:0] in4, in3, in2;
  input [5:0] ctrl1;
  output [31:0] out1;
  wire [31:0] in5;
  wire [8:0] in4, in3, in2;
  wire [5:0] ctrl1;
  wire [31:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_55, n_57, n_66;
  OAI2BB1X1 g3079(.A0N (in5[6]), .A1N (n_66), .B0 (n_28), .Y (out1[6]));
  OAI2BB1X1 g3076(.A0N (in5[7]), .A1N (n_66), .B0 (n_27), .Y (out1[7]));
  OAI2BB1X1 g3077(.A0N (in5[8]), .A1N (n_66), .B0 (n_25), .Y (out1[8]));
  OAI2BB1X1 g3082(.A0N (in5[5]), .A1N (n_66), .B0 (n_29), .Y (out1[5]));
  OAI2BB1X1 g3078(.A0N (in5[2]), .A1N (n_66), .B0 (n_30), .Y (out1[2]));
  OAI2BB1X1 g3075(.A0N (in5[3]), .A1N (n_66), .B0 (n_33), .Y (out1[3]));
  OAI2BB1X1 g3083(.A0N (in5[4]), .A1N (n_66), .B0 (n_57), .Y (out1[4]));
  OAI2BB1X1 g3081(.A0N (in5[1]), .A1N (n_66), .B0 (n_24), .Y (out1[1]));
  OAI2BB1X1 g3080(.A0N (in5[0]), .A1N (n_66), .B0 (n_26), .Y (out1[0]));
  NOR2BX1 g3111(.AN (in5[27]), .B (n_55), .Y (out1[27]));
  AOI221X1 g3092(.A0 (in3[4]), .A1 (n_32), .B0 (in2[4]), .B1 (n_31),
       .C0 (n_14), .Y (n_57));
  NOR2BX1 g3096(.AN (in5[31]), .B (n_55), .Y (out1[31]));
  NOR2BX1 g3099(.AN (in5[30]), .B (n_55), .Y (out1[30]));
  NOR2BX1 g3103(.AN (in5[29]), .B (n_55), .Y (out1[29]));
  NOR2BX1 g3104(.AN (in5[28]), .B (n_55), .Y (out1[28]));
  NOR2BX1 g3115(.AN (in5[9]), .B (n_55), .Y (out1[9]));
  NOR2BX1 g3106(.AN (in5[16]), .B (n_55), .Y (out1[16]));
  NOR2BX1 g3110(.AN (in5[26]), .B (n_55), .Y (out1[26]));
  NOR2BX1 g3114(.AN (in5[25]), .B (n_55), .Y (out1[25]));
  NOR2BX1 g3094(.AN (in5[24]), .B (n_55), .Y (out1[24]));
  NOR2BX1 g3095(.AN (in5[23]), .B (n_55), .Y (out1[23]));
  NOR2BX1 g3107(.AN (in5[15]), .B (n_55), .Y (out1[15]));
  NOR2BX1 g3098(.AN (in5[21]), .B (n_55), .Y (out1[21]));
  NOR2BX1 g3093(.AN (in5[20]), .B (n_55), .Y (out1[20]));
  NOR2BX1 g3100(.AN (in5[19]), .B (n_55), .Y (out1[19]));
  NOR2BX1 g3101(.AN (in5[18]), .B (n_55), .Y (out1[18]));
  NOR2BX1 g3102(.AN (in5[17]), .B (n_55), .Y (out1[17]));
  NOR2BX1 g3097(.AN (in5[22]), .B (n_55), .Y (out1[22]));
  NOR2BX1 g3109(.AN (in5[13]), .B (n_55), .Y (out1[13]));
  NOR2BX1 g3105(.AN (in5[12]), .B (n_55), .Y (out1[12]));
  NOR2BX1 g3108(.AN (in5[14]), .B (n_55), .Y (out1[14]));
  NOR2BX1 g3113(.AN (in5[10]), .B (n_55), .Y (out1[10]));
  NOR2BX1 g3112(.AN (in5[11]), .B (n_55), .Y (out1[11]));
  AOI221X1 g3085(.A0 (in3[3]), .A1 (n_32), .B0 (in2[3]), .B1 (n_31),
       .C0 (n_15), .Y (n_33));
  AOI221X1 g3084(.A0 (in3[2]), .A1 (n_32), .B0 (in2[2]), .B1 (n_31),
       .C0 (n_16), .Y (n_30));
  AOI221X1 g3091(.A0 (in3[5]), .A1 (n_32), .B0 (in2[5]), .B1 (n_31),
       .C0 (n_18), .Y (n_29));
  AOI221X1 g3088(.A0 (in3[6]), .A1 (n_32), .B0 (in2[6]), .B1 (n_31),
       .C0 (n_11), .Y (n_28));
  AOI221X1 g3089(.A0 (in3[7]), .A1 (n_32), .B0 (in2[7]), .B1 (n_31),
       .C0 (n_10), .Y (n_27));
  AOI221X1 g3090(.A0 (in3[0]), .A1 (n_32), .B0 (in2[0]), .B1 (n_31),
       .C0 (n_13), .Y (n_26));
  AOI221X1 g3086(.A0 (in3[8]), .A1 (n_32), .B0 (in2[8]), .B1 (n_31),
       .C0 (n_12), .Y (n_25));
  AOI221X1 g3087(.A0 (in3[1]), .A1 (n_32), .B0 (in2[1]), .B1 (n_31),
       .C0 (n_19), .Y (n_24));
  NAND4XL g3116(.A (n_21), .B (n_23), .C (n_8), .D (n_22), .Y (n_66));
  AND4X1 g3126(.A (n_23), .B (n_22), .C (n_20), .D (n_9), .Y (n_55));
  NOR2BX1 g3130(.AN (n_20), .B (n_7), .Y (n_21));
  NOR2BX1 g3124(.AN (in4[1]), .B (n_17), .Y (n_19));
  NOR2BX1 g3125(.AN (in4[5]), .B (n_17), .Y (n_18));
  NOR2BX1 g3117(.AN (in4[2]), .B (n_17), .Y (n_16));
  NOR4X1 g3128(.A (n_6), .B (ctrl1[2]), .C (ctrl1[0]), .D (n_4), .Y
       (n_32));
  NOR2BX1 g3118(.AN (in4[3]), .B (n_17), .Y (n_15));
  NOR2BX1 g3119(.AN (in4[4]), .B (n_17), .Y (n_14));
  NOR2BX1 g3120(.AN (in4[0]), .B (n_17), .Y (n_13));
  NOR2BX1 g3121(.AN (in4[8]), .B (n_17), .Y (n_12));
  NOR2BX1 g3122(.AN (in4[6]), .B (n_17), .Y (n_11));
  NOR2BX1 g3123(.AN (in4[7]), .B (n_17), .Y (n_10));
  NOR2BX1 g3129(.AN (n_8), .B (n_7), .Y (n_9));
  NOR4X1 g3132(.A (n_0), .B (ctrl1[3]), .C (n_2), .D (n_5), .Y (n_31));
  NAND4BX1 g3127(.AN (n_1), .B (ctrl1[0]), .C (ctrl1[3]), .D (n_23), .Y
       (n_17));
  OAI21X1 g3131(.A0 (n_6), .A1 (n_3), .B0 (ctrl1[3]), .Y (n_22));
  NAND2BXL g3133(.AN (ctrl1[3]), .B (n_5), .Y (n_20));
  NAND2X1 g3134(.A (ctrl1[3]), .B (n_23), .Y (n_4));
  AND2X1 g3135(.A (n_6), .B (n_3), .Y (n_7));
  NAND2X1 g3137(.A (ctrl1[2]), .B (n_6), .Y (n_5));
  INVX1 g3138(.A (n_23), .Y (n_2));
  NAND2X1 g3136(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_1));
  NOR2BX1 g3139(.AN (ctrl1[2]), .B (ctrl1[0]), .Y (n_3));
  NAND2BXL g3140(.AN (ctrl1[2]), .B (ctrl1[0]), .Y (n_8));
  AND2X1 g3141(.A (ctrl1[5]), .B (ctrl1[4]), .Y (n_23));
  INVX1 g3142(.A (ctrl1[1]), .Y (n_6));
  INVX1 g3143(.A (ctrl1[0]), .Y (n_0));
endmodule

