`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:07:31 CST (May 25 2023 22:07:31 UTC)

module SobelFilter_N_Mux_32_3_78_1(in4, in3, in2, ctrl1, out1);
  input [31:0] in4;
  input [8:0] in3, in2;
  input [5:0] ctrl1;
  output [31:0] out1;
  wire [31:0] in4;
  wire [8:0] in3, in2;
  wire [5:0] ctrl1;
  wire [31:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_244, n_245;
  OAI2BB1X1 g3976(.A0N (in4[6]), .A1N (n_109), .B0 (n_138), .Y
       (out1[6]));
  OAI2BB1X1 g3977(.A0N (in4[7]), .A1N (n_113), .B0 (n_140), .Y
       (out1[7]));
  OAI2BB1X1 g3978(.A0N (in4[8]), .A1N (n_112), .B0 (n_147), .Y
       (out1[8]));
  OAI2BB1X1 g3979(.A0N (in4[5]), .A1N (n_106), .B0 (n_139), .Y
       (out1[5]));
  OAI2BB1X1 g3980(.A0N (in4[2]), .A1N (n_105), .B0 (n_144), .Y
       (out1[2]));
  OAI2BB1X1 g3981(.A0N (in4[3]), .A1N (n_108), .B0 (n_137), .Y
       (out1[3]));
  OAI2BB1X1 g3982(.A0N (in4[4]), .A1N (n_107), .B0 (n_141), .Y
       (out1[4]));
  OAI2BB1X1 g3983(.A0N (in4[1]), .A1N (n_104), .B0 (n_143), .Y
       (out1[1]));
  OAI2BB1X1 g3984(.A0N (in4[0]), .A1N (n_110), .B0 (n_148), .Y
       (out1[0]));
  NOR2BX1 g4004(.AN (in4[24]), .B (n_117), .Y (out1[24]));
  NOR2BX1 g3986(.AN (in4[28]), .B (n_115), .Y (out1[28]));
  NOR2BX1 g3992(.AN (in4[27]), .B (n_129), .Y (out1[27]));
  NOR2BX1 g3997(.AN (in4[26]), .B (n_126), .Y (out1[26]));
  NOR2BX1 g4016(.AN (in4[25]), .B (n_122), .Y (out1[25]));
  NOR2BX1 g4000(.AN (in4[29]), .B (n_133), .Y (out1[29]));
  NOR2BX1 g4007(.AN (in4[23]), .B (n_135), .Y (out1[23]));
  NOR2BX1 g3989(.AN (in4[22]), .B (n_134), .Y (out1[22]));
  NOR2BX1 g3990(.AN (in4[21]), .B (n_132), .Y (out1[21]));
  NOR2BX1 g3991(.AN (in4[20]), .B (n_124), .Y (out1[20]));
  NOR2BX1 g3993(.AN (in4[19]), .B (n_130), .Y (out1[19]));
  NOR2BX1 g4006(.AN (in4[11]), .B (n_116), .Y (out1[11]));
  NOR2BX1 g3996(.AN (in4[17]), .B (n_127), .Y (out1[17]));
  NOR2BX1 g3998(.AN (in4[16]), .B (n_119), .Y (out1[16]));
  NOR2BX1 g3999(.AN (in4[15]), .B (n_123), .Y (out1[15]));
  NOR2BX1 g4002(.AN (in4[14]), .B (n_121), .Y (out1[14]));
  NOR2BX1 g4005(.AN (in4[12]), .B (n_118), .Y (out1[12]));
  NOR2BX1 g3994(.AN (in4[18]), .B (n_128), .Y (out1[18]));
  NOR2BX1 g4003(.AN (in4[13]), .B (n_125), .Y (out1[13]));
  NOR2BX1 g3988(.AN (in4[9]), .B (n_131), .Y (out1[9]));
  NOR2BX1 g3987(.AN (in4[10]), .B (n_114), .Y (out1[10]));
  NOR2BX1 g3985(.AN (in4[30]), .B (n_136), .Y (out1[30]));
  NOR2BX1 g3995(.AN (in4[31]), .B (n_120), .Y (out1[31]));
  AOI221X1 g4001(.A0 (in4[0]), .A1 (n_146), .B0 (in3[0]), .B1 (n_145),
       .C0 (n_78), .Y (n_148));
  AOI221X1 g4008(.A0 (in4[8]), .A1 (n_146), .B0 (in3[8]), .B1 (n_145),
       .C0 (n_77), .Y (n_147));
  AOI221X1 g4014(.A0 (in4[2]), .A1 (n_146), .B0 (in2[2]), .B1 (n_142),
       .C0 (n_69), .Y (n_144));
  AOI221X1 g4015(.A0 (in4[1]), .A1 (n_146), .B0 (in2[1]), .B1 (n_142),
       .C0 (n_85), .Y (n_143));
  AOI221X1 g4012(.A0 (in4[4]), .A1 (n_146), .B0 (in3[4]), .B1 (n_145),
       .C0 (n_71), .Y (n_141));
  AOI221X1 g4009(.A0 (in4[7]), .A1 (n_146), .B0 (in3[7]), .B1 (n_145),
       .C0 (n_75), .Y (n_140));
  AOI221X1 g4011(.A0 (in4[5]), .A1 (n_146), .B0 (in2[5]), .B1 (n_142),
       .C0 (n_73), .Y (n_139));
  AOI221X1 g4010(.A0 (in4[6]), .A1 (n_146), .B0 (in3[6]), .B1 (n_145),
       .C0 (n_74), .Y (n_138));
  AOI221X1 g4013(.A0 (in4[3]), .A1 (n_146), .B0 (in3[3]), .B1 (n_145),
       .C0 (n_70), .Y (n_137));
  NOR2X1 g4033(.A (n_41), .B (n_96), .Y (n_136));
  NOR2X1 g4028(.A (n_53), .B (n_102), .Y (n_135));
  NOR2X1 g4029(.A (n_50), .B (n_95), .Y (n_134));
  NOR2X1 g4030(.A (n_49), .B (n_93), .Y (n_133));
  NOR2X1 g4031(.A (n_48), .B (n_94), .Y (n_132));
  NOR2X1 g4027(.A (n_52), .B (n_97), .Y (n_131));
  NOR2X1 g4034(.A (n_39), .B (n_99), .Y (n_130));
  NOR2X1 g4035(.A (n_55), .B (n_89), .Y (n_129));
  NOR2X1 g4036(.A (n_51), .B (n_90), .Y (n_128));
  NOR2X1 g4037(.A (n_35), .B (n_87), .Y (n_127));
  NOR2X1 g4038(.A (n_60), .B (n_83), .Y (n_126));
  NOR2X1 g4044(.A (n_34), .B (n_81), .Y (n_125));
  NOR2X1 g4017(.A (n_47), .B (n_92), .Y (n_124));
  NOR2X1 g4040(.A (n_37), .B (n_82), .Y (n_123));
  NOR2X1 g4041(.A (n_38), .B (n_68), .Y (n_122));
  NOR2X1 g4042(.A (n_36), .B (n_88), .Y (n_121));
  NOR2X1 g4043(.A (n_59), .B (n_86), .Y (n_120));
  NOR2X1 g4039(.A (n_40), .B (n_84), .Y (n_119));
  NOR2X1 g4045(.A (n_42), .B (n_103), .Y (n_118));
  NOR2X1 g4046(.A (n_46), .B (n_80), .Y (n_117));
  NOR2X1 g4047(.A (n_56), .B (n_98), .Y (n_116));
  NOR2X1 g4048(.A (n_45), .B (n_91), .Y (n_115));
  NOR2X1 g4026(.A (n_54), .B (n_79), .Y (n_114));
  NAND2X1 g4019(.A (n_111), .B (n_44), .Y (n_113));
  NAND2X1 g4018(.A (n_111), .B (n_43), .Y (n_112));
  NAND2X1 g4032(.A (n_111), .B (n_33), .Y (n_110));
  NAND2X1 g4020(.A (n_111), .B (n_67), .Y (n_109));
  NAND2X1 g4023(.A (n_111), .B (n_62), .Y (n_108));
  NAND2X1 g4022(.A (n_111), .B (n_63), .Y (n_107));
  NAND2X1 g4021(.A (n_111), .B (n_66), .Y (n_106));
  NAND2X1 g4024(.A (n_111), .B (n_61), .Y (n_105));
  NAND2X1 g4025(.A (n_111), .B (n_32), .Y (n_104));
  NAND2BX1 g4080(.AN (n_101), .B (n_100), .Y (n_103));
  NAND2BX1 g4068(.AN (n_101), .B (n_100), .Y (n_102));
  NAND2BX1 g4077(.AN (n_101), .B (n_100), .Y (n_99));
  NAND2BX1 g4069(.AN (n_101), .B (n_100), .Y (n_98));
  NAND2BX1 g4070(.AN (n_101), .B (n_100), .Y (n_97));
  NAND2BX1 g4071(.AN (n_101), .B (n_100), .Y (n_96));
  NAND2BX1 g4072(.AN (n_101), .B (n_100), .Y (n_95));
  NAND2BX1 g4073(.AN (n_101), .B (n_100), .Y (n_94));
  NAND2BX1 g4074(.AN (n_101), .B (n_100), .Y (n_93));
  NAND2BX1 g4075(.AN (n_101), .B (n_100), .Y (n_92));
  NAND2BX1 g4076(.AN (n_101), .B (n_100), .Y (n_91));
  NAND2BX1 g4079(.AN (n_101), .B (n_100), .Y (n_90));
  NAND2BX1 g4078(.AN (n_101), .B (n_100), .Y (n_89));
  NAND2BX1 g4082(.AN (n_101), .B (n_100), .Y (n_88));
  NAND2BX1 g4081(.AN (n_101), .B (n_100), .Y (n_87));
  NAND2BX1 g4067(.AN (n_101), .B (n_100), .Y (n_86));
  NOR2BX1 g4057(.AN (in3[1]), .B (n_72), .Y (n_85));
  NAND2BX1 g4084(.AN (n_101), .B (n_100), .Y (n_84));
  NAND2BX1 g4085(.AN (n_101), .B (n_100), .Y (n_83));
  NAND2BX1 g4086(.AN (n_101), .B (n_100), .Y (n_82));
  NAND2BX1 g4087(.AN (n_101), .B (n_100), .Y (n_81));
  NAND2BX1 g4088(.AN (n_101), .B (n_100), .Y (n_80));
  NAND2BX1 g4089(.AN (n_101), .B (n_100), .Y (n_79));
  NOR2BX1 g4049(.AN (in2[0]), .B (n_76), .Y (n_78));
  NOR2BX1 g4050(.AN (in2[8]), .B (n_76), .Y (n_77));
  NOR2BX1 g4051(.AN (in2[7]), .B (n_76), .Y (n_75));
  NOR2BX1 g4052(.AN (in2[6]), .B (n_76), .Y (n_74));
  NOR2BX1 g4053(.AN (in3[5]), .B (n_72), .Y (n_73));
  NOR2BX1 g4054(.AN (in2[4]), .B (n_76), .Y (n_71));
  NOR2BX1 g4055(.AN (in2[3]), .B (n_76), .Y (n_70));
  NOR2BX1 g4056(.AN (in3[2]), .B (n_72), .Y (n_69));
  NAND2BX1 g4083(.AN (n_101), .B (n_100), .Y (n_68));
  NOR2X1 g4062(.A (n_65), .B (n_64), .Y (n_67));
  NOR2X1 g4063(.A (n_65), .B (n_64), .Y (n_66));
  NOR2X1 g4064(.A (n_65), .B (n_64), .Y (n_63));
  NOR2X1 g4065(.A (n_65), .B (n_64), .Y (n_62));
  NOR2X1 g4066(.A (n_65), .B (n_64), .Y (n_61));
  NAND2XL g4090(.A (n_58), .B (n_57), .Y (n_60));
  NAND2XL g4091(.A (n_58), .B (n_57), .Y (n_59));
  NAND2XL g4092(.A (n_58), .B (n_57), .Y (n_56));
  NAND2XL g4093(.A (n_58), .B (n_57), .Y (n_55));
  NAND2XL g4094(.A (n_58), .B (n_57), .Y (n_54));
  NAND2XL g4095(.A (n_58), .B (n_57), .Y (n_53));
  NAND2XL g4096(.A (n_58), .B (n_57), .Y (n_52));
  NAND2XL g4097(.A (n_58), .B (n_57), .Y (n_51));
  NAND2XL g4098(.A (n_58), .B (n_57), .Y (n_50));
  NAND2XL g4099(.A (n_58), .B (n_57), .Y (n_49));
  NAND2XL g4100(.A (n_58), .B (n_57), .Y (n_48));
  NAND2XL g4101(.A (n_58), .B (n_57), .Y (n_47));
  NAND2XL g4102(.A (n_58), .B (n_57), .Y (n_46));
  NAND2XL g4103(.A (n_58), .B (n_57), .Y (n_45));
  NOR2X1 g4061(.A (n_65), .B (n_64), .Y (n_44));
  NOR2X1 g4060(.A (n_65), .B (n_64), .Y (n_43));
  NAND2XL g4107(.A (n_58), .B (n_57), .Y (n_42));
  NAND2XL g4108(.A (n_58), .B (n_57), .Y (n_41));
  NAND2XL g4109(.A (n_58), .B (n_57), .Y (n_40));
  NAND2XL g4110(.A (n_58), .B (n_57), .Y (n_39));
  NAND2XL g4111(.A (n_58), .B (n_57), .Y (n_38));
  NAND2XL g4112(.A (n_58), .B (n_57), .Y (n_37));
  NAND2XL g4113(.A (n_58), .B (n_57), .Y (n_36));
  NAND2XL g4114(.A (n_58), .B (n_57), .Y (n_35));
  NAND2XL g4115(.A (n_58), .B (n_57), .Y (n_34));
  NOR2X1 g4058(.A (n_65), .B (n_64), .Y (n_33));
  NOR2X1 g4059(.A (n_65), .B (n_64), .Y (n_32));
  CLKINVX3 g4105(.A (n_76), .Y (n_142));
  CLKINVX4 g4106(.A (n_72), .Y (n_145));
  NAND2X6 g4117(.A (n_2), .B (n_30), .Y (n_76));
  NOR2X2 g4104(.A (n_18), .B (n_31), .Y (n_111));
  NAND2X4 g4119(.A (n_11), .B (n_29), .Y (n_72));
  NOR2X8 g4120(.A (n_22), .B (n_28), .Y (n_100));
  NAND2X6 g4116(.A (n_27), .B (n_16), .Y (n_64));
  NAND2X4 g4121(.A (n_9), .B (n_25), .Y (n_101));
  NAND2X4 g4118(.A (n_21), .B (n_23), .Y (n_65));
  INVX2 g4126(.A (n_31), .Y (n_58));
  NOR2X6 g4129(.A (n_7), .B (n_12), .Y (n_30));
  NOR2X6 g4127(.A (n_3), .B (n_10), .Y (n_29));
  NAND2X6 g4123(.A (n_26), .B (n_14), .Y (n_28));
  NAND2X2 g4130(.A (n_1), .B (n_19), .Y (n_31));
  NOR2X4 g4122(.A (n_24), .B (n_8), .Y (n_27));
  CLKINVX2 g4133(.A (n_26), .Y (n_146));
  NOR2X4 g4124(.A (n_20), .B (n_24), .Y (n_25));
  NOR2X4 g4128(.A (n_13), .B (n_22), .Y (n_23));
  AOI2BB1X2 g4125(.A0N (ctrl1[4]), .A1N (n_17), .B0 (n_15), .Y (n_57));
  INVX1 g4132(.A (n_20), .Y (n_21));
  NAND2X4 g4137(.A (ctrl1[3]), .B (n_6), .Y (n_19));
  NOR2X1 g4152(.A (n_17), .B (ctrl1[4]), .Y (n_18));
  INVX1 g4131(.A (n_15), .Y (n_16));
  INVX2 g4143(.A (n_13), .Y (n_14));
  CLKINVX2 g4142(.A (n_4), .Y (n_12));
  NOR2X2 g4135(.A (ctrl1[0]), .B (n_0), .Y (n_11));
  NAND2X6 g4146(.A (ctrl1[2]), .B (n_244), .Y (n_10));
  INVX1 g4144(.A (n_8), .Y (n_9));
  NAND2X6 g4148(.A (ctrl1[5]), .B (n_6), .Y (n_7));
  NAND2X4 g4141(.A (ctrl1[0]), .B (n_245), .Y (n_26));
  NOR2X4 g4145(.A (ctrl1[3]), .B (ctrl1[2]), .Y (n_4));
  NAND2X4 g4147(.A (ctrl1[4]), .B (ctrl1[3]), .Y (n_3));
  NOR2X6 g4149(.A (ctrl1[5]), .B (ctrl1[1]), .Y (n_13));
  NOR2X8 g4150(.A (ctrl1[5]), .B (ctrl1[2]), .Y (n_22));
  NOR2X8 g4139(.A (ctrl1[5]), .B (ctrl1[3]), .Y (n_20));
  CLKAND2X2 g4136(.A (ctrl1[1]), .B (ctrl1[0]), .Y (n_2));
  NAND2X2 g4134(.A (ctrl1[5]), .B (ctrl1[4]), .Y (n_1));
  NOR2X2 g4138(.A (ctrl1[4]), .B (ctrl1[1]), .Y (n_15));
  NOR2X6 g4140(.A (ctrl1[5]), .B (ctrl1[4]), .Y (n_24));
  NOR2X4 g4151(.A (ctrl1[4]), .B (ctrl1[0]), .Y (n_8));
  INVX1 g4153(.A (ctrl1[1]), .Y (n_0));
  CLKINVX3 g4156(.A (ctrl1[2]), .Y (n_17));
  CLKINVX12 g4155(.A (ctrl1[4]), .Y (n_6));
  CLKINVX3 fopt(.A (ctrl1[5]), .Y (n_244));
  CLKINVX4 fopt4158(.A (ctrl1[5]), .Y (n_245));
endmodule

