`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:09:48 CST (May 25 2023 22:09:48 UTC)

module SobelFilter_Add_24Ux10U_24U_1(in2, in1, out1);
  input [23:0] in2;
  input [9:0] in1;
  output [23:0] out1;
  wire [23:0] in2;
  wire [9:0] in1;
  wire [23:0] out1;
  wire add_23_2_n_1, add_23_2_n_2, add_23_2_n_3, add_23_2_n_11,
       add_23_2_n_13, add_23_2_n_14, add_23_2_n_15, add_23_2_n_16;
  wire add_23_2_n_17, add_23_2_n_18, add_23_2_n_19, add_23_2_n_20,
       add_23_2_n_21, add_23_2_n_22, add_23_2_n_23, add_23_2_n_24;
  wire add_23_2_n_25, add_23_2_n_26, add_23_2_n_27, add_23_2_n_28,
       add_23_2_n_29, add_23_2_n_30, add_23_2_n_31, add_23_2_n_32;
  wire add_23_2_n_33, add_23_2_n_34, add_23_2_n_35, add_23_2_n_36,
       add_23_2_n_37, add_23_2_n_38, add_23_2_n_39, add_23_2_n_40;
  wire add_23_2_n_41, add_23_2_n_42, add_23_2_n_43, add_23_2_n_44,
       add_23_2_n_45, add_23_2_n_46, add_23_2_n_47, add_23_2_n_48;
  wire add_23_2_n_49, add_23_2_n_50, add_23_2_n_51, add_23_2_n_52,
       add_23_2_n_53, add_23_2_n_54, add_23_2_n_55, add_23_2_n_56;
  wire add_23_2_n_57, add_23_2_n_58, add_23_2_n_59, add_23_2_n_60,
       add_23_2_n_61, add_23_2_n_62, add_23_2_n_63, add_23_2_n_64;
  wire add_23_2_n_65, add_23_2_n_66, add_23_2_n_67, add_23_2_n_68,
       add_23_2_n_69, add_23_2_n_70, add_23_2_n_71, add_23_2_n_72;
  wire add_23_2_n_73, add_23_2_n_74, add_23_2_n_75, add_23_2_n_76,
       add_23_2_n_77, add_23_2_n_78, add_23_2_n_79, add_23_2_n_80;
  wire add_23_2_n_81, add_23_2_n_82, add_23_2_n_83, add_23_2_n_84,
       add_23_2_n_85, add_23_2_n_86, add_23_2_n_87, add_23_2_n_88;
  wire add_23_2_n_89, add_23_2_n_90, add_23_2_n_91, add_23_2_n_92,
       add_23_2_n_93, add_23_2_n_94, add_23_2_n_95, add_23_2_n_96;
  wire add_23_2_n_97, add_23_2_n_98, add_23_2_n_99, add_23_2_n_100,
       add_23_2_n_101, add_23_2_n_102, add_23_2_n_103, add_23_2_n_104;
  wire add_23_2_n_105, add_23_2_n_106, add_23_2_n_107, add_23_2_n_108,
       add_23_2_n_109, add_23_2_n_110, add_23_2_n_111, add_23_2_n_112;
  wire add_23_2_n_113, add_23_2_n_114, add_23_2_n_115, add_23_2_n_116,
       add_23_2_n_117, add_23_2_n_118, add_23_2_n_119, add_23_2_n_120;
  wire add_23_2_n_121, add_23_2_n_122, add_23_2_n_123, add_23_2_n_124,
       add_23_2_n_125, add_23_2_n_126, add_23_2_n_127, add_23_2_n_128;
  wire add_23_2_n_129, add_23_2_n_130, add_23_2_n_131, add_23_2_n_132,
       n_182, n_183, n_184, n_192;
  wire n_193, n_194, n_196, n_199, n_204;
  MXI2X1 add_23_2_g564(.A (add_23_2_n_21), .B (in2[17]), .S0
       (add_23_2_n_130), .Y (out1[17]));
  MXI2X1 add_23_2_g565(.A (add_23_2_n_25), .B (in2[19]), .S0
       (add_23_2_n_127), .Y (out1[19]));
  MXI2X1 add_23_2_g566(.A (add_23_2_n_26), .B (in2[21]), .S0
       (add_23_2_n_128), .Y (out1[21]));
  MXI2X1 add_23_2_g567(.A (add_23_2_n_22), .B (in2[23]), .S0
       (add_23_2_n_126), .Y (out1[23]));
  MXI2X1 add_23_2_g568(.A (add_23_2_n_20), .B (in2[22]), .S0
       (add_23_2_n_129), .Y (out1[22]));
  MXI2X1 add_23_2_g569(.A (add_23_2_n_14), .B (in2[20]), .S0
       (add_23_2_n_132), .Y (out1[20]));
  MXI2X1 add_23_2_g570(.A (add_23_2_n_16), .B (in2[18]), .S0
       (add_23_2_n_131), .Y (out1[18]));
  MXI2X1 add_23_2_g571(.A (in2[13]), .B (add_23_2_n_19), .S0
       (add_23_2_n_122), .Y (out1[13]));
  MXI2X1 add_23_2_g572(.A (in2[11]), .B (add_23_2_n_24), .S0
       (add_23_2_n_123), .Y (out1[11]));
  MXI2X1 add_23_2_g573(.A (in2[10]), .B (add_23_2_n_23), .S0
       (add_23_2_n_121), .Y (out1[10]));
  MXI2X1 add_23_2_g574(.A (add_23_2_n_67), .B (add_23_2_n_68), .S0
       (add_23_2_n_125), .Y (out1[9]));
  MXI2X1 add_23_2_g575(.A (in2[12]), .B (add_23_2_n_13), .S0
       (add_23_2_n_124), .Y (out1[12]));
  MXI2X1 add_23_2_g576(.A (in2[15]), .B (add_23_2_n_18), .S0
       (add_23_2_n_119), .Y (out1[15]));
  MXI2X1 add_23_2_g577(.A (in2[14]), .B (add_23_2_n_17), .S0
       (add_23_2_n_118), .Y (out1[14]));
  MXI2XL add_23_2_g578(.A (in2[16]), .B (add_23_2_n_15), .S0
       (add_23_2_n_120), .Y (out1[16]));
  NOR2X1 add_23_2_g579(.A (add_23_2_n_51), .B (add_23_2_n_120), .Y
       (add_23_2_n_132));
  NOR2X1 add_23_2_g580(.A (add_23_2_n_35), .B (add_23_2_n_120), .Y
       (add_23_2_n_131));
  NOR2X1 add_23_2_g581(.A (add_23_2_n_15), .B (add_23_2_n_120), .Y
       (add_23_2_n_130));
  NOR2X1 add_23_2_g582(.A (add_23_2_n_78), .B (add_23_2_n_120), .Y
       (add_23_2_n_129));
  NOR2X1 add_23_2_g583(.A (add_23_2_n_74), .B (add_23_2_n_120), .Y
       (add_23_2_n_128));
  NOR2X1 add_23_2_g584(.A (add_23_2_n_49), .B (add_23_2_n_120), .Y
       (add_23_2_n_127));
  NOR2X1 add_23_2_g585(.A (add_23_2_n_71), .B (add_23_2_n_120), .Y
       (add_23_2_n_126));
  NOR2BX1 add_23_2_g587(.AN (add_23_2_n_30), .B (add_23_2_n_116), .Y
       (add_23_2_n_125));
  NOR2X1 add_23_2_g588(.A (add_23_2_n_86), .B (add_23_2_n_115), .Y
       (add_23_2_n_124));
  NOR2BX1 add_23_2_g589(.AN (add_23_2_n_89), .B (add_23_2_n_113), .Y
       (add_23_2_n_123));
  NOR2BX1 add_23_2_g590(.AN (add_23_2_n_97), .B (add_23_2_n_114), .Y
       (add_23_2_n_122));
  NOR2X1 add_23_2_g591(.A (add_23_2_n_76), .B (add_23_2_n_117), .Y
       (add_23_2_n_121));
  NOR2X1 add_23_2_g595(.A (add_23_2_n_95), .B (add_23_2_n_110), .Y
       (add_23_2_n_119));
  NOR2X1 add_23_2_g596(.A (add_23_2_n_98), .B (add_23_2_n_112), .Y
       (add_23_2_n_118));
  NOR2X2 add_23_2_g597(.A (add_23_2_n_111), .B (add_23_2_n_96), .Y
       (add_23_2_n_120));
  NOR2X1 add_23_2_g598(.A (add_23_2_n_63), .B (n_199), .Y
       (add_23_2_n_117));
  NOR2X1 add_23_2_g599(.A (add_23_2_n_41), .B (n_199), .Y
       (add_23_2_n_116));
  NOR2X1 add_23_2_g600(.A (add_23_2_n_82), .B (n_199), .Y
       (add_23_2_n_115));
  NOR2X1 add_23_2_g601(.A (add_23_2_n_90), .B (n_199), .Y
       (add_23_2_n_114));
  NOR2X1 add_23_2_g602(.A (add_23_2_n_80), .B (n_199), .Y
       (add_23_2_n_113));
  NOR2X1 add_23_2_g603(.A (add_23_2_n_91), .B (n_199), .Y
       (add_23_2_n_112));
  NOR2X2 add_23_2_g604(.A (add_23_2_n_88), .B (add_23_2_n_109), .Y
       (add_23_2_n_111));
  NOR2X1 add_23_2_g605(.A (add_23_2_n_84), .B (n_199), .Y
       (add_23_2_n_110));
  NOR2X4 add_23_2_g606(.A (add_23_2_n_93), .B (add_23_2_n_104), .Y
       (add_23_2_n_109));
  NOR2BX1 add_23_2_g608(.AN (add_23_2_n_28), .B (add_23_2_n_105), .Y
       (add_23_2_n_108));
  NOR2X1 add_23_2_g611(.A (add_23_2_n_94), .B (add_23_2_n_103), .Y
       (add_23_2_n_107));
  NOR2X1 add_23_2_g612(.A (add_23_2_n_61), .B (n_196), .Y
       (add_23_2_n_106));
  NOR2X1 add_23_2_g613(.A (add_23_2_n_44), .B (n_196), .Y
       (add_23_2_n_105));
  NOR2X6 add_23_2_g614(.A (add_23_2_n_79), .B (add_23_2_n_101), .Y
       (add_23_2_n_104));
  NOR2X1 add_23_2_g615(.A (add_23_2_n_81), .B (n_196), .Y
       (add_23_2_n_103));
  NOR2BX1 add_23_2_g616(.AN (add_23_2_n_40), .B (add_23_2_n_100), .Y
       (add_23_2_n_102));
  NOR2X6 add_23_2_g618(.A (add_23_2_n_73), .B (add_23_2_n_99), .Y
       (add_23_2_n_101));
  NOR2X1 add_23_2_g619(.A (add_23_2_n_33), .B (n_183), .Y
       (add_23_2_n_100));
  NOR2X2 add_23_2_g620(.A (add_23_2_n_3), .B (add_23_2_n_92), .Y
       (add_23_2_n_99));
  NOR2X1 add_23_2_g621(.A (add_23_2_n_27), .B (add_23_2_n_85), .Y
       (add_23_2_n_98));
  NAND2X1 add_23_2_g622(.A (in2[12]), .B (add_23_2_n_86), .Y
       (add_23_2_n_97));
  NOR2X1 add_23_2_g623(.A (add_23_2_n_52), .B (add_23_2_n_85), .Y
       (add_23_2_n_96));
  NOR2X1 add_23_2_g624(.A (add_23_2_n_66), .B (add_23_2_n_85), .Y
       (add_23_2_n_95));
  OAI21X1 add_23_2_g625(.A0 (add_23_2_n_39), .A1 (n_193), .B0
       (add_23_2_n_29), .Y (add_23_2_n_94));
  OAI21X2 add_23_2_g626(.A0 (add_23_2_n_57), .A1 (add_23_2_n_77), .B0
       (add_23_2_n_72), .Y (add_23_2_n_93));
  NOR2X2 add_23_2_g627(.A (add_23_2_n_2), .B (add_23_2_n_87), .Y
       (add_23_2_n_92));
  OR2XL add_23_2_g629(.A (add_23_2_n_27), .B (add_23_2_n_82), .Y
       (add_23_2_n_91));
  NAND2X1 add_23_2_g630(.A (in2[12]), .B (add_23_2_n_83), .Y
       (add_23_2_n_90));
  NAND2XL add_23_2_g631(.A (in2[10]), .B (add_23_2_n_76), .Y
       (add_23_2_n_89));
  NAND2BX1 add_23_2_g632(.AN (add_23_2_n_52), .B (add_23_2_n_83), .Y
       (add_23_2_n_88));
  NOR2X2 add_23_2_g633(.A (add_23_2_n_31), .B (add_23_2_n_46), .Y
       (add_23_2_n_87));
  INVX1 add_23_2_g634(.A (add_23_2_n_86), .Y (add_23_2_n_85));
  NOR2X1 add_23_2_g635(.A (add_23_2_n_47), .B (add_23_2_n_75), .Y
       (add_23_2_n_86));
  NAND2BX1 add_23_2_g636(.AN (add_23_2_n_66), .B (add_23_2_n_83), .Y
       (add_23_2_n_84));
  INVX1 add_23_2_g638(.A (add_23_2_n_83), .Y (add_23_2_n_82));
  OR2XL add_23_2_g639(.A (add_23_2_n_39), .B (add_23_2_n_61), .Y
       (add_23_2_n_81));
  NAND2X1 add_23_2_g640(.A (in2[10]), .B (add_23_2_n_62), .Y
       (add_23_2_n_80));
  NAND2X2 add_23_2_g641(.A (add_23_2_n_56), .B (add_23_2_n_60), .Y
       (add_23_2_n_79));
  OR2XL add_23_2_g642(.A (add_23_2_n_36), .B (add_23_2_n_51), .Y
       (add_23_2_n_78));
  NOR2X2 add_23_2_g643(.A (add_23_2_n_47), .B (add_23_2_n_63), .Y
       (add_23_2_n_83));
  INVX1 add_23_2_g645(.A (add_23_2_n_75), .Y (add_23_2_n_76));
  OR2XL add_23_2_g646(.A (add_23_2_n_14), .B (add_23_2_n_51), .Y
       (add_23_2_n_74));
  OAI21X4 add_23_2_g647(.A0 (add_23_2_n_40), .A1 (n_204), .B0
       (add_23_2_n_48), .Y (add_23_2_n_73));
  AOI2BB1X1 add_23_2_g648(.A0N (add_23_2_n_29), .A1N (add_23_2_n_42),
       .B0 (add_23_2_n_37), .Y (add_23_2_n_72));
  OR3XL add_23_2_g649(.A (add_23_2_n_51), .B (add_23_2_n_20), .C
       (add_23_2_n_36), .Y (add_23_2_n_71));
  NOR2X1 add_23_2_g650(.A (add_23_2_n_1), .B (add_23_2_n_50), .Y
       (add_23_2_n_77));
  NOR2BX1 add_23_2_g651(.AN (add_23_2_n_45), .B (add_23_2_n_59), .Y
       (add_23_2_n_75));
  INVX1 add_23_2_g654(.A (add_23_2_n_67), .Y (add_23_2_n_68));
  INVX1 add_23_2_g657(.A (add_23_2_n_62), .Y (add_23_2_n_63));
  INVX1 add_23_2_g658(.A (add_23_2_n_60), .Y (add_23_2_n_61));
  NOR2X1 add_23_2_g659(.A (add_23_2_n_30), .B (add_23_2_n_43), .Y
       (add_23_2_n_59));
  NOR2BX1 add_23_2_g660(.AN (add_23_2_n_48), .B (n_204), .Y
       (add_23_2_n_70));
  NOR2X1 add_23_2_g661(.A (add_23_2_n_2), .B (add_23_2_n_46), .Y
       (add_23_2_n_58));
  NAND2BX1 add_23_2_g662(.AN (add_23_2_n_33), .B (add_23_2_n_40), .Y
       (add_23_2_n_69));
  NOR2BX1 add_23_2_g663(.AN (add_23_2_n_45), .B (add_23_2_n_43), .Y
       (add_23_2_n_67));
  OR2XL add_23_2_g664(.A (add_23_2_n_17), .B (add_23_2_n_27), .Y
       (add_23_2_n_66));
  NOR2X1 add_23_2_g665(.A (add_23_2_n_37), .B (add_23_2_n_42), .Y
       (add_23_2_n_65));
  NAND2BX1 add_23_2_g666(.AN (add_23_2_n_39), .B (add_23_2_n_29), .Y
       (add_23_2_n_64));
  NOR2X1 add_23_2_g667(.A (add_23_2_n_43), .B (add_23_2_n_41), .Y
       (add_23_2_n_62));
  NOR2X1 add_23_2_g668(.A (add_23_2_n_34), .B (add_23_2_n_44), .Y
       (add_23_2_n_60));
  INVX1 add_23_2_g669(.A (add_23_2_n_56), .Y (add_23_2_n_57));
  NOR2X1 add_23_2_g674(.A (add_23_2_n_28), .B (add_23_2_n_34), .Y
       (add_23_2_n_50));
  OR2XL add_23_2_g675(.A (add_23_2_n_16), .B (add_23_2_n_35), .Y
       (add_23_2_n_49));
  NOR2X1 add_23_2_g677(.A (add_23_2_n_42), .B (add_23_2_n_39), .Y
       (add_23_2_n_56));
  NAND2BX1 add_23_2_g678(.AN (add_23_2_n_44), .B (add_23_2_n_28), .Y
       (add_23_2_n_55));
  NOR2X1 add_23_2_g679(.A (add_23_2_n_1), .B (add_23_2_n_34), .Y
       (add_23_2_n_54));
  NAND2BX1 add_23_2_g680(.AN (add_23_2_n_41), .B (add_23_2_n_30), .Y
       (add_23_2_n_53));
  OR2XL add_23_2_g681(.A (add_23_2_n_38), .B (add_23_2_n_27), .Y
       (add_23_2_n_52));
  OR3XL add_23_2_g682(.A (add_23_2_n_35), .B (add_23_2_n_25), .C
       (add_23_2_n_16), .Y (add_23_2_n_51));
  NAND2X1 add_23_2_g683(.A (in2[15]), .B (in2[14]), .Y (add_23_2_n_38));
  NAND2X1 add_23_2_g684(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_48));
  NAND2X1 add_23_2_g686(.A (in2[11]), .B (in2[10]), .Y (add_23_2_n_47));
  NOR2X2 add_23_2_g687(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_46));
  NAND2X1 add_23_2_g688(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_45));
  NOR2X1 add_23_2_g689(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_44));
  NOR2X1 add_23_2_g690(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_43));
  NOR2X2 add_23_2_g691(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_42));
  NOR2X1 add_23_2_g692(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_41));
  NAND2X1 add_23_2_g693(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_40));
  NOR2X2 add_23_2_g694(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_39));
  AND2X1 add_23_2_g697(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_37));
  NAND2X1 add_23_2_g699(.A (in2[21]), .B (in2[20]), .Y (add_23_2_n_36));
  NAND2X1 add_23_2_g700(.A (in2[17]), .B (in2[16]), .Y (add_23_2_n_35));
  NOR2X2 add_23_2_g701(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_34));
  NOR2X2 add_23_2_g702(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_33));
  NOR2X8 add_23_2_g703(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_32));
  NAND2X4 add_23_2_g704(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_31));
  NAND2X1 add_23_2_g705(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_30));
  NAND2X1 add_23_2_g706(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_29));
  NAND2X1 add_23_2_g707(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_28));
  NAND2X1 add_23_2_g708(.A (in2[13]), .B (in2[12]), .Y (add_23_2_n_27));
  INVXL add_23_2_g712(.A (in2[21]), .Y (add_23_2_n_26));
  INVX1 add_23_2_g713(.A (in2[19]), .Y (add_23_2_n_25));
  INVX1 add_23_2_g714(.A (in2[11]), .Y (add_23_2_n_24));
  INVX1 add_23_2_g715(.A (in2[10]), .Y (add_23_2_n_23));
  INVXL add_23_2_g716(.A (in2[23]), .Y (add_23_2_n_22));
  INVXL add_23_2_g719(.A (in2[17]), .Y (add_23_2_n_21));
  INVX1 add_23_2_g720(.A (in2[22]), .Y (add_23_2_n_20));
  INVX1 add_23_2_g721(.A (in2[13]), .Y (add_23_2_n_19));
  INVX1 add_23_2_g722(.A (in2[15]), .Y (add_23_2_n_18));
  INVX1 add_23_2_g723(.A (in2[14]), .Y (add_23_2_n_17));
  INVX1 add_23_2_g724(.A (in2[18]), .Y (add_23_2_n_16));
  INVX1 add_23_2_g725(.A (in2[16]), .Y (add_23_2_n_15));
  INVX1 add_23_2_g726(.A (in2[20]), .Y (add_23_2_n_14));
  INVX1 add_23_2_g727(.A (in2[12]), .Y (add_23_2_n_13));
  XNOR2X1 add_23_2_g2(.A (add_23_2_n_31), .B (add_23_2_n_58), .Y
       (out1[1]));
  NOR2BX1 add_23_2_g728(.AN (n_192), .B (add_23_2_n_106), .Y
       (add_23_2_n_11));
  XNOR2X1 add_23_2_g729(.A (add_23_2_n_70), .B (add_23_2_n_102), .Y
       (out1[3]));
  CLKXOR2X1 add_23_2_g730(.A (add_23_2_n_69), .B (n_182), .Y (out1[2]));
  XNOR2XL add_23_2_g731(.A (add_23_2_n_65), .B (add_23_2_n_107), .Y
       (out1[7]));
  CLKXOR2X1 add_23_2_g732(.A (add_23_2_n_64), .B (add_23_2_n_11), .Y
       (out1[6]));
  CLKXOR2X1 add_23_2_g733(.A (add_23_2_n_55), .B (n_196), .Y (out1[4]));
  XNOR2XL add_23_2_g734(.A (add_23_2_n_54), .B (add_23_2_n_108), .Y
       (out1[5]));
  CLKXOR2X1 add_23_2_g735(.A (add_23_2_n_53), .B (n_199), .Y (out1[8]));
  OR2XL add_23_2_g736(.A (add_23_2_n_32), .B (add_23_2_n_33), .Y
       (add_23_2_n_3));
  CLKAND2X3 add_23_2_g737(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_2));
  AND2X1 add_23_2_g738(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_1));
  CLKXOR2X1 add_23_2_g739(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVXL fopt(.A (n_184), .Y (n_182));
  INVXL fopt740(.A (n_184), .Y (n_183));
  INVXL fopt741(.A (add_23_2_n_92), .Y (n_184));
  INVXL fopt745(.A (n_194), .Y (n_192));
  INVXL fopt746(.A (n_194), .Y (n_193));
  INVXL fopt747(.A (add_23_2_n_77), .Y (n_194));
  BUFX3 fopt748(.A (add_23_2_n_101), .Y (n_196));
  BUFX3 fopt749(.A (add_23_2_n_109), .Y (n_199));
  BUFX3 fopt750(.A (add_23_2_n_32), .Y (n_204));
endmodule

