`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:09:32 CST (May 25 2023 22:09:32 UTC)

module SobelFilter_N_Mux_20_4_11_1(in5, in4, in3, in2, ctrl1, out1);
  input [19:0] in5, in4, in3, in2;
  input [4:0] ctrl1;
  output [19:0] out1;
  wire [19:0] in5, in4, in3, in2;
  wire [4:0] ctrl1;
  wire [19:0] out1;
  wire n_0, n_2, n_3, n_4, n_5, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_189, n_190, n_195, n_196;
  NAND3X1 g305(.A (n_62), .B (n_15), .C (n_63), .Y (out1[19]));
  NAND3X1 g316(.A (n_41), .B (n_11), .C (n_79), .Y (out1[18]));
  NAND3X1 g306(.A (n_45), .B (n_31), .C (n_70), .Y (out1[17]));
  NAND3X1 g317(.A (n_43), .B (n_20), .C (n_74), .Y (out1[16]));
  NAND3X1 g307(.A (n_47), .B (n_14), .C (n_77), .Y (out1[15]));
  NAND3X1 g310(.A (n_40), .B (n_24), .C (n_65), .Y (out1[14]));
  NAND3X1 g312(.A (n_51), .B (n_35), .C (n_75), .Y (out1[13]));
  NAND3X1 g318(.A (n_50), .B (n_27), .C (n_66), .Y (out1[12]));
  NAND3X1 g321(.A (n_56), .B (n_33), .C (n_78), .Y (out1[11]));
  NAND3X1 g323(.A (n_53), .B (n_18), .C (n_83), .Y (out1[10]));
  NAND3X1 g308(.A (n_46), .B (n_16), .C (n_73), .Y (out1[9]));
  NAND3X1 g309(.A (n_44), .B (n_12), .C (n_69), .Y (out1[8]));
  NAND3X1 g311(.A (n_52), .B (n_10), .C (n_71), .Y (out1[7]));
  NAND3X1 g313(.A (n_59), .B (n_38), .C (n_67), .Y (out1[6]));
  NAND3X1 g314(.A (n_58), .B (n_36), .C (n_80), .Y (out1[5]));
  NAND3X1 g315(.A (n_57), .B (n_25), .C (n_72), .Y (out1[4]));
  NAND3X1 g319(.A (n_61), .B (n_23), .C (n_68), .Y (out1[3]));
  NAND3X1 g320(.A (n_54), .B (n_26), .C (n_64), .Y (out1[2]));
  NAND3X1 g322(.A (n_55), .B (n_29), .C (n_82), .Y (out1[1]));
  NAND3X1 g324(.A (n_42), .B (n_21), .C (n_76), .Y (out1[0]));
  NAND2XL g325(.A (in5[10]), .B (n_81), .Y (n_83));
  NAND2XL g341(.A (in5[1]), .B (n_81), .Y (n_82));
  NAND2XL g333(.A (in5[5]), .B (n_81), .Y (n_80));
  NAND2XL g329(.A (in5[18]), .B (n_81), .Y (n_79));
  NAND2XL g342(.A (in5[11]), .B (n_81), .Y (n_78));
  NAND2XL g327(.A (in5[15]), .B (n_81), .Y (n_77));
  NAND2XL g343(.A (in5[0]), .B (n_81), .Y (n_76));
  NAND2XL g334(.A (in5[13]), .B (n_81), .Y (n_75));
  NAND2XL g344(.A (in5[16]), .B (n_81), .Y (n_74));
  NAND2XL g326(.A (in5[9]), .B (n_81), .Y (n_73));
  NAND2XL g335(.A (in5[4]), .B (n_81), .Y (n_72));
  NAND2XL g330(.A (in5[7]), .B (n_81), .Y (n_71));
  NAND2XL g336(.A (in5[17]), .B (n_81), .Y (n_70));
  NAND2XL g328(.A (in5[8]), .B (n_81), .Y (n_69));
  NAND2XL g337(.A (in5[3]), .B (n_81), .Y (n_68));
  NAND2XL g331(.A (in5[6]), .B (n_81), .Y (n_67));
  NAND2XL g338(.A (in5[12]), .B (n_81), .Y (n_66));
  NAND2XL g332(.A (in5[14]), .B (n_81), .Y (n_65));
  NAND2XL g339(.A (in5[2]), .B (n_81), .Y (n_64));
  NAND2XL g340(.A (in5[19]), .B (n_81), .Y (n_63));
  AOI21X1 g345(.A0 (in4[19]), .A1 (n_60), .B0 (n_22), .Y (n_62));
  AOI21X1 g355(.A0 (in4[3]), .A1 (n_60), .B0 (n_30), .Y (n_61));
  AOI21X1 g352(.A0 (in4[6]), .A1 (n_60), .B0 (n_32), .Y (n_59));
  AOI21X1 g357(.A0 (in4[5]), .A1 (n_60), .B0 (n_37), .Y (n_58));
  AOI21X1 g358(.A0 (in4[4]), .A1 (n_60), .B0 (n_34), .Y (n_57));
  AOI21X1 g363(.A0 (in4[11]), .A1 (n_60), .B0 (n_17), .Y (n_56));
  AOI21X1 g348(.A0 (in4[1]), .A1 (n_60), .B0 (n_39), .Y (n_55));
  AOI21X1 g361(.A0 (in4[2]), .A1 (n_60), .B0 (n_28), .Y (n_54));
  AOI21X1 g365(.A0 (in4[10]), .A1 (n_60), .B0 (n_19), .Y (n_53));
  AOI21X1 g351(.A0 (in4[7]), .A1 (n_60), .B0 (n_13), .Y (n_52));
  AOI22X1 g356(.A0 (in2[13]), .A1 (n_49), .B0 (in3[13]), .B1 (n_48), .Y
       (n_51));
  AOI22X1 g359(.A0 (in2[12]), .A1 (n_49), .B0 (in3[12]), .B1 (n_48), .Y
       (n_50));
  AOI22X1 g353(.A0 (in2[15]), .A1 (n_49), .B0 (in3[15]), .B1 (n_48), .Y
       (n_47));
  AOI22X1 g346(.A0 (in2[9]), .A1 (n_49), .B0 (in3[9]), .B1 (n_48), .Y
       (n_46));
  NOR3X6 g354(.A (n_49), .B (n_60), .C (n_48), .Y (n_81));
  AOI22X1 g360(.A0 (in2[17]), .A1 (n_49), .B0 (in3[17]), .B1 (n_48), .Y
       (n_45));
  AOI22X1 g347(.A0 (in2[8]), .A1 (n_49), .B0 (in3[8]), .B1 (n_48), .Y
       (n_44));
  AOI22X1 g362(.A0 (in2[16]), .A1 (n_49), .B0 (in3[16]), .B1 (n_48), .Y
       (n_43));
  AOI22X1 g364(.A0 (in2[0]), .A1 (n_49), .B0 (in4[0]), .B1 (n_60), .Y
       (n_42));
  AOI22X1 g349(.A0 (in2[18]), .A1 (n_49), .B0 (in3[18]), .B1 (n_48), .Y
       (n_41));
  AOI22X1 g350(.A0 (in2[14]), .A1 (n_49), .B0 (in3[14]), .B1 (n_48), .Y
       (n_40));
  AND2XL g381(.A (in3[1]), .B (n_48), .Y (n_39));
  NAND2X1 g375(.A (in2[6]), .B (n_49), .Y (n_38));
  AND2XL g376(.A (in3[5]), .B (n_48), .Y (n_37));
  NAND2X1 g377(.A (in2[5]), .B (n_49), .Y (n_36));
  NAND2X1 g378(.A (in4[13]), .B (n_60), .Y (n_35));
  AND2XL g379(.A (in3[4]), .B (n_48), .Y (n_34));
  NAND2X1 g380(.A (in2[11]), .B (n_49), .Y (n_33));
  AND2XL g374(.A (in3[6]), .B (n_48), .Y (n_32));
  NAND2X1 g382(.A (in4[17]), .B (n_60), .Y (n_31));
  AND2XL g383(.A (in3[3]), .B (n_48), .Y (n_30));
  NAND2X1 g384(.A (in2[1]), .B (n_49), .Y (n_29));
  AND2XL g385(.A (in3[2]), .B (n_48), .Y (n_28));
  NAND2X1 g386(.A (in4[12]), .B (n_60), .Y (n_27));
  NAND2X1 g387(.A (in2[2]), .B (n_49), .Y (n_26));
  NAND2X1 g388(.A (in2[4]), .B (n_49), .Y (n_25));
  NAND2X1 g366(.A (in4[14]), .B (n_60), .Y (n_24));
  NAND2X1 g390(.A (in2[3]), .B (n_49), .Y (n_23));
  AND2XL g391(.A (in3[19]), .B (n_48), .Y (n_22));
  NAND2X1 g392(.A (in3[0]), .B (n_48), .Y (n_21));
  NAND2X1 g393(.A (in4[16]), .B (n_60), .Y (n_20));
  AND2XL g394(.A (in3[10]), .B (n_48), .Y (n_19));
  NAND2X1 g395(.A (in2[10]), .B (n_49), .Y (n_18));
  AND2XL g389(.A (in3[11]), .B (n_48), .Y (n_17));
  NAND2X1 g367(.A (in4[9]), .B (n_60), .Y (n_16));
  NAND2X1 g372(.A (in2[19]), .B (n_49), .Y (n_15));
  NAND2X1 g368(.A (in4[15]), .B (n_60), .Y (n_14));
  AND2XL g371(.A (in3[7]), .B (n_48), .Y (n_13));
  NAND2X1 g369(.A (in4[8]), .B (n_60), .Y (n_12));
  NAND2X1 g370(.A (in4[18]), .B (n_60), .Y (n_11));
  NAND2X1 g373(.A (in2[7]), .B (n_49), .Y (n_10));
  NOR2X8 g396(.A (n_3), .B (n_8), .Y (n_49));
  NOR2X8 g397(.A (n_5), .B (n_9), .Y (n_60));
  CLKAND2X6 g398(.A (n_4), .B (n_7), .Y (n_48));
  NAND3X8 g399(.A (ctrl1[0]), .B (ctrl1[4]), .C (n_196), .Y (n_9));
  NAND2X6 g400(.A (ctrl1[0]), .B (n_0), .Y (n_8));
  NOR3X4 g401(.A (ctrl1[0]), .B (ctrl1[4]), .C (n_195), .Y (n_7));
  NAND2X4 g404(.A (ctrl1[1]), .B (n_2), .Y (n_5));
  NOR2X4 g402(.A (ctrl1[2]), .B (n_190), .Y (n_4));
  NAND2X4 g405(.A (n_189), .B (n_2), .Y (n_3));
  NOR2X6 g403(.A (ctrl1[4]), .B (ctrl1[3]), .Y (n_0));
  CLKINVX4 g408(.A (ctrl1[2]), .Y (n_2));
  CLKINVX4 fopt(.A (ctrl1[1]), .Y (n_189));
  CLKINVX12 fopt409(.A (ctrl1[1]), .Y (n_190));
  CLKINVX4 fopt412(.A (ctrl1[3]), .Y (n_195));
  CLKINVX6 fopt413(.A (ctrl1[3]), .Y (n_196));
endmodule

