`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:09:29 CST (May 25 2023 22:09:29 UTC)

module SobelFilter_N_Mux_20_3_15_1(in4, in3, in2, ctrl1, out1);
  input [19:0] in4, in3, in2;
  input [4:0] ctrl1;
  output [19:0] out1;
  wire [19:0] in4, in3, in2;
  wire [4:0] ctrl1;
  wire [19:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_67, n_139, n_140, n_142, n_143, n_145;
  OAI2BB1X1 g306(.A0N (in4[19]), .A1N (n_67), .B0 (n_39), .Y
       (out1[19]));
  OAI2BB1X1 g307(.A0N (in4[18]), .A1N (n_67), .B0 (n_43), .Y
       (out1[18]));
  OAI2BB1X1 g319(.A0N (in4[17]), .A1N (n_67), .B0 (n_36), .Y
       (out1[17]));
  OAI2BB1X1 g308(.A0N (in4[16]), .A1N (n_67), .B0 (n_48), .Y
       (out1[16]));
  OAI2BB1X1 g315(.A0N (in4[15]), .A1N (n_67), .B0 (n_40), .Y
       (out1[15]));
  OAI2BB1X1 g320(.A0N (in4[14]), .A1N (n_67), .B0 (n_33), .Y
       (out1[14]));
  OAI2BB1X1 g323(.A0N (in4[13]), .A1N (n_67), .B0 (n_34), .Y
       (out1[13]));
  OAI2BB1X1 g309(.A0N (in4[12]), .A1N (n_67), .B0 (n_45), .Y
       (out1[12]));
  OAI2BB1X1 g312(.A0N (in4[11]), .A1N (n_67), .B0 (n_32), .Y
       (out1[11]));
  OAI2BB1X1 g316(.A0N (in4[10]), .A1N (n_67), .B0 (n_44), .Y
       (out1[10]));
  OAI2BB1X1 g318(.A0N (in4[9]), .A1N (n_67), .B0 (n_41), .Y (out1[9]));
  OAI2BB1X1 g321(.A0N (in4[8]), .A1N (n_67), .B0 (n_38), .Y (out1[8]));
  OAI2BB1X1 g322(.A0N (in4[7]), .A1N (n_67), .B0 (n_35), .Y (out1[7]));
  OAI2BB1X1 g324(.A0N (in4[6]), .A1N (n_67), .B0 (n_31), .Y (out1[6]));
  OAI2BB1X1 g325(.A0N (in4[5]), .A1N (n_67), .B0 (n_30), .Y (out1[5]));
  OAI2BB1X1 g310(.A0N (in4[4]), .A1N (n_67), .B0 (n_47), .Y (out1[4]));
  OAI2BB1X1 g311(.A0N (in4[3]), .A1N (n_67), .B0 (n_28), .Y (out1[3]));
  OAI2BB1X1 g313(.A0N (in4[2]), .A1N (n_67), .B0 (n_42), .Y (out1[2]));
  OAI2BB1X1 g314(.A0N (in4[1]), .A1N (n_67), .B0 (n_37), .Y (out1[1]));
  OAI2BB1X1 g317(.A0N (in4[0]), .A1N (n_67), .B0 (n_29), .Y (out1[0]));
  AOI21X1 g337(.A0 (in3[16]), .A1 (n_46), .B0 (n_18), .Y (n_48));
  AOI21X1 g329(.A0 (in3[4]), .A1 (n_46), .B0 (n_7), .Y (n_47));
  AOI21X1 g332(.A0 (in3[12]), .A1 (n_46), .B0 (n_23), .Y (n_45));
  AOI21X1 g338(.A0 (in3[10]), .A1 (n_46), .B0 (n_17), .Y (n_44));
  AOI21X1 g339(.A0 (in3[18]), .A1 (n_46), .B0 (n_11), .Y (n_43));
  AOI21X1 g333(.A0 (in3[2]), .A1 (n_46), .B0 (n_26), .Y (n_42));
  AOI21X1 g340(.A0 (in3[9]), .A1 (n_46), .B0 (n_16), .Y (n_41));
  AOI21X1 g341(.A0 (in3[15]), .A1 (n_46), .B0 (n_14), .Y (n_40));
  AOI21X1 g326(.A0 (in3[19]), .A1 (n_46), .B0 (n_21), .Y (n_39));
  AOI21X1 g342(.A0 (in3[8]), .A1 (n_46), .B0 (n_19), .Y (n_38));
  AOI21X1 g334(.A0 (in3[1]), .A1 (n_46), .B0 (n_20), .Y (n_37));
  AOI21X1 g330(.A0 (in3[17]), .A1 (n_46), .B0 (n_27), .Y (n_36));
  AOI21X1 g343(.A0 (in3[7]), .A1 (n_46), .B0 (n_15), .Y (n_35));
  AOI21X1 g328(.A0 (in3[13]), .A1 (n_46), .B0 (n_8), .Y (n_34));
  AOI21X1 g344(.A0 (in3[14]), .A1 (n_46), .B0 (n_12), .Y (n_33));
  AOI21X1 g335(.A0 (in3[11]), .A1 (n_46), .B0 (n_13), .Y (n_32));
  AOI21X1 g345(.A0 (in3[6]), .A1 (n_46), .B0 (n_10), .Y (n_31));
  AOI21X1 g327(.A0 (in3[5]), .A1 (n_46), .B0 (n_9), .Y (n_30));
  AOI21X1 g336(.A0 (in3[0]), .A1 (n_46), .B0 (n_22), .Y (n_29));
  AOI21X1 g331(.A0 (in3[3]), .A1 (n_46), .B0 (n_24), .Y (n_28));
  NOR2BX1 g349(.AN (in2[17]), .B (n_145), .Y (n_27));
  NOR2BX1 g350(.AN (in2[2]), .B (n_145), .Y (n_26));
  NOR2BX1 g351(.AN (in2[3]), .B (n_145), .Y (n_24));
  NOR2BX1 g352(.AN (in2[12]), .B (n_145), .Y (n_23));
  NOR2BX1 g353(.AN (in2[0]), .B (n_145), .Y (n_22));
  NOR2BX1 g354(.AN (in2[19]), .B (n_145), .Y (n_21));
  NOR2BX1 g355(.AN (in2[1]), .B (n_145), .Y (n_20));
  NOR2BX1 g356(.AN (in2[8]), .B (n_139), .Y (n_19));
  NOR2BX1 g357(.AN (in2[16]), .B (n_142), .Y (n_18));
  NOR2BX1 g358(.AN (in2[10]), .B (n_145), .Y (n_17));
  NOR2BX1 g359(.AN (in2[9]), .B (n_145), .Y (n_16));
  NOR2BX1 g363(.AN (in2[7]), .B (n_145), .Y (n_15));
  NOR2BX1 g360(.AN (in2[15]), .B (n_145), .Y (n_14));
  NOR2BX1 g361(.AN (in2[11]), .B (n_145), .Y (n_13));
  NOR2BX1 g364(.AN (in2[14]), .B (n_145), .Y (n_12));
  NOR2BX1 g362(.AN (in2[18]), .B (n_143), .Y (n_11));
  NOR2BX1 g365(.AN (in2[6]), .B (n_145), .Y (n_10));
  NOR2BX1 g346(.AN (in2[5]), .B (n_145), .Y (n_9));
  NOR2BX1 g347(.AN (in2[13]), .B (n_140), .Y (n_8));
  NOR2BX1 g348(.AN (in2[4]), .B (n_145), .Y (n_7));
  NOR2X4 g366(.A (n_6), .B (n_46), .Y (n_67));
  CLKAND2X8 g367(.A (n_3), .B (n_4), .Y (n_46));
  NOR2X6 g369(.A (n_1), .B (n_5), .Y (n_6));
  NAND2X6 g370(.A (ctrl1[0]), .B (n_2), .Y (n_5));
  NOR3X2 g371(.A (ctrl1[0]), .B (ctrl1[3]), .C (n_0), .Y (n_4));
  NOR2X2 g372(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_3));
  NOR2X8 g373(.A (ctrl1[4]), .B (ctrl1[3]), .Y (n_2));
  NAND2X2 g374(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_1));
  INVX2 g375(.A (ctrl1[4]), .Y (n_0));
  INVXL fopt(.A (n_6), .Y (n_139));
  INVXL fopt376(.A (n_6), .Y (n_140));
  INVXL fopt377(.A (n_6), .Y (n_142));
  INVXL fopt378(.A (n_6), .Y (n_143));
  CLKINVX8 fopt379(.A (n_6), .Y (n_145));
endmodule

