`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:00:49 CST (May 25 2023 22:00:49 UTC)

module SobelFilter_N_Mux_20_3_17_4(in4, in3, in2, ctrl1, out1);
  input [19:0] in4, in3, in2;
  input [4:0] ctrl1;
  output [19:0] out1;
  wire [19:0] in4, in3, in2;
  wire [4:0] ctrl1;
  wire [19:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_47;
  OAI2BB1X1 g1795(.A0N (in4[19]), .A1N (n_47), .B0 (n_12), .Y
       (out1[19]));
  OAI2BB1X1 g1808(.A0N (in4[18]), .A1N (n_47), .B0 (n_13), .Y
       (out1[18]));
  OAI2BB1X1 g1796(.A0N (in4[17]), .A1N (n_47), .B0 (n_10), .Y
       (out1[17]));
  OAI2BB1X1 g1803(.A0N (in4[16]), .A1N (n_47), .B0 (n_24), .Y
       (out1[16]));
  OAI2BB1X1 g1809(.A0N (in4[15]), .A1N (n_47), .B0 (n_18), .Y
       (out1[15]));
  OAI2BB1X1 g1812(.A0N (in4[14]), .A1N (n_47), .B0 (n_27), .Y
       (out1[14]));
  OAI2BB1X1 g1797(.A0N (in4[13]), .A1N (n_47), .B0 (n_16), .Y
       (out1[13]));
  OAI2BB1X1 g1800(.A0N (in4[12]), .A1N (n_47), .B0 (n_15), .Y
       (out1[12]));
  OAI2BB1X1 g1804(.A0N (in4[11]), .A1N (n_47), .B0 (n_14), .Y
       (out1[11]));
  OAI2BB1X1 g1807(.A0N (in4[10]), .A1N (n_47), .B0 (n_8), .Y
       (out1[10]));
  OAI2BB1X1 g1810(.A0N (in4[9]), .A1N (n_47), .B0 (n_7), .Y (out1[9]));
  OAI2BB1X1 g1811(.A0N (in4[8]), .A1N (n_47), .B0 (n_20), .Y (out1[8]));
  OAI2BB1X1 g1813(.A0N (in4[7]), .A1N (n_47), .B0 (n_17), .Y (out1[7]));
  OAI2BB1X1 g1814(.A0N (in4[6]), .A1N (n_47), .B0 (n_28), .Y (out1[6]));
  OAI2BB1X1 g1798(.A0N (in4[5]), .A1N (n_47), .B0 (n_21), .Y (out1[5]));
  OAI2BB1X1 g1799(.A0N (in4[4]), .A1N (n_47), .B0 (n_22), .Y (out1[4]));
  OAI2BB1X1 g1801(.A0N (in4[3]), .A1N (n_47), .B0 (n_9), .Y (out1[3]));
  OAI2BB1X1 g1802(.A0N (in4[2]), .A1N (n_47), .B0 (n_23), .Y (out1[2]));
  OAI2BB1X1 g1805(.A0N (in4[1]), .A1N (n_47), .B0 (n_19), .Y (out1[1]));
  OAI2BB1X1 g1806(.A0N (in4[0]), .A1N (n_47), .B0 (n_11), .Y (out1[0]));
  AOI22X1 g1815(.A0 (in2[6]), .A1 (n_26), .B0 (in3[6]), .B1 (n_25), .Y
       (n_28));
  AOI22X1 g1816(.A0 (in2[14]), .A1 (n_26), .B0 (in3[14]), .B1 (n_25),
       .Y (n_27));
  AOI22X1 g1831(.A0 (in2[16]), .A1 (n_26), .B0 (in3[16]), .B1 (n_25),
       .Y (n_24));
  AOI22X1 g1823(.A0 (in2[2]), .A1 (n_26), .B0 (in3[2]), .B1 (n_25), .Y
       (n_23));
  AOI22X1 g1819(.A0 (in2[4]), .A1 (n_26), .B0 (in3[4]), .B1 (n_25), .Y
       (n_22));
  AOI22X1 g1817(.A0 (in2[5]), .A1 (n_26), .B0 (in3[5]), .B1 (n_25), .Y
       (n_21));
  AOI22X1 g1832(.A0 (in2[8]), .A1 (n_26), .B0 (in3[8]), .B1 (n_25), .Y
       (n_20));
  AOI22X1 g1824(.A0 (in2[1]), .A1 (n_26), .B0 (in3[1]), .B1 (n_25), .Y
       (n_19));
  AOI22X1 g1833(.A0 (in2[15]), .A1 (n_26), .B0 (in3[15]), .B1 (n_25),
       .Y (n_18));
  AOI22X1 g1834(.A0 (in2[7]), .A1 (n_26), .B0 (in3[7]), .B1 (n_25), .Y
       (n_17));
  AOI22X1 g1820(.A0 (in2[13]), .A1 (n_26), .B0 (in3[13]), .B1 (n_25),
       .Y (n_16));
  AOI22X1 g1825(.A0 (in2[12]), .A1 (n_26), .B0 (in3[12]), .B1 (n_25),
       .Y (n_15));
  AOI22X1 g1826(.A0 (in2[11]), .A1 (n_26), .B0 (in3[11]), .B1 (n_25),
       .Y (n_14));
  AOI22X1 g1818(.A0 (in2[18]), .A1 (n_26), .B0 (in3[18]), .B1 (n_25),
       .Y (n_13));
  AOI22X1 g1821(.A0 (in2[19]), .A1 (n_26), .B0 (in3[19]), .B1 (n_25),
       .Y (n_12));
  AOI22X1 g1827(.A0 (in2[0]), .A1 (n_26), .B0 (in3[0]), .B1 (n_25), .Y
       (n_11));
  AOI22X1 g1828(.A0 (in2[17]), .A1 (n_26), .B0 (in3[17]), .B1 (n_25),
       .Y (n_10));
  AOI22X1 g1822(.A0 (in2[3]), .A1 (n_26), .B0 (in3[3]), .B1 (n_25), .Y
       (n_9));
  AOI22X1 g1829(.A0 (in2[10]), .A1 (n_26), .B0 (in3[10]), .B1 (n_25),
       .Y (n_8));
  AOI22X1 g1830(.A0 (in2[9]), .A1 (n_26), .B0 (in3[9]), .B1 (n_25), .Y
       (n_7));
  OAI2BB1X1 g1835(.A0N (ctrl1[3]), .A1N (n_4), .B0 (n_6), .Y (n_47));
  AND3XL g1836(.A (n_5), .B (ctrl1[3]), .C (ctrl1[2]), .Y (n_25));
  AOI211XL g1837(.A0 (ctrl1[1]), .A1 (n_1), .B0 (n_3), .C0 (ctrl1[4]),
       .Y (n_6));
  AND4X1 g1838(.A (ctrl1[2]), .B (n_0), .C (ctrl1[0]), .D (n_2), .Y
       (n_26));
  NOR2XL g1839(.A (ctrl1[4]), .B (n_4), .Y (n_5));
  OAI21X1 g1840(.A0 (ctrl1[1]), .A1 (ctrl1[0]), .B0 (ctrl1[2]), .Y
       (n_3));
  NAND2BX1 g1841(.AN (ctrl1[0]), .B (ctrl1[1]), .Y (n_4));
  NOR2X1 g1842(.A (ctrl1[4]), .B (ctrl1[3]), .Y (n_2));
  INVX1 g1844(.A (ctrl1[3]), .Y (n_1));
  INVX1 g1843(.A (ctrl1[1]), .Y (n_0));
endmodule

