`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 05:58:27 CST (May 25 2023 21:58:27 UTC)

module SobelFilter_N_Mux_24_2_114_4(in2, ctrl1, out1);
  input [23:0] in2;
  input ctrl1;
  output [23:0] out1;
  wire [23:0] in2;
  wire ctrl1;
  wire [23:0] out1;
  NOR2BX1 g234(.AN (in2[18]), .B (ctrl1), .Y (out1[18]));
  NOR2BX1 g218(.AN (in2[22]), .B (ctrl1), .Y (out1[22]));
  NOR2BX1 g233(.AN (in2[21]), .B (ctrl1), .Y (out1[21]));
  NOR2BX1 g219(.AN (in2[20]), .B (ctrl1), .Y (out1[20]));
  NOR2BX1 g231(.AN (in2[2]), .B (ctrl1), .Y (out1[2]));
  NOR2BX1 g226(.AN (in2[19]), .B (ctrl1), .Y (out1[19]));
  NOR2BX1 g223(.AN (in2[23]), .B (ctrl1), .Y (out1[23]));
  NOR2BX1 g238(.AN (in2[17]), .B (ctrl1), .Y (out1[17]));
  NOR2BX1 g224(.AN (in2[6]), .B (ctrl1), .Y (out1[6]));
  NOR2BX1 g220(.AN (in2[16]), .B (ctrl1), .Y (out1[16]));
  NOR2BX1 g217(.AN (in2[15]), .B (ctrl1), .Y (out1[15]));
  NOR2BX1 g227(.AN (in2[14]), .B (ctrl1), .Y (out1[14]));
  NOR2BX1 g222(.AN (in2[7]), .B (ctrl1), .Y (out1[7]));
  NOR2BX1 g229(.AN (in2[12]), .B (ctrl1), .Y (out1[12]));
  NOR2BX1 g237(.AN (in2[11]), .B (ctrl1), .Y (out1[11]));
  NOR2BX1 g239(.AN (in2[10]), .B (ctrl1), .Y (out1[10]));
  NOR2BX1 g240(.AN (in2[9]), .B (ctrl1), .Y (out1[9]));
  NOR2BX1 g221(.AN (in2[8]), .B (ctrl1), .Y (out1[8]));
  NOR2BX1 g230(.AN (in2[13]), .B (ctrl1), .Y (out1[13]));
  NOR2BX1 g225(.AN (in2[5]), .B (ctrl1), .Y (out1[5]));
  NOR2BX1 g228(.AN (in2[4]), .B (ctrl1), .Y (out1[4]));
  NOR2BX1 g235(.AN (in2[3]), .B (ctrl1), .Y (out1[3]));
  NOR2BX1 g232(.AN (in2[1]), .B (ctrl1), .Y (out1[1]));
  NOR2BX1 g236(.AN (in2[0]), .B (ctrl1), .Y (out1[0]));
endmodule

