`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:07:03 CST (May 25 2023 22:07:03 UTC)

module SobelFilter_N_Mux_32_3_100_1(in4, in3, in2, ctrl1, out1);
  input [31:0] in4;
  input [8:0] in3, in2;
  input [5:0] ctrl1;
  output [31:0] out1;
  wire [31:0] in4;
  wire [8:0] in3, in2;
  wire [5:0] ctrl1;
  wire [31:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_105, n_106;
  wire n_128, n_129, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_139, n_140, n_141, n_142, n_143, n_213, n_214, n_218;
  wire n_222, n_230, n_232, n_234, n_236, n_237, n_238;
  OAI2BB1X1 g3824(.A0N (in4[7]), .A1N (n_101), .B0 (n_143), .Y
       (out1[7]));
  OAI2BB1X1 g3823(.A0N (in4[6]), .A1N (n_102), .B0 (n_141), .Y
       (out1[6]));
  OAI2BB1X1 g3829(.A0N (in4[4]), .A1N (n_95), .B0 (n_142), .Y
       (out1[4]));
  OAI2BB1X1 g3827(.A0N (in4[2]), .A1N (n_97), .B0 (n_140), .Y
       (out1[2]));
  OAI2BB1X1 g3825(.A0N (in4[8]), .A1N (n_99), .B0 (n_134), .Y
       (out1[8]));
  OAI2BB1X1 g3826(.A0N (in4[5]), .A1N (n_92), .B0 (n_137), .Y
       (out1[5]));
  OAI2BB1X1 g3828(.A0N (in4[3]), .A1N (n_96), .B0 (n_132), .Y
       (out1[3]));
  OAI2BB1X1 g3830(.A0N (in4[1]), .A1N (n_94), .B0 (n_136), .Y
       (out1[1]));
  OAI2BB1X1 g3831(.A0N (in4[0]), .A1N (n_93), .B0 (n_133), .Y
       (out1[0]));
  NOR3BX1 g3856(.AN (n_42), .B (n_84), .C (n_98), .Y (n_143));
  AOI221X1 g3859(.A0 (in4[4]), .A1 (n_139), .B0 (in2[4]), .B1 (n_222),
       .C0 (n_105), .Y (n_142));
  NOR3BX1 g3857(.AN (n_44), .B (n_91), .C (n_106), .Y (n_141));
  AOI221X1 g3861(.A0 (in4[2]), .A1 (n_139), .B0 (in2[2]), .B1 (n_222),
       .C0 (n_103), .Y (n_140));
  AOI221X1 g3858(.A0 (in4[5]), .A1 (n_139), .B0 (in3[5]), .B1 (n_135),
       .C0 (n_86), .Y (n_137));
  AOI221X1 g3862(.A0 (in4[1]), .A1 (n_139), .B0 (in3[1]), .B1 (n_135),
       .C0 (n_88), .Y (n_136));
  AOI221X1 g3855(.A0 (in4[8]), .A1 (n_139), .B0 (in3[8]), .B1 (n_135),
       .C0 (n_87), .Y (n_134));
  AOI221X1 g3848(.A0 (in4[0]), .A1 (n_139), .B0 (in3[0]), .B1 (n_135),
       .C0 (n_85), .Y (n_133));
  AOI221X1 g3860(.A0 (in4[3]), .A1 (n_139), .B0 (in3[3]), .B1 (n_135),
       .C0 (n_90), .Y (n_132));
  AOI31X1 g3840(.A0 (n_49), .A1 (n_129), .A2 (n_128), .B0 (n_4), .Y
       (out1[26]));
  AOI31X1 g3844(.A0 (n_71), .A1 (n_129), .A2 (n_128), .B0 (n_9), .Y
       (out1[30]));
  AOI31X1 g3850(.A0 (n_66), .A1 (n_129), .A2 (n_128), .B0 (n_6), .Y
       (out1[29]));
  AOI31X1 g3837(.A0 (n_59), .A1 (n_129), .A2 (n_128), .B0 (n_0), .Y
       (out1[28]));
  AOI31X1 g3833(.A0 (n_68), .A1 (n_129), .A2 (n_128), .B0 (n_2), .Y
       (out1[27]));
  AOI31X1 g3847(.A0 (n_63), .A1 (n_129), .A2 (n_128), .B0 (n_8), .Y
       (out1[31]));
  AOI31X1 g3846(.A0 (n_57), .A1 (n_129), .A2 (n_128), .B0 (n_18), .Y
       (out1[25]));
  AOI31X1 g3863(.A0 (n_67), .A1 (n_129), .A2 (n_128), .B0 (n_24), .Y
       (out1[24]));
  AOI31X1 g3851(.A0 (n_65), .A1 (n_129), .A2 (n_128), .B0 (n_12), .Y
       (out1[23]));
  AOI31X1 g3834(.A0 (n_61), .A1 (n_129), .A2 (n_128), .B0 (n_10), .Y
       (out1[22]));
  AOI31X1 g3836(.A0 (n_58), .A1 (n_129), .A2 (n_128), .B0 (n_22), .Y
       (out1[21]));
  AOI31X1 g3832(.A0 (n_50), .A1 (n_129), .A2 (n_128), .B0 (n_3), .Y
       (out1[14]));
  AOI31X1 g3839(.A0 (n_53), .A1 (n_129), .A2 (n_128), .B0 (n_23), .Y
       (out1[19]));
  AOI31X1 g3841(.A0 (n_51), .A1 (n_129), .A2 (n_128), .B0 (n_21), .Y
       (out1[18]));
  AOI31X1 g3842(.A0 (n_56), .A1 (n_129), .A2 (n_128), .B0 (n_7), .Y
       (out1[17]));
  AOI31X1 g3843(.A0 (n_64), .A1 (n_129), .A2 (n_128), .B0 (n_1), .Y
       (out1[16]));
  AOI31X1 g3845(.A0 (n_60), .A1 (n_129), .A2 (n_128), .B0 (n_20), .Y
       (out1[15]));
  AOI31X1 g3838(.A0 (n_54), .A1 (n_129), .A2 (n_128), .B0 (n_25), .Y
       (out1[20]));
  AOI31X1 g3849(.A0 (n_72), .A1 (n_129), .A2 (n_128), .B0 (n_16), .Y
       (out1[13]));
  AOI31X1 g3852(.A0 (n_48), .A1 (n_129), .A2 (n_128), .B0 (n_5), .Y
       (out1[12]));
  AOI31X1 g3853(.A0 (n_52), .A1 (n_129), .A2 (n_128), .B0 (n_14), .Y
       (out1[11]));
  AOI31X1 g3835(.A0 (n_62), .A1 (n_129), .A2 (n_128), .B0 (n_19), .Y
       (out1[9]));
  AOI31X1 g3854(.A0 (n_55), .A1 (n_129), .A2 (n_128), .B0 (n_11), .Y
       (out1[10]));
  NOR2BX1 g3877(.AN (in3[6]), .B (n_214), .Y (n_106));
  NOR2BX1 g3879(.AN (in3[4]), .B (n_218), .Y (n_105));
  NOR2BX1 g3881(.AN (in3[2]), .B (n_218), .Y (n_103));
  NAND2XL g3864(.A (n_100), .B (n_78), .Y (n_102));
  NAND2XL g3865(.A (n_100), .B (n_83), .Y (n_101));
  NAND2XL g3866(.A (n_100), .B (n_79), .Y (n_99));
  NOR2BX1 g3875(.AN (in3[7]), .B (n_213), .Y (n_98));
  NAND2XL g3868(.A (n_100), .B (n_75), .Y (n_97));
  NAND2XL g3869(.A (n_100), .B (n_76), .Y (n_96));
  NAND2XL g3870(.A (n_100), .B (n_74), .Y (n_95));
  NAND2XL g3871(.A (n_100), .B (n_77), .Y (n_94));
  NAND2XL g3872(.A (n_100), .B (n_73), .Y (n_93));
  NAND2XL g3867(.A (n_100), .B (n_82), .Y (n_92));
  NOR2BX1 g3876(.AN (in2[6]), .B (n_89), .Y (n_91));
  NOR2BX1 g3880(.AN (in2[3]), .B (n_89), .Y (n_90));
  NOR2BX1 g3882(.AN (in2[1]), .B (n_89), .Y (n_88));
  NOR2BX1 g3873(.AN (in2[8]), .B (n_89), .Y (n_87));
  NOR2BX1 g3878(.AN (in2[5]), .B (n_89), .Y (n_86));
  NOR2BX1 g3883(.AN (in2[0]), .B (n_89), .Y (n_85));
  NOR2BX1 g3874(.AN (in2[7]), .B (n_89), .Y (n_84));
  NOR2XL g3886(.A (n_81), .B (n_80), .Y (n_83));
  NOR2XL g3885(.A (n_81), .B (n_80), .Y (n_82));
  NOR2XL g3884(.A (n_81), .B (n_80), .Y (n_79));
  NOR2XL g3887(.A (n_81), .B (n_80), .Y (n_78));
  NOR2XL g3888(.A (n_81), .B (n_80), .Y (n_77));
  NOR2XL g3889(.A (n_81), .B (n_80), .Y (n_76));
  NOR2XL g3890(.A (n_81), .B (n_80), .Y (n_75));
  NOR2XL g3891(.A (n_81), .B (n_80), .Y (n_74));
  NOR2XL g3892(.A (n_81), .B (n_80), .Y (n_73));
  NOR2X1 g3914(.A (n_70), .B (n_69), .Y (n_72));
  NOR2X1 g3915(.A (n_70), .B (n_69), .Y (n_71));
  NOR2X1 g3918(.A (n_70), .B (n_69), .Y (n_68));
  NOR2X1 g3916(.A (n_70), .B (n_69), .Y (n_67));
  NOR2X1 g3898(.A (n_70), .B (n_69), .Y (n_66));
  NOR2X1 g3897(.A (n_70), .B (n_69), .Y (n_65));
  NOR2X1 g3893(.A (n_70), .B (n_69), .Y (n_64));
  NOR2X1 g3894(.A (n_70), .B (n_69), .Y (n_63));
  NOR2X1 g3895(.A (n_70), .B (n_69), .Y (n_62));
  NOR2X1 g3896(.A (n_70), .B (n_69), .Y (n_61));
  NOR2X6 g3919(.A (n_30), .B (n_47), .Y (n_135));
  NAND2X6 g3920(.A (n_32), .B (n_43), .Y (n_89));
  NOR2X6 g3922(.A (n_139), .B (n_46), .Y (n_128));
  NOR2X1 g3913(.A (n_70), .B (n_69), .Y (n_60));
  NOR2X1 g3900(.A (n_70), .B (n_69), .Y (n_59));
  NOR2X1 g3901(.A (n_70), .B (n_69), .Y (n_58));
  NOR2X1 g3902(.A (n_70), .B (n_69), .Y (n_57));
  NOR2X1 g3903(.A (n_70), .B (n_69), .Y (n_56));
  NOR2X1 g3917(.A (n_70), .B (n_69), .Y (n_55));
  NOR2X1 g3904(.A (n_70), .B (n_69), .Y (n_54));
  NOR2X1 g3905(.A (n_70), .B (n_69), .Y (n_53));
  NOR2X1 g3899(.A (n_70), .B (n_69), .Y (n_52));
  NOR2X1 g3909(.A (n_70), .B (n_69), .Y (n_51));
  NOR2X1 g3910(.A (n_70), .B (n_69), .Y (n_50));
  NOR2X1 g3911(.A (n_70), .B (n_69), .Y (n_49));
  NOR2X1 g3912(.A (n_70), .B (n_69), .Y (n_48));
  NOR2X2 g3906(.A (n_234), .B (n_70), .Y (n_100));
  NAND2X4 g3921(.A (n_45), .B (n_41), .Y (n_80));
  NAND2X4 g3930(.A (n_28), .B (n_33), .Y (n_47));
  NAND2X4 g3928(.A (n_35), .B (n_45), .Y (n_46));
  NAND2XL g3923(.A (in4[6]), .B (n_139), .Y (n_44));
  NOR2X6 g3929(.A (n_38), .B (n_37), .Y (n_43));
  NAND2XL g3924(.A (in4[7]), .B (n_139), .Y (n_42));
  CLKINVX3 g3927(.A (n_81), .Y (n_129));
  NOR2X6 g3931(.A (n_230), .B (n_34), .Y (n_70));
  AOI21X2 g3925(.A0 (ctrl1[2]), .A1 (n_36), .B0 (n_39), .Y (n_41));
  NAND2X2 g3932(.A (n_15), .B (n_27), .Y (n_81));
  OR2X6 g3926(.A (n_40), .B (n_39), .Y (n_69));
  NAND2X8 g3935(.A (ctrl1[3]), .B (n_13), .Y (n_38));
  CLKINVX3 g3933(.A (n_26), .Y (n_37));
  NAND2X2 g3937(.A (ctrl1[1]), .B (n_36), .Y (n_45));
  NOR2X2 g3939(.A (ctrl1[3]), .B (n_238), .Y (n_139));
  NAND2X1 g3946(.A (ctrl1[2]), .B (n_36), .Y (n_35));
  NOR2X4 g3942(.A (ctrl1[2]), .B (n_36), .Y (n_34));
  NOR2X4 g3940(.A (ctrl1[3]), .B (n_232), .Y (n_33));
  NOR2X2 g3941(.A (n_236), .B (n_29), .Y (n_32));
  NAND2X2 g3934(.A (n_29), .B (n_237), .Y (n_30));
  NOR2X4 g3944(.A (ctrl1[5]), .B (ctrl1[2]), .Y (n_28));
  NOR2X4 g3945(.A (ctrl1[4]), .B (ctrl1[0]), .Y (n_39));
  NAND2X1 g3943(.A (ctrl1[4]), .B (ctrl1[3]), .Y (n_27));
  NOR2X4 g3936(.A (ctrl1[5]), .B (ctrl1[4]), .Y (n_26));
  NOR2X8 g3938(.A (ctrl1[4]), .B (ctrl1[1]), .Y (n_40));
  INVX1 g3950(.A (in4[20]), .Y (n_25));
  INVX1 g3961(.A (in4[24]), .Y (n_24));
  INVX1 g3969(.A (in4[19]), .Y (n_23));
  INVX1 g3963(.A (in4[21]), .Y (n_22));
  INVX1 g3967(.A (in4[18]), .Y (n_21));
  INVX1 g3962(.A (in4[15]), .Y (n_20));
  INVX1 g3949(.A (in4[9]), .Y (n_19));
  INVX1 g3972(.A (in4[25]), .Y (n_18));
  INVX1 g3968(.A (in4[13]), .Y (n_16));
  INVX1 g3958(.A (ctrl1[5]), .Y (n_15));
  INVX1 g3966(.A (in4[11]), .Y (n_14));
  CLKINVX12 g3975(.A (ctrl1[2]), .Y (n_13));
  INVX1 g3971(.A (in4[23]), .Y (n_12));
  INVX1 g3956(.A (in4[10]), .Y (n_11));
  INVX1 g3964(.A (in4[22]), .Y (n_10));
  INVX1 g3953(.A (in4[30]), .Y (n_9));
  INVX1 g3954(.A (in4[31]), .Y (n_8));
  INVX1 g3957(.A (in4[17]), .Y (n_7));
  INVX1 g3965(.A (in4[29]), .Y (n_6));
  INVX1 g3952(.A (in4[12]), .Y (n_5));
  INVX1 g3951(.A (in4[26]), .Y (n_4));
  INVX1 g3970(.A (in4[14]), .Y (n_3));
  INVX1 g3955(.A (in4[27]), .Y (n_2));
  INVX1 g3947(.A (in4[16]), .Y (n_1));
  INVX1 g3948(.A (in4[28]), .Y (n_0));
  INVX2 g3974(.A (ctrl1[1]), .Y (n_29));
  CLKINVX4 g3960(.A (ctrl1[3]), .Y (n_36));
  INVXL fopt3977(.A (n_135), .Y (n_213));
  INVXL fopt3978(.A (n_135), .Y (n_214));
  CLKINVX3 fopt3979(.A (n_135), .Y (n_218));
  CLKINVX3 fopt3980(.A (n_89), .Y (n_222));
  BUFX3 fopt3984(.A (ctrl1[4]), .Y (n_230));
  CLKINVX4 fopt3985(.A (ctrl1[4]), .Y (n_232));
  BUFX3 fopt(.A (n_40), .Y (n_234));
  CLKINVX3 fopt3986(.A (ctrl1[0]), .Y (n_236));
  CLKINVX1 fopt3987(.A (ctrl1[0]), .Y (n_237));
  CLKINVX2 fopt3988(.A (ctrl1[0]), .Y (n_238));
endmodule

