`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 05:59:54 CST (May 25 2023 21:59:54 UTC)

module SobelFilter_N_Mux_32_4_58_4(in5, in4, in3, in2, ctrl1, out1);
  input [31:0] in5;
  input [8:0] in4, in3, in2;
  input [5:0] ctrl1;
  output [31:0] out1;
  wire [31:0] in5;
  wire [8:0] in4, in3, in2;
  wire [5:0] ctrl1;
  wire [31:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_58, n_68;
  OAI2BB1X1 g3077(.A0N (in5[6]), .A1N (n_68), .B0 (n_29), .Y (out1[6]));
  OAI2BB1X1 g3086(.A0N (in5[7]), .A1N (n_68), .B0 (n_28), .Y (out1[7]));
  OAI2BB1X1 g3074(.A0N (in5[8]), .A1N (n_68), .B0 (n_26), .Y (out1[8]));
  OAI2BB1X1 g3076(.A0N (in5[5]), .A1N (n_68), .B0 (n_32), .Y (out1[5]));
  OAI2BB1X1 g3072(.A0N (in5[2]), .A1N (n_68), .B0 (n_30), .Y (out1[2]));
  OAI2BB1X1 g3073(.A0N (in5[3]), .A1N (n_68), .B0 (n_35), .Y (out1[3]));
  OAI2BB1X1 g3079(.A0N (in5[4]), .A1N (n_68), .B0 (n_31), .Y (out1[4]));
  OAI2BB1X1 g3075(.A0N (in5[1]), .A1N (n_68), .B0 (n_27), .Y (out1[1]));
  OAI2BB1X1 g3078(.A0N (in5[0]), .A1N (n_68), .B0 (n_36), .Y (out1[0]));
  AND2XL g3100(.A (in5[28]), .B (n_58), .Y (out1[28]));
  AND2XL g3108(.A (in5[12]), .B (n_58), .Y (out1[12]));
  AND2XL g3092(.A (in5[31]), .B (n_58), .Y (out1[31]));
  AND2XL g3094(.A (in5[30]), .B (n_58), .Y (out1[30]));
  AND2XL g3103(.A (in5[29]), .B (n_58), .Y (out1[29]));
  AND2XL g3091(.A (in5[9]), .B (n_58), .Y (out1[9]));
  AND2XL g3096(.A (in5[20]), .B (n_58), .Y (out1[20]));
  AND2XL g3101(.A (in5[27]), .B (n_58), .Y (out1[27]));
  AND2XL g3110(.A (in5[26]), .B (n_58), .Y (out1[26]));
  AND2XL g3095(.A (in5[25]), .B (n_58), .Y (out1[25]));
  AND2XL g3090(.A (in5[24]), .B (n_58), .Y (out1[24]));
  AND2XL g3104(.A (in5[15]), .B (n_58), .Y (out1[15]));
  AND2XL g3089(.A (in5[22]), .B (n_58), .Y (out1[22]));
  AND2XL g3097(.A (in5[21]), .B (n_58), .Y (out1[21]));
  AND2XL g3099(.A (in5[18]), .B (n_58), .Y (out1[18]));
  AND2XL g3107(.A (in5[17]), .B (n_58), .Y (out1[17]));
  AND2XL g3102(.A (in5[16]), .B (n_58), .Y (out1[16]));
  AND2XL g3093(.A (in5[23]), .B (n_58), .Y (out1[23]));
  AND2XL g3105(.A (in5[14]), .B (n_58), .Y (out1[14]));
  AND2XL g3106(.A (in5[13]), .B (n_58), .Y (out1[13]));
  AND2XL g3109(.A (in5[11]), .B (n_58), .Y (out1[11]));
  AND2XL g3111(.A (in5[10]), .B (n_58), .Y (out1[10]));
  AND2XL g3098(.A (in5[19]), .B (n_58), .Y (out1[19]));
  AOI221X1 g3084(.A0 (in4[0]), .A1 (n_34), .B0 (in3[0]), .B1 (n_33),
       .C0 (n_17), .Y (n_36));
  AOI221X1 g3081(.A0 (in4[3]), .A1 (n_34), .B0 (in3[3]), .B1 (n_33),
       .C0 (n_25), .Y (n_35));
  AOI221X1 g3088(.A0 (in4[5]), .A1 (n_34), .B0 (in3[5]), .B1 (n_33),
       .C0 (n_14), .Y (n_32));
  AOI221X1 g3082(.A0 (in4[4]), .A1 (n_34), .B0 (in3[4]), .B1 (n_33),
       .C0 (n_20), .Y (n_31));
  AOI221X1 g3080(.A0 (in4[2]), .A1 (n_34), .B0 (in3[2]), .B1 (n_33),
       .C0 (n_24), .Y (n_30));
  AOI221X1 g3087(.A0 (in4[6]), .A1 (n_34), .B0 (in3[6]), .B1 (n_33),
       .C0 (n_15), .Y (n_29));
  AOI221X1 g3112(.A0 (in3[7]), .A1 (n_33), .B0 (in4[7]), .B1 (n_34),
       .C0 (n_18), .Y (n_28));
  AOI221X1 g3085(.A0 (in4[1]), .A1 (n_34), .B0 (in3[1]), .B1 (n_33),
       .C0 (n_19), .Y (n_27));
  AOI221X1 g3083(.A0 (in4[8]), .A1 (n_34), .B0 (in3[8]), .B1 (n_33),
       .C0 (n_16), .Y (n_26));
  NAND4XL g3122(.A (n_6), .B (n_12), .C (n_9), .D (n_22), .Y (n_68));
  OR4X1 g3123(.A (n_11), .B (n_21), .C (n_7), .D (n_13), .Y (n_58));
  NOR2BX1 g3114(.AN (in2[3]), .B (n_23), .Y (n_25));
  NOR2BX1 g3113(.AN (in2[2]), .B (n_23), .Y (n_24));
  INVXL g3125(.A (n_21), .Y (n_22));
  NOR2BX1 g3115(.AN (in2[4]), .B (n_23), .Y (n_20));
  NOR2BX1 g3116(.AN (in2[1]), .B (n_23), .Y (n_19));
  NOR2BX1 g3119(.AN (in2[7]), .B (n_23), .Y (n_18));
  NOR2BX1 g3118(.AN (in2[0]), .B (n_23), .Y (n_17));
  NOR2BX1 g3117(.AN (in2[8]), .B (n_23), .Y (n_16));
  NOR2BX1 g3120(.AN (in2[6]), .B (n_23), .Y (n_15));
  NOR2BX1 g3121(.AN (in2[5]), .B (n_23), .Y (n_14));
  NAND2X1 g3126(.A (n_8), .B (n_12), .Y (n_13));
  OAI22X1 g3127(.A0 (n_10), .A1 (n_3), .B0 (ctrl1[1]), .B1 (ctrl1[0]),
       .Y (n_21));
  NOR4X1 g3128(.A (n_4), .B (ctrl1[3]), .C (n_5), .D (n_11), .Y (n_33));
  NOR4X1 g3129(.A (n_10), .B (ctrl1[2]), .C (n_2), .D (n_11), .Y
       (n_34));
  NAND4X1 g3124(.A (n_0), .B (ctrl1[0]), .C (n_10), .D (n_1), .Y
       (n_23));
  NOR2BX1 g3130(.AN (n_8), .B (n_11), .Y (n_9));
  INVX1 g3131(.A (n_6), .Y (n_7));
  NAND2X1 g3132(.A (ctrl1[2]), .B (n_5), .Y (n_6));
  NAND3X1 g3133(.A (ctrl1[1]), .B (n_10), .C (n_4), .Y (n_12));
  INVXL g3136(.A (n_2), .Y (n_3));
  INVX1 g3137(.A (n_1), .Y (n_11));
  NOR2X1 g3134(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_0));
  NAND2X1 g3138(.A (ctrl1[3]), .B (ctrl1[2]), .Y (n_8));
  NAND2BX1 g3135(.AN (ctrl1[0]), .B (ctrl1[1]), .Y (n_5));
  NAND2X1 g3139(.A (ctrl1[1]), .B (ctrl1[0]), .Y (n_2));
  NOR2X1 g3140(.A (ctrl1[5]), .B (ctrl1[4]), .Y (n_1));
  INVX1 g3141(.A (ctrl1[2]), .Y (n_4));
  INVX1 g3142(.A (ctrl1[3]), .Y (n_10));
endmodule

