`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 05:58:29 CST (May 25 2023 21:58:29 UTC)

module SobelFilter_OrReduction_2U_1U_4(in1, out1);
  input [1:0] in1;
  output out1;
  wire [1:0] in1;
  wire out1;
  OR2XL g4(.A (in1[1]), .B (in1[0]), .Y (out1));
endmodule

