`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:09:36 CST (May 25 2023 22:09:36 UTC)

module SobelFilter_N_Mux_20_4_7_1(in5, in4, in3, in2, ctrl1, out1);
  input [19:0] in5, in4, in3, in2;
  input [4:0] ctrl1;
  output [19:0] out1;
  wire [19:0] in5, in4, in3, in2;
  wire [4:0] ctrl1;
  wire [19:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_83, n_183;
  NAND3X1 g320(.A (n_46), .B (n_30), .C (n_70), .Y (out1[10]));
  NAND3X1 g318(.A (n_48), .B (n_38), .C (n_69), .Y (out1[11]));
  NAND3X1 g302(.A (n_45), .B (n_24), .C (n_67), .Y (out1[19]));
  NAND3X1 g308(.A (n_47), .B (n_28), .C (n_66), .Y (out1[7]));
  NAND3X1 g310(.A (n_44), .B (n_23), .C (n_71), .Y (out1[6]));
  NAND3X1 g316(.A (n_63), .B (n_32), .C (n_64), .Y (out1[3]));
  NAND3X1 g312(.A (n_55), .B (n_37), .C (n_74), .Y (out1[4]));
  NAND3X1 g311(.A (n_58), .B (n_22), .C (n_68), .Y (out1[5]));
  NAND3X1 g317(.A (n_51), .B (n_33), .C (n_65), .Y (out1[2]));
  NAND3X1 g319(.A (n_56), .B (n_35), .C (n_73), .Y (out1[1]));
  OAI211X1 g321(.A0 (n_7), .A1 (n_83), .B0 (n_40), .C0 (n_41), .Y
       (out1[0]));
  OAI211X1 g303(.A0 (n_3), .A1 (n_83), .B0 (n_52), .C0 (n_36), .Y
       (out1[17]));
  OAI211X1 g313(.A0 (n_4), .A1 (n_83), .B0 (n_53), .C0 (n_25), .Y
       (out1[18]));
  OAI211X1 g304(.A0 (n_6), .A1 (n_83), .B0 (n_43), .C0 (n_26), .Y
       (out1[15]));
  OAI211X1 g307(.A0 (n_8), .A1 (n_83), .B0 (n_50), .C0 (n_27), .Y
       (out1[14]));
  OAI211X1 g305(.A0 (n_5), .A1 (n_83), .B0 (n_42), .C0 (n_31), .Y
       (out1[9]));
  OAI211X1 g315(.A0 (n_0), .A1 (n_83), .B0 (n_54), .C0 (n_34), .Y
       (out1[12]));
  OAI211X1 g309(.A0 (n_9), .A1 (n_83), .B0 (n_60), .C0 (n_21), .Y
       (out1[13]));
  OAI211X1 g306(.A0 (n_1), .A1 (n_83), .B0 (n_62), .C0 (n_29), .Y
       (out1[8]));
  OAI211X1 g314(.A0 (n_2), .A1 (n_83), .B0 (n_49), .C0 (n_39), .Y
       (out1[16]));
  NAND2XL g326(.A (in5[4]), .B (n_72), .Y (n_74));
  NAND2XL g330(.A (in5[1]), .B (n_72), .Y (n_73));
  NAND2XL g322(.A (in5[6]), .B (n_72), .Y (n_71));
  NAND2XL g324(.A (in5[10]), .B (n_72), .Y (n_70));
  NAND2XL g331(.A (in5[11]), .B (n_72), .Y (n_69));
  NAND2XL g325(.A (in5[5]), .B (n_72), .Y (n_68));
  NAND2XL g327(.A (in5[19]), .B (n_72), .Y (n_67));
  NAND2XL g323(.A (in5[7]), .B (n_72), .Y (n_66));
  NAND2XL g328(.A (in5[2]), .B (n_72), .Y (n_65));
  NAND2XL g329(.A (in5[3]), .B (n_72), .Y (n_64));
  CLKINVX4 g332(.A (n_72), .Y (n_83));
  AOI22X1 g343(.A0 (in3[3]), .A1 (n_61), .B0 (in4[3]), .B1 (n_57), .Y
       (n_63));
  AOI22X1 g335(.A0 (in2[8]), .A1 (n_59), .B0 (in3[8]), .B1 (n_61), .Y
       (n_62));
  AOI22X1 g344(.A0 (in2[13]), .A1 (n_59), .B0 (in3[13]), .B1 (n_61), .Y
       (n_60));
  AOI22X1 g345(.A0 (in3[5]), .A1 (n_61), .B0 (in4[5]), .B1 (n_57), .Y
       (n_58));
  AOI22X1 g336(.A0 (in3[1]), .A1 (n_61), .B0 (in4[1]), .B1 (n_57), .Y
       (n_56));
  AOI22X1 g346(.A0 (in3[4]), .A1 (n_61), .B0 (in4[4]), .B1 (n_57), .Y
       (n_55));
  AOI22X1 g347(.A0 (in2[12]), .A1 (n_59), .B0 (in3[12]), .B1 (n_61), .Y
       (n_54));
  AOI22X1 g337(.A0 (in2[18]), .A1 (n_59), .B0 (in3[18]), .B1 (n_61), .Y
       (n_53));
  AOI22X1 g348(.A0 (in2[17]), .A1 (n_59), .B0 (in3[17]), .B1 (n_61), .Y
       (n_52));
  AOI22X1 g349(.A0 (in3[2]), .A1 (n_61), .B0 (in4[2]), .B1 (n_57), .Y
       (n_51));
  AOI22X1 g338(.A0 (in2[14]), .A1 (n_59), .B0 (in3[14]), .B1 (n_61), .Y
       (n_50));
  AOI22X1 g350(.A0 (in2[16]), .A1 (n_59), .B0 (in3[16]), .B1 (n_61), .Y
       (n_49));
  AOI22X1 g351(.A0 (in3[11]), .A1 (n_61), .B0 (in4[11]), .B1 (n_57), .Y
       (n_48));
  AOI22X1 g339(.A0 (in3[7]), .A1 (n_61), .B0 (in4[7]), .B1 (n_57), .Y
       (n_47));
  AOI22X1 g353(.A0 (in3[10]), .A1 (n_61), .B0 (in4[10]), .B1 (n_57), .Y
       (n_46));
  AOI22X1 g333(.A0 (in3[19]), .A1 (n_61), .B0 (in4[19]), .B1 (n_57), .Y
       (n_45));
  AOI22X1 g340(.A0 (in3[6]), .A1 (n_61), .B0 (in4[6]), .B1 (n_57), .Y
       (n_44));
  AOI22X1 g341(.A0 (in2[15]), .A1 (n_59), .B0 (in3[15]), .B1 (n_61), .Y
       (n_43));
  AOI22X1 g334(.A0 (in2[9]), .A1 (n_59), .B0 (in3[9]), .B1 (n_61), .Y
       (n_42));
  NOR3X6 g342(.A (n_59), .B (n_57), .C (n_61), .Y (n_72));
  NAND2XL g371(.A (in3[0]), .B (n_61), .Y (n_41));
  AOI22X1 g352(.A0 (in2[0]), .A1 (n_59), .B0 (in4[0]), .B1 (n_57), .Y
       (n_40));
  NAND2XL g372(.A (in4[16]), .B (n_57), .Y (n_39));
  NAND2X1 g364(.A (in2[11]), .B (n_183), .Y (n_38));
  NAND2X1 g365(.A (in2[4]), .B (n_183), .Y (n_37));
  NAND2XL g366(.A (in4[17]), .B (n_57), .Y (n_36));
  NAND2X1 g367(.A (in2[1]), .B (n_183), .Y (n_35));
  NAND2XL g368(.A (in4[12]), .B (n_57), .Y (n_34));
  NAND2X1 g369(.A (in2[2]), .B (n_183), .Y (n_33));
  NAND2X1 g370(.A (in2[3]), .B (n_183), .Y (n_32));
  NAND2XL g355(.A (in4[9]), .B (n_57), .Y (n_31));
  NAND2X1 g373(.A (in2[10]), .B (n_183), .Y (n_30));
  NAND2XL g357(.A (in4[8]), .B (n_57), .Y (n_29));
  NAND2X1 g354(.A (in2[7]), .B (n_183), .Y (n_28));
  NAND2XL g360(.A (in4[14]), .B (n_57), .Y (n_27));
  NAND2XL g356(.A (in4[15]), .B (n_57), .Y (n_26));
  NAND2XL g358(.A (in4[18]), .B (n_57), .Y (n_25));
  NAND2X1 g359(.A (in2[19]), .B (n_183), .Y (n_24));
  NAND2X1 g361(.A (in2[6]), .B (n_183), .Y (n_23));
  NAND2X1 g362(.A (in2[5]), .B (n_183), .Y (n_22));
  NAND2XL g363(.A (in4[13]), .B (n_57), .Y (n_21));
  NOR2X8 g375(.A (n_14), .B (n_20), .Y (n_61));
  NOR2X8 g376(.A (n_15), .B (n_18), .Y (n_59));
  NOR2X8 g374(.A (n_12), .B (n_19), .Y (n_57));
  NAND2X4 g379(.A (n_10), .B (n_17), .Y (n_20));
  NAND3X6 g377(.A (ctrl1[0]), .B (ctrl1[4]), .C (n_16), .Y (n_19));
  NAND2X4 g378(.A (ctrl1[0]), .B (n_13), .Y (n_18));
  NOR2X8 g381(.A (ctrl1[4]), .B (n_16), .Y (n_17));
  NAND2X4 g384(.A (ctrl1[2]), .B (n_11), .Y (n_15));
  NAND2X2 g380(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_14));
  NOR2X8 g382(.A (ctrl1[4]), .B (ctrl1[3]), .Y (n_13));
  NAND2X2 g383(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_12));
  INVX2 g397(.A (ctrl1[1]), .Y (n_11));
  INVX1 g389(.A (ctrl1[0]), .Y (n_10));
  INVX1 g393(.A (in5[13]), .Y (n_9));
  INVX1 g395(.A (in5[14]), .Y (n_8));
  INVX1 g394(.A (in5[0]), .Y (n_7));
  CLKINVX12 g396(.A (ctrl1[3]), .Y (n_16));
  INVX1 g386(.A (in5[15]), .Y (n_6));
  INVX1 g391(.A (in5[9]), .Y (n_5));
  INVX1 g388(.A (in5[18]), .Y (n_4));
  INVX1 g385(.A (in5[17]), .Y (n_3));
  INVX1 g390(.A (in5[16]), .Y (n_2));
  INVX1 g392(.A (in5[8]), .Y (n_1));
  INVX1 g387(.A (in5[12]), .Y (n_0));
  CLKBUFX3 fopt(.A (n_59), .Y (n_183));
endmodule

