`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:00:12 CST (May 25 2023 22:00:12 UTC)

module SobelFilter_N_Mux_32_4_42_4(in5, in4, in3, in2, ctrl1, out1);
  input [31:0] in5;
  input [8:0] in4, in3, in2;
  input [5:0] ctrl1;
  output [31:0] out1;
  wire [31:0] in5;
  wire [8:0] in4, in3, in2;
  wire [5:0] ctrl1;
  wire [31:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_64, n_87;
  NOR2BX1 g2906(.AN (in5[16]), .B (n_87), .Y (out1[16]));
  NOR2BX1 g2889(.AN (in5[30]), .B (n_87), .Y (out1[30]));
  NOR2BX1 g2892(.AN (in5[29]), .B (n_87), .Y (out1[29]));
  NOR2BX1 g2893(.AN (in5[28]), .B (n_87), .Y (out1[28]));
  NOR2BX1 g2901(.AN (in5[27]), .B (n_87), .Y (out1[27]));
  NOR2BX1 g2896(.AN (in5[26]), .B (n_87), .Y (out1[26]));
  NOR2BX1 g2897(.AN (in5[25]), .B (n_87), .Y (out1[25]));
  NOR2BX1 g2898(.AN (in5[24]), .B (n_87), .Y (out1[24]));
  NOR2BX1 g2904(.AN (in5[23]), .B (n_87), .Y (out1[23]));
  NOR2BX1 g2899(.AN (in5[22]), .B (n_87), .Y (out1[22]));
  NOR2BX1 g2900(.AN (in5[21]), .B (n_87), .Y (out1[21]));
  NOR2BX1 g2895(.AN (in5[20]), .B (n_87), .Y (out1[20]));
  NOR2BX1 g2902(.AN (in5[19]), .B (n_87), .Y (out1[19]));
  NOR2BX1 g2903(.AN (in5[18]), .B (n_87), .Y (out1[18]));
  NOR2BX1 g2905(.AN (in5[17]), .B (n_87), .Y (out1[17]));
  NOR2BX1 g2884(.AN (in5[31]), .B (n_87), .Y (out1[31]));
  OAI211X1 g2882(.A0 (n_7), .A1 (n_64), .B0 (n_53), .C0 (n_35), .Y
       (out1[0]));
  NOR2BX1 g2885(.AN (in5[14]), .B (n_87), .Y (out1[14]));
  NOR2BX1 g2887(.AN (in5[13]), .B (n_87), .Y (out1[13]));
  NOR2BX1 g2888(.AN (in5[12]), .B (n_87), .Y (out1[12]));
  NOR2BX1 g2890(.AN (in5[11]), .B (n_87), .Y (out1[11]));
  NOR2BX1 g2891(.AN (in5[10]), .B (n_87), .Y (out1[10]));
  NOR2BX1 g2894(.AN (in5[9]), .B (n_87), .Y (out1[9]));
  OAI211X1 g2877(.A0 (n_6), .A1 (n_64), .B0 (n_44), .C0 (n_42), .Y
       (out1[8]));
  OAI211X1 g2879(.A0 (n_4), .A1 (n_64), .B0 (n_37), .C0 (n_34), .Y
       (out1[7]));
  OAI211X1 g2883(.A0 (n_3), .A1 (n_64), .B0 (n_52), .C0 (n_41), .Y
       (out1[6]));
  OAI211X1 g2876(.A0 (n_0), .A1 (n_64), .B0 (n_40), .C0 (n_45), .Y
       (out1[5]));
  OAI211X1 g2875(.A0 (n_1), .A1 (n_64), .B0 (n_33), .C0 (n_49), .Y
       (out1[4]));
  OAI211X1 g2878(.A0 (n_9), .A1 (n_64), .B0 (n_43), .C0 (n_48), .Y
       (out1[3]));
  OAI211X1 g2881(.A0 (n_5), .A1 (n_64), .B0 (n_38), .C0 (n_39), .Y
       (out1[2]));
  OAI211X1 g2880(.A0 (n_2), .A1 (n_64), .B0 (n_32), .C0 (n_36), .Y
       (out1[1]));
  NOR2BX1 g2886(.AN (in5[15]), .B (n_87), .Y (out1[15]));
  AND2X1 g2911(.A (n_29), .B (n_55), .Y (n_87));
  NOR4X1 g2910(.A (n_54), .B (n_28), .C (n_31), .D (n_25), .Y (n_64));
  NOR4X1 g2927(.A (n_27), .B (n_54), .C (n_30), .D (n_18), .Y (n_55));
  AOI22X1 g2923(.A0 (in4[0]), .A1 (n_51), .B0 (in5[0]), .B1 (n_50), .Y
       (n_53));
  AOI22X1 g2920(.A0 (in4[6]), .A1 (n_51), .B0 (in5[6]), .B1 (n_50), .Y
       (n_52));
  AOI22X1 g2908(.A0 (in3[4]), .A1 (n_47), .B0 (in2[4]), .B1 (n_46), .Y
       (n_49));
  AOI22X1 g2912(.A0 (in3[3]), .A1 (n_47), .B0 (in2[3]), .B1 (n_46), .Y
       (n_48));
  AOI22X1 g2909(.A0 (in3[5]), .A1 (n_47), .B0 (in2[5]), .B1 (n_46), .Y
       (n_45));
  AOI22X1 g2921(.A0 (in4[8]), .A1 (n_51), .B0 (in5[8]), .B1 (n_50), .Y
       (n_44));
  AOI22X1 g2922(.A0 (in4[3]), .A1 (n_51), .B0 (in5[3]), .B1 (n_50), .Y
       (n_43));
  AOI22X1 g2913(.A0 (in3[8]), .A1 (n_47), .B0 (in2[8]), .B1 (n_46), .Y
       (n_42));
  AOI22X1 g2907(.A0 (in3[6]), .A1 (n_47), .B0 (in2[6]), .B1 (n_46), .Y
       (n_41));
  AOI22X1 g2919(.A0 (in4[5]), .A1 (n_51), .B0 (in5[5]), .B1 (n_50), .Y
       (n_40));
  AOI22X1 g2914(.A0 (in3[2]), .A1 (n_47), .B0 (in2[2]), .B1 (n_46), .Y
       (n_39));
  AOI22X1 g2925(.A0 (in4[2]), .A1 (n_51), .B0 (in5[2]), .B1 (n_50), .Y
       (n_38));
  AOI22X1 g2926(.A0 (in4[7]), .A1 (n_51), .B0 (in5[7]), .B1 (n_50), .Y
       (n_37));
  AOI22X1 g2915(.A0 (in3[1]), .A1 (n_47), .B0 (in2[1]), .B1 (n_46), .Y
       (n_36));
  AOI22X1 g2916(.A0 (in3[0]), .A1 (n_47), .B0 (in2[0]), .B1 (n_46), .Y
       (n_35));
  AOI22X1 g2917(.A0 (in3[7]), .A1 (n_47), .B0 (in2[7]), .B1 (n_46), .Y
       (n_34));
  AOI22X1 g2918(.A0 (in4[4]), .A1 (n_51), .B0 (in5[4]), .B1 (n_50), .Y
       (n_33));
  AOI22X1 g2924(.A0 (in4[1]), .A1 (n_51), .B0 (in5[1]), .B1 (n_50), .Y
       (n_32));
  NAND3BXL g2928(.AN (n_30), .B (n_19), .C (n_26), .Y (n_31));
  NOR4X1 g2929(.A (n_28), .B (n_50), .C (n_23), .D (n_22), .Y (n_29));
  NAND3BXL g2932(.AN (n_24), .B (n_26), .C (n_17), .Y (n_27));
  NOR4X1 g2930(.A (n_11), .B (ctrl1[0]), .C (n_14), .D (n_20), .Y
       (n_47));
  OR4X1 g2934(.A (n_24), .B (n_16), .C (n_23), .D (n_22), .Y (n_25));
  NOR3BX1 g2933(.AN (n_12), .B (n_21), .C (ctrl1[1]), .Y (n_51));
  NOR4X1 g2931(.A (n_10), .B (n_21), .C (ctrl1[3]), .D (n_20), .Y
       (n_46));
  INVXL g2936(.A (n_18), .Y (n_19));
  OAI32X1 g2935(.A0 (ctrl1[1]), .A1 (n_15), .A2 (ctrl1[3]), .B0 (n_8),
       .B1 (ctrl1[4]), .Y (n_28));
  INVXL g2945(.A (n_16), .Y (n_17));
  NOR3X1 g2937(.A (ctrl1[0]), .B (n_15), .C (n_13), .Y (n_54));
  NOR3X1 g2938(.A (n_15), .B (n_14), .C (n_13), .Y (n_18));
  NOR4X1 g2939(.A (ctrl1[5]), .B (ctrl1[4]), .C (ctrl1[3]), .D
       (ctrl1[2]), .Y (n_12));
  NAND2X1 g2942(.A (ctrl1[2]), .B (n_13), .Y (n_11));
  NAND3X1 g2940(.A (ctrl1[4]), .B (ctrl1[3]), .C (ctrl1[0]), .Y (n_26));
  NOR2X1 g2947(.A (n_15), .B (ctrl1[5]), .Y (n_24));
  NOR2X1 g2946(.A (n_13), .B (ctrl1[5]), .Y (n_22));
  NOR2X1 g2943(.A (n_15), .B (ctrl1[2]), .Y (n_30));
  NOR2X1 g2949(.A (n_14), .B (ctrl1[5]), .Y (n_16));
  NAND2X1 g2941(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_10));
  NAND2X1 g2948(.A (ctrl1[5]), .B (ctrl1[4]), .Y (n_20));
  NOR2BX1 g2944(.AN (ctrl1[2]), .B (ctrl1[5]), .Y (n_23));
  NOR2X1 g2950(.A (ctrl1[5]), .B (ctrl1[0]), .Y (n_50));
  INVX1 g2953(.A (in5[3]), .Y (n_9));
  INVX1 g2959(.A (ctrl1[5]), .Y (n_8));
  INVX1 g2956(.A (in5[0]), .Y (n_7));
  INVX1 g2960(.A (in5[8]), .Y (n_6));
  INVX1 g2957(.A (ctrl1[0]), .Y (n_21));
  INVX1 g2958(.A (ctrl1[3]), .Y (n_14));
  INVX1 g2963(.A (ctrl1[1]), .Y (n_13));
  INVX1 g2954(.A (in5[2]), .Y (n_5));
  INVX1 g2952(.A (in5[7]), .Y (n_4));
  INVX1 g2951(.A (in5[6]), .Y (n_3));
  INVX1 g2961(.A (in5[1]), .Y (n_2));
  INVX1 g2962(.A (in5[4]), .Y (n_1));
  INVX1 g2955(.A (in5[5]), .Y (n_0));
  INVX1 g2964(.A (ctrl1[4]), .Y (n_15));
endmodule

