`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 05:59:35 CST (May 25 2023 21:59:35 UTC)

module SobelFilter_N_Mux_32_3_68_4(in4, in3, in2, ctrl1, out1);
  input [31:0] in4;
  input [8:0] in3, in2;
  input [5:0] ctrl1;
  output [31:0] out1;
  wire [31:0] in4;
  wire [8:0] in3, in2;
  wire [5:0] ctrl1;
  wire [31:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_63, n_73;
  OAI211X1 g3041(.A0 (n_3), .A1 (n_73), .B0 (n_22), .C0 (n_37), .Y
       (out1[7]));
  OAI211X1 g3044(.A0 (n_4), .A1 (n_73), .B0 (n_21), .C0 (n_41), .Y
       (out1[5]));
  OAI211X1 g3040(.A0 (n_2), .A1 (n_73), .B0 (n_23), .C0 (n_40), .Y
       (out1[2]));
  OAI211X1 g3042(.A0 (n_1), .A1 (n_73), .B0 (n_32), .C0 (n_35), .Y
       (out1[8]));
  OAI211X1 g3045(.A0 (n_6), .A1 (n_73), .B0 (n_27), .C0 (n_25), .Y
       (out1[6]));
  OAI211X1 g3047(.A0 (n_8), .A1 (n_73), .B0 (n_26), .C0 (n_36), .Y
       (out1[4]));
  OAI211X1 g3048(.A0 (n_0), .A1 (n_73), .B0 (n_30), .C0 (n_33), .Y
       (out1[3]));
  OAI211X1 g3043(.A0 (n_7), .A1 (n_73), .B0 (n_24), .C0 (n_28), .Y
       (out1[1]));
  OAI211X1 g3046(.A0 (n_5), .A1 (n_73), .B0 (n_29), .C0 (n_31), .Y
       (out1[0]));
  NOR2BX1 g3067(.AN (in4[26]), .B (n_63), .Y (out1[26]));
  NOR2BX1 g3051(.AN (in4[30]), .B (n_63), .Y (out1[30]));
  NOR2BX1 g3055(.AN (in4[29]), .B (n_63), .Y (out1[29]));
  NOR2BX1 g3049(.AN (in4[28]), .B (n_63), .Y (out1[28]));
  NOR2BX1 g3060(.AN (in4[27]), .B (n_63), .Y (out1[27]));
  NOR2BX1 g3064(.AN (in4[31]), .B (n_63), .Y (out1[31]));
  NOR2BX1 g3070(.AN (in4[25]), .B (n_63), .Y (out1[25]));
  NOR2BX1 g3052(.AN (in4[24]), .B (n_63), .Y (out1[24]));
  NOR2BX1 g3050(.AN (in4[23]), .B (n_63), .Y (out1[23]));
  NOR2BX1 g3053(.AN (in4[22]), .B (n_63), .Y (out1[22]));
  NOR2BX1 g3054(.AN (in4[21]), .B (n_63), .Y (out1[21]));
  NOR2BX1 g3063(.AN (in4[14]), .B (n_63), .Y (out1[14]));
  NOR2BX1 g3057(.AN (in4[19]), .B (n_63), .Y (out1[19]));
  NOR2BX1 g3058(.AN (in4[18]), .B (n_63), .Y (out1[18]));
  NOR2BX1 g3059(.AN (in4[17]), .B (n_63), .Y (out1[17]));
  NOR2BX1 g3061(.AN (in4[16]), .B (n_63), .Y (out1[16]));
  NOR2BX1 g3062(.AN (in4[15]), .B (n_63), .Y (out1[15]));
  NOR2BX1 g3056(.AN (in4[20]), .B (n_63), .Y (out1[20]));
  NOR2BX1 g3080(.AN (in4[13]), .B (n_63), .Y (out1[13]));
  NOR2BX1 g3066(.AN (in4[12]), .B (n_63), .Y (out1[12]));
  NOR2BX1 g3068(.AN (in4[11]), .B (n_63), .Y (out1[11]));
  NOR2BX1 g3069(.AN (in4[10]), .B (n_63), .Y (out1[10]));
  NOR2BX1 g3071(.AN (in4[9]), .B (n_63), .Y (out1[9]));
  AOI22X1 g3079(.A0 (in3[5]), .A1 (n_39), .B0 (in4[5]), .B1 (n_38), .Y
       (n_41));
  AOI22X1 g3073(.A0 (in3[2]), .A1 (n_39), .B0 (in4[2]), .B1 (n_38), .Y
       (n_40));
  AOI22X1 g3077(.A0 (in3[7]), .A1 (n_39), .B0 (in4[7]), .B1 (n_38), .Y
       (n_37));
  AOI22X1 g3065(.A0 (in2[4]), .A1 (n_34), .B0 (in4[4]), .B1 (n_38), .Y
       (n_36));
  AOI22X1 g3075(.A0 (in2[8]), .A1 (n_34), .B0 (in4[8]), .B1 (n_38), .Y
       (n_35));
  AOI22X1 g3072(.A0 (in2[3]), .A1 (n_34), .B0 (in4[3]), .B1 (n_38), .Y
       (n_33));
  NAND2X1 g3081(.A (in3[8]), .B (n_39), .Y (n_32));
  AOI22X1 g3076(.A0 (in2[0]), .A1 (n_34), .B0 (in4[0]), .B1 (n_38), .Y
       (n_31));
  NAND2X1 g3083(.A (in3[3]), .B (n_39), .Y (n_30));
  NAND2X1 g3085(.A (in3[0]), .B (n_39), .Y (n_29));
  AOI22X1 g3074(.A0 (in2[1]), .A1 (n_34), .B0 (in4[1]), .B1 (n_38), .Y
       (n_28));
  NAND2X1 g3087(.A (in3[6]), .B (n_39), .Y (n_27));
  NAND2X1 g3089(.A (in3[4]), .B (n_39), .Y (n_26));
  AOI22X1 g3078(.A0 (in2[6]), .A1 (n_34), .B0 (in4[6]), .B1 (n_38), .Y
       (n_25));
  NAND2X1 g3084(.A (in3[1]), .B (n_39), .Y (n_24));
  AND4X1 g3091(.A (n_10), .B (n_19), .C (n_17), .D (n_15), .Y (n_63));
  NAND2X1 g3082(.A (in2[2]), .B (n_34), .Y (n_23));
  NAND2X1 g3086(.A (in2[7]), .B (n_34), .Y (n_22));
  NAND2X1 g3088(.A (in2[5]), .B (n_34), .Y (n_21));
  NOR4X1 g3090(.A (n_14), .B (n_16), .C (n_20), .D (n_18), .Y (n_73));
  NOR4X1 g3092(.A (n_9), .B (ctrl1[0]), .C (n_13), .D (n_20), .Y
       (n_39));
  INVXL g3094(.A (n_18), .Y (n_19));
  INVXL g3096(.A (n_16), .Y (n_17));
  NOR4X1 g3093(.A (n_11), .B (ctrl1[3]), .C (n_12), .D (n_20), .Y
       (n_34));
  NOR2X1 g3095(.A (n_38), .B (n_14), .Y (n_15));
  AND2XL g3097(.A (n_13), .B (n_12), .Y (n_16));
  OAI22X1 g3098(.A0 (ctrl1[3]), .A1 (ctrl1[2]), .B0 (n_13), .B1 (n_11),
       .Y (n_18));
  INVXL g3099(.A (n_20), .Y (n_10));
  NAND2X1 g3102(.A (ctrl1[1]), .B (n_11), .Y (n_9));
  OR2X1 g3100(.A (ctrl1[5]), .B (ctrl1[4]), .Y (n_20));
  NOR2BX1 g3101(.AN (ctrl1[0]), .B (ctrl1[2]), .Y (n_38));
  NOR2X1 g3103(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_14));
  NAND2BX1 g3104(.AN (ctrl1[1]), .B (ctrl1[0]), .Y (n_12));
  INVX1 g3107(.A (in4[4]), .Y (n_8));
  INVX1 g3114(.A (in4[1]), .Y (n_7));
  INVX1 g3109(.A (in4[6]), .Y (n_6));
  INVX1 g3110(.A (in4[0]), .Y (n_5));
  INVX1 g3108(.A (ctrl1[2]), .Y (n_11));
  INVX1 g3111(.A (in4[5]), .Y (n_4));
  INVX1 g3106(.A (in4[7]), .Y (n_3));
  INVX1 g3112(.A (in4[2]), .Y (n_2));
  INVX1 g3113(.A (in4[8]), .Y (n_1));
  INVX1 g3105(.A (in4[3]), .Y (n_0));
  INVX1 g3115(.A (ctrl1[3]), .Y (n_13));
endmodule

