`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:00:13 CST (May 25 2023 22:00:13 UTC)

module SobelFilter_N_Mux_32_4_41_4(in5, in4, in3, in2, ctrl1, out1);
  input [31:0] in5;
  input [8:0] in4, in3, in2;
  input [5:0] ctrl1;
  output [31:0] out1;
  wire [31:0] in5;
  wire [8:0] in4, in3, in2;
  wire [5:0] ctrl1;
  wire [31:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_73, n_83;
  OAI211X1 g3011(.A0 (n_3), .A1 (n_83), .B0 (n_39), .C0 (n_50), .Y
       (out1[6]));
  OAI211X1 g3007(.A0 (n_0), .A1 (n_83), .B0 (n_42), .C0 (n_46), .Y
       (out1[7]));
  OAI211X1 g3005(.A0 (n_5), .A1 (n_83), .B0 (n_26), .C0 (n_34), .Y
       (out1[8]));
  OAI211X1 g3004(.A0 (n_1), .A1 (n_83), .B0 (n_35), .C0 (n_43), .Y
       (out1[5]));
  OAI211X1 g3009(.A0 (n_2), .A1 (n_83), .B0 (n_25), .C0 (n_37), .Y
       (out1[2]));
  OAI211X1 g3006(.A0 (n_7), .A1 (n_83), .B0 (n_28), .C0 (n_45), .Y
       (out1[3]));
  OAI211X1 g3003(.A0 (n_4), .A1 (n_83), .B0 (n_36), .C0 (n_30), .Y
       (out1[4]));
  OAI211X1 g3008(.A0 (n_8), .A1 (n_83), .B0 (n_29), .C0 (n_27), .Y
       (out1[1]));
  OAI211X1 g3010(.A0 (n_6), .A1 (n_83), .B0 (n_44), .C0 (n_49), .Y
       (out1[0]));
  AND2XL g3024(.A (in5[23]), .B (n_73), .Y (out1[23]));
  AND2XL g3018(.A (in5[27]), .B (n_73), .Y (out1[27]));
  AND2XL g3021(.A (in5[26]), .B (n_73), .Y (out1[26]));
  AND2XL g3022(.A (in5[25]), .B (n_73), .Y (out1[25]));
  AND2XL g3023(.A (in5[24]), .B (n_73), .Y (out1[24]));
  AND2XL g3017(.A (in5[28]), .B (n_73), .Y (out1[28]));
  AND2XL g3025(.A (in5[22]), .B (n_73), .Y (out1[22]));
  AND2XL g3030(.A (in5[21]), .B (n_73), .Y (out1[21]));
  AND2XL g3026(.A (in5[20]), .B (n_73), .Y (out1[20]));
  AND2XL g3028(.A (in5[19]), .B (n_73), .Y (out1[19]));
  AND2XL g3029(.A (in5[18]), .B (n_73), .Y (out1[18]));
  AND2XL g3015(.A (in5[11]), .B (n_73), .Y (out1[11]));
  AND2XL g3031(.A (in5[16]), .B (n_73), .Y (out1[16]));
  AND2XL g3033(.A (in5[15]), .B (n_73), .Y (out1[15]));
  AND2XL g3034(.A (in5[14]), .B (n_73), .Y (out1[14]));
  AND2XL g3013(.A (in5[13]), .B (n_73), .Y (out1[13]));
  AND2XL g3014(.A (in5[12]), .B (n_73), .Y (out1[12]));
  AND2XL g3032(.A (in5[17]), .B (n_73), .Y (out1[17]));
  AND2XL g3016(.A (in5[10]), .B (n_73), .Y (out1[10]));
  AND2XL g3019(.A (in5[29]), .B (n_73), .Y (out1[29]));
  AND2XL g3020(.A (in5[9]), .B (n_73), .Y (out1[9]));
  AND2XL g3027(.A (in5[31]), .B (n_73), .Y (out1[31]));
  AND2XL g3012(.A (in5[30]), .B (n_73), .Y (out1[30]));
  AND3XL g3044(.A (n_38), .B (n_23), .C (n_51), .Y (n_83));
  NAND3X1 g3055(.A (n_33), .B (n_51), .C (n_24), .Y (n_73));
  AOI22X1 g3036(.A0 (in2[6]), .A1 (n_48), .B0 (in3[6]), .B1 (n_47), .Y
       (n_50));
  AOI22X1 g3043(.A0 (in2[0]), .A1 (n_48), .B0 (in3[0]), .B1 (n_47), .Y
       (n_49));
  AOI22X1 g3035(.A0 (in2[7]), .A1 (n_48), .B0 (in3[7]), .B1 (n_47), .Y
       (n_46));
  AOI22X1 g3039(.A0 (in2[3]), .A1 (n_48), .B0 (in3[3]), .B1 (n_47), .Y
       (n_45));
  AOI22X1 g3051(.A0 (in4[0]), .A1 (n_41), .B0 (in5[0]), .B1 (n_40), .Y
       (n_44));
  AOI22X1 g3037(.A0 (in2[5]), .A1 (n_48), .B0 (in3[5]), .B1 (n_47), .Y
       (n_43));
  AOI22X1 g3052(.A0 (in4[7]), .A1 (n_41), .B0 (in5[7]), .B1 (n_40), .Y
       (n_42));
  AOI22X1 g3053(.A0 (in4[6]), .A1 (n_41), .B0 (in5[6]), .B1 (n_40), .Y
       (n_39));
  NOR4X1 g3054(.A (n_20), .B (n_22), .C (n_31), .D (n_32), .Y (n_38));
  AOI22X1 g3040(.A0 (in2[2]), .A1 (n_48), .B0 (in3[2]), .B1 (n_47), .Y
       (n_37));
  AOI22X1 g3045(.A0 (in4[4]), .A1 (n_41), .B0 (in5[4]), .B1 (n_40), .Y
       (n_36));
  AOI22X1 g3046(.A0 (in4[5]), .A1 (n_41), .B0 (in5[5]), .B1 (n_40), .Y
       (n_35));
  AOI22X1 g3041(.A0 (in2[8]), .A1 (n_48), .B0 (in3[8]), .B1 (n_47), .Y
       (n_34));
  NOR4X1 g3056(.A (n_18), .B (n_32), .C (n_31), .D (n_19), .Y (n_33));
  AOI22X1 g3038(.A0 (in2[4]), .A1 (n_48), .B0 (in3[4]), .B1 (n_47), .Y
       (n_30));
  AOI22X1 g3047(.A0 (in4[1]), .A1 (n_41), .B0 (in5[1]), .B1 (n_40), .Y
       (n_29));
  AOI22X1 g3048(.A0 (in4[3]), .A1 (n_41), .B0 (in5[3]), .B1 (n_40), .Y
       (n_28));
  AOI22X1 g3042(.A0 (in2[1]), .A1 (n_48), .B0 (in3[1]), .B1 (n_47), .Y
       (n_27));
  AOI22X1 g3049(.A0 (in4[8]), .A1 (n_41), .B0 (in5[8]), .B1 (n_40), .Y
       (n_26));
  AOI22X1 g3050(.A0 (in4[2]), .A1 (n_41), .B0 (in5[2]), .B1 (n_40), .Y
       (n_25));
  NOR2BX1 g3059(.AN (n_23), .B (n_22), .Y (n_24));
  NOR4X1 g3057(.A (n_12), .B (ctrl1[0]), .C (ctrl1[3]), .D (n_21), .Y
       (n_48));
  NOR4X1 g3058(.A (n_9), .B (n_15), .C (ctrl1[3]), .D (n_21), .Y
       (n_47));
  NAND3BXL g3060(.AN (n_19), .B (n_16), .C (n_17), .Y (n_20));
  NAND3BXL g3061(.AN (n_40), .B (n_17), .C (n_16), .Y (n_18));
  NOR3X1 g3062(.A (n_14), .B (n_15), .C (ctrl1[1]), .Y (n_41));
  NAND3BXL g3063(.AN (ctrl1[2]), .B (ctrl1[0]), .C (n_13), .Y (n_23));
  NOR3X1 g3064(.A (ctrl1[0]), .B (n_11), .C (ctrl1[4]), .Y (n_32));
  NAND4XL g3065(.A (ctrl1[3]), .B (ctrl1[2]), .C (ctrl1[4]), .D (n_10),
       .Y (n_14));
  AOI22X1 g3066(.A0 (ctrl1[3]), .A1 (n_13), .B0 (ctrl1[5]), .B1
       (ctrl1[4]), .Y (n_51));
  NAND2X1 g3068(.A (ctrl1[1]), .B (n_11), .Y (n_12));
  NAND2X1 g3069(.A (ctrl1[1]), .B (n_10), .Y (n_16));
  NAND2X1 g3071(.A (n_10), .B (n_11), .Y (n_17));
  NAND2X1 g3075(.A (ctrl1[5]), .B (n_13), .Y (n_21));
  NAND2X1 g3067(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_9));
  NOR2X1 g3070(.A (ctrl1[5]), .B (ctrl1[0]), .Y (n_40));
  NOR2X1 g3072(.A (ctrl1[5]), .B (ctrl1[3]), .Y (n_19));
  NOR2X1 g3073(.A (ctrl1[5]), .B (ctrl1[4]), .Y (n_31));
  NOR2X1 g3074(.A (ctrl1[4]), .B (ctrl1[1]), .Y (n_22));
  INVX1 g3078(.A (in5[1]), .Y (n_8));
  INVX1 g3088(.A (in5[3]), .Y (n_7));
  INVX1 g3079(.A (in5[0]), .Y (n_6));
  INVX1 g3084(.A (in5[8]), .Y (n_5));
  INVX1 g3086(.A (in5[4]), .Y (n_4));
  INVX1 g3082(.A (ctrl1[5]), .Y (n_10));
  INVX1 g3085(.A (in5[6]), .Y (n_3));
  INVX1 g3087(.A (in5[2]), .Y (n_2));
  INVX1 g3077(.A (in5[5]), .Y (n_1));
  INVX1 g3076(.A (in5[7]), .Y (n_0));
  INVX1 g3080(.A (ctrl1[0]), .Y (n_15));
  INVX1 g3081(.A (ctrl1[2]), .Y (n_11));
  INVX1 g3083(.A (ctrl1[4]), .Y (n_13));
endmodule

