`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:00:20 CST (May 25 2023 22:00:20 UTC)

module SobelFilter_N_Mux_32_4_34_4(in5, in4, in3, in2, ctrl1, out1);
  input [31:0] in5;
  input [8:0] in4, in3, in2;
  input [5:0] ctrl1;
  output [31:0] out1;
  wire [31:0] in5;
  wire [8:0] in4, in3, in2;
  wire [5:0] ctrl1;
  wire [31:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_75, n_85;
  OAI211X1 g2869(.A0 (n_0), .A1 (n_85), .B0 (n_31), .C0 (n_49), .Y
       (out1[6]));
  OAI211X1 g2865(.A0 (n_8), .A1 (n_85), .B0 (n_35), .C0 (n_46), .Y
       (out1[7]));
  OAI211X1 g2863(.A0 (n_2), .A1 (n_85), .B0 (n_36), .C0 (n_44), .Y
       (out1[8]));
  OAI211X1 g2862(.A0 (n_9), .A1 (n_85), .B0 (n_32), .C0 (n_48), .Y
       (out1[5]));
  OAI211X1 g2867(.A0 (n_7), .A1 (n_85), .B0 (n_33), .C0 (n_47), .Y
       (out1[2]));
  OAI211X1 g2864(.A0 (n_6), .A1 (n_85), .B0 (n_40), .C0 (n_52), .Y
       (out1[3]));
  OAI211X1 g2861(.A0 (n_3), .A1 (n_85), .B0 (n_37), .C0 (n_53), .Y
       (out1[4]));
  OAI211X1 g2866(.A0 (n_1), .A1 (n_85), .B0 (n_41), .C0 (n_45), .Y
       (out1[1]));
  OAI211X1 g2868(.A0 (n_4), .A1 (n_85), .B0 (n_34), .C0 (n_42), .Y
       (out1[0]));
  NOR2BX1 g2871(.AN (in5[14]), .B (n_75), .Y (out1[14]));
  NOR2BX1 g2878(.AN (in5[29]), .B (n_75), .Y (out1[29]));
  NOR2BX1 g2877(.AN (in5[10]), .B (n_75), .Y (out1[10]));
  NOR2BX1 g2879(.AN (in5[28]), .B (n_75), .Y (out1[28]));
  NOR2BX1 g2887(.AN (in5[27]), .B (n_75), .Y (out1[27]));
  NOR2BX1 g2882(.AN (in5[26]), .B (n_75), .Y (out1[26]));
  NOR2BX1 g2875(.AN (in5[30]), .B (n_75), .Y (out1[30]));
  NOR2BX1 g2883(.AN (in5[25]), .B (n_75), .Y (out1[25]));
  NOR2BX1 g2884(.AN (in5[24]), .B (n_75), .Y (out1[24]));
  NOR2BX1 g2890(.AN (in5[23]), .B (n_75), .Y (out1[23]));
  NOR2BX1 g2885(.AN (in5[22]), .B (n_75), .Y (out1[22]));
  NOR2BX1 g2870(.AN (in5[31]), .B (n_75), .Y (out1[31]));
  NOR2BX1 g2874(.AN (in5[12]), .B (n_75), .Y (out1[12]));
  NOR2BX1 g2889(.AN (in5[18]), .B (n_75), .Y (out1[18]));
  NOR2BX1 g2891(.AN (in5[17]), .B (n_75), .Y (out1[17]));
  NOR2BX1 g2892(.AN (in5[16]), .B (n_75), .Y (out1[16]));
  NOR2BX1 g2872(.AN (in5[15]), .B (n_75), .Y (out1[15]));
  NOR2BX1 g2886(.AN (in5[21]), .B (n_75), .Y (out1[21]));
  NOR2BX1 g2888(.AN (in5[19]), .B (n_75), .Y (out1[19]));
  NOR2BX1 g2876(.AN (in5[11]), .B (n_75), .Y (out1[11]));
  NOR2BX1 g2881(.AN (in5[20]), .B (n_75), .Y (out1[20]));
  NOR2BX1 g2880(.AN (in5[9]), .B (n_75), .Y (out1[9]));
  NOR2BX1 g2873(.AN (in5[13]), .B (n_75), .Y (out1[13]));
  AND3XL g2896(.A (n_43), .B (n_29), .C (n_27), .Y (n_85));
  AOI22X1 g2894(.A0 (in3[4]), .A1 (n_51), .B0 (in4[4]), .B1 (n_50), .Y
       (n_53));
  AOI22X1 g2898(.A0 (in3[3]), .A1 (n_51), .B0 (in4[3]), .B1 (n_50), .Y
       (n_52));
  AOI22X1 g2893(.A0 (in3[6]), .A1 (n_51), .B0 (in4[6]), .B1 (n_50), .Y
       (n_49));
  AOI22X1 g2895(.A0 (in3[5]), .A1 (n_51), .B0 (in4[5]), .B1 (n_50), .Y
       (n_48));
  AOI22X1 g2899(.A0 (in3[2]), .A1 (n_51), .B0 (in4[2]), .B1 (n_50), .Y
       (n_47));
  AOI22X1 g2903(.A0 (in3[7]), .A1 (n_51), .B0 (in4[7]), .B1 (n_50), .Y
       (n_46));
  AOI22X1 g2901(.A0 (in3[1]), .A1 (n_51), .B0 (in4[1]), .B1 (n_50), .Y
       (n_45));
  AOI22X1 g2900(.A0 (in3[8]), .A1 (n_51), .B0 (in4[8]), .B1 (n_50), .Y
       (n_44));
  NOR4X1 g2914(.A (n_26), .B (n_13), .C (n_20), .D (n_12), .Y (n_43));
  AOI22X1 g2902(.A0 (in3[0]), .A1 (n_51), .B0 (in4[0]), .B1 (n_50), .Y
       (n_42));
  NOR2X1 g2897(.A (n_28), .B (n_30), .Y (n_75));
  AOI22X1 g2909(.A0 (in2[1]), .A1 (n_39), .B0 (in5[1]), .B1 (n_38), .Y
       (n_41));
  AOI22X1 g2908(.A0 (in2[3]), .A1 (n_39), .B0 (in5[3]), .B1 (n_38), .Y
       (n_40));
  AOI22X1 g2907(.A0 (in2[4]), .A1 (n_39), .B0 (in5[4]), .B1 (n_38), .Y
       (n_37));
  AOI22X1 g2910(.A0 (in2[8]), .A1 (n_39), .B0 (in5[8]), .B1 (n_38), .Y
       (n_36));
  AOI22X1 g2913(.A0 (in2[7]), .A1 (n_39), .B0 (in5[7]), .B1 (n_38), .Y
       (n_35));
  AOI22X1 g2912(.A0 (in2[0]), .A1 (n_39), .B0 (in5[0]), .B1 (n_38), .Y
       (n_34));
  AOI22X1 g2911(.A0 (in2[2]), .A1 (n_39), .B0 (in5[2]), .B1 (n_38), .Y
       (n_33));
  AOI22X1 g2904(.A0 (in2[5]), .A1 (n_39), .B0 (in5[5]), .B1 (n_38), .Y
       (n_32));
  AOI22X1 g2905(.A0 (in2[6]), .A1 (n_39), .B0 (in5[6]), .B1 (n_38), .Y
       (n_31));
  NAND4XL g2917(.A (n_29), .B (n_14), .C (n_23), .D (n_22), .Y (n_30));
  NAND4XL g2906(.A (n_27), .B (n_15), .C (n_24), .D (n_25), .Y (n_28));
  NAND4XL g2918(.A (n_21), .B (n_25), .C (n_24), .D (n_23), .Y (n_26));
  NOR4X1 g2915(.A (ctrl1[2]), .B (ctrl1[1]), .C (n_5), .D (n_19), .Y
       (n_51));
  AND3XL g2919(.A (n_17), .B (ctrl1[1]), .C (ctrl1[0]), .Y (n_39));
  NOR4X1 g2916(.A (n_10), .B (ctrl1[0]), .C (ctrl1[5]), .D (n_18), .Y
       (n_50));
  NOR2BX1 g2920(.AN (n_21), .B (n_20), .Y (n_22));
  OR2XL g2921(.A (ctrl1[5]), .B (n_18), .Y (n_19));
  AOI22X1 g2928(.A0 (ctrl1[3]), .A1 (n_11), .B0 (ctrl1[5]), .B1
       (ctrl1[4]), .Y (n_27));
  NAND3BXL g2927(.AN (ctrl1[1]), .B (ctrl1[2]), .C (n_16), .Y (n_25));
  NOR4X1 g2925(.A (n_16), .B (ctrl1[4]), .C (ctrl1[3]), .D (ctrl1[2]),
       .Y (n_17));
  INVXL g2924(.A (n_38), .Y (n_15));
  NOR2X1 g2922(.A (n_13), .B (n_12), .Y (n_14));
  NAND3BXL g2926(.AN (ctrl1[2]), .B (ctrl1[1]), .C (n_16), .Y (n_23));
  NAND2BXL g2931(.AN (ctrl1[3]), .B (n_16), .Y (n_21));
  NOR3X1 g2929(.A (ctrl1[1]), .B (ctrl1[5]), .C (ctrl1[0]), .Y (n_38));
  NAND2X1 g2936(.A (ctrl1[2]), .B (n_11), .Y (n_29));
  NAND3BXL g2923(.AN (ctrl1[5]), .B (ctrl1[0]), .C (ctrl1[2]), .Y
       (n_24));
  NOR2X1 g2930(.A (ctrl1[5]), .B (ctrl1[4]), .Y (n_20));
  NOR2X1 g2932(.A (ctrl1[4]), .B (ctrl1[1]), .Y (n_13));
  NAND2X1 g2933(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_10));
  NAND2X1 g2935(.A (ctrl1[4]), .B (ctrl1[3]), .Y (n_18));
  NOR2X1 g2934(.A (ctrl1[4]), .B (ctrl1[0]), .Y (n_12));
  INVX1 g2938(.A (in5[5]), .Y (n_9));
  INVX1 g2939(.A (in5[7]), .Y (n_8));
  INVX1 g2940(.A (in5[2]), .Y (n_7));
  INVX1 g2945(.A (in5[3]), .Y (n_6));
  INVX1 g2947(.A (ctrl1[0]), .Y (n_5));
  INVX1 g2948(.A (ctrl1[5]), .Y (n_16));
  INVX1 g2944(.A (in5[0]), .Y (n_4));
  INVX1 g2943(.A (in5[4]), .Y (n_3));
  INVX1 g2946(.A (in5[8]), .Y (n_2));
  INVX1 g2937(.A (in5[1]), .Y (n_1));
  INVX1 g2941(.A (in5[6]), .Y (n_0));
  INVX1 g2942(.A (ctrl1[4]), .Y (n_11));
endmodule

