`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 12:37:07 CST (May 26 2023 04:37:07 UTC)

module SobelFilter_Add_6S_19_4(in1, out1);
  input [5:0] in1;
  output [5:0] out1;
  wire [5:0] in1;
  wire [5:0] out1;
  wire add_21_2_n_1, add_21_2_n_3, add_21_2_n_4;
  assign out1[0] = in1[0];
  INVX1 g2(.A (in1[1]), .Y (out1[1]));
  XNOR2X1 add_21_2_g82(.A (in1[5]), .B (add_21_2_n_4), .Y (out1[5]));
  XNOR2X1 add_21_2_g83(.A (in1[3]), .B (add_21_2_n_1), .Y (out1[3]));
  XNOR2X1 add_21_2_g84(.A (in1[4]), .B (add_21_2_n_3), .Y (out1[4]));
  NAND2BX1 add_21_2_g85(.AN (add_21_2_n_3), .B (in1[4]), .Y
       (add_21_2_n_4));
  NAND3X1 add_21_2_g86(.A (in1[1]), .B (in1[3]), .C (in1[2]), .Y
       (add_21_2_n_3));
  XOR2XL add_21_2_g87(.A (in1[2]), .B (in1[1]), .Y (out1[2]));
  NAND2X1 add_21_2_g88(.A (in1[2]), .B (in1[1]), .Y (add_21_2_n_1));
endmodule


