`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:00:00 CST (May 25 2023 22:00:00 UTC)

module SobelFilter_N_Mux_32_4_53_4(in5, in4, in3, in2, ctrl1, out1);
  input [31:0] in5;
  input [8:0] in4, in3, in2;
  input [5:0] ctrl1;
  output [31:0] out1;
  wire [31:0] in5;
  wire [8:0] in4, in3, in2;
  wire [5:0] ctrl1;
  wire [31:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_57, n_67;
  OAI2BB1X1 g3047(.A0N (in5[6]), .A1N (n_67), .B0 (n_25), .Y (out1[6]));
  OAI2BB1X1 g3044(.A0N (in5[7]), .A1N (n_67), .B0 (n_29), .Y (out1[7]));
  OAI2BB1X1 g3054(.A0N (in5[8]), .A1N (n_67), .B0 (n_31), .Y (out1[8]));
  OAI2BB1X1 g3059(.A0N (in5[5]), .A1N (n_67), .B0 (n_30), .Y (out1[5]));
  OAI2BB1X1 g3046(.A0N (in5[2]), .A1N (n_67), .B0 (n_35), .Y (out1[2]));
  OAI2BB1X1 g3045(.A0N (in5[3]), .A1N (n_67), .B0 (n_34), .Y (out1[3]));
  OAI2BB1X1 g3050(.A0N (in5[4]), .A1N (n_67), .B0 (n_28), .Y (out1[4]));
  OAI2BB1X1 g3049(.A0N (in5[1]), .A1N (n_67), .B0 (n_27), .Y (out1[1]));
  OAI2BB1X1 g3048(.A0N (in5[0]), .A1N (n_67), .B0 (n_26), .Y (out1[0]));
  NOR2BX1 g3081(.AN (in5[26]), .B (n_57), .Y (out1[26]));
  NOR2BX1 g3063(.AN (in5[30]), .B (n_57), .Y (out1[30]));
  NOR2BX1 g3074(.AN (in5[29]), .B (n_57), .Y (out1[29]));
  NOR2BX1 g3071(.AN (in5[28]), .B (n_57), .Y (out1[28]));
  NOR2BX1 g3077(.AN (in5[27]), .B (n_57), .Y (out1[27]));
  NOR2BX1 g3067(.AN (in5[31]), .B (n_57), .Y (out1[31]));
  NOR2BX1 g3066(.AN (in5[25]), .B (n_57), .Y (out1[25]));
  NOR2BX1 g3061(.AN (in5[24]), .B (n_57), .Y (out1[24]));
  NOR2BX1 g3064(.AN (in5[23]), .B (n_57), .Y (out1[23]));
  NOR2BX1 g3065(.AN (in5[22]), .B (n_57), .Y (out1[22]));
  NOR2BX1 g3068(.AN (in5[21]), .B (n_57), .Y (out1[21]));
  NOR2BX1 g3076(.AN (in5[14]), .B (n_57), .Y (out1[14]));
  NOR2BX1 g3060(.AN (in5[20]), .B (n_57), .Y (out1[20]));
  NOR2BX1 g3070(.AN (in5[19]), .B (n_57), .Y (out1[19]));
  NOR2BX1 g3072(.AN (in5[17]), .B (n_57), .Y (out1[17]));
  NOR2BX1 g3073(.AN (in5[16]), .B (n_57), .Y (out1[16]));
  NOR2BX1 g3075(.AN (in5[15]), .B (n_57), .Y (out1[15]));
  NOR2BX1 g3080(.AN (in5[11]), .B (n_57), .Y (out1[11]));
  NOR2BX1 g3078(.AN (in5[13]), .B (n_57), .Y (out1[13]));
  NOR2BX1 g3079(.AN (in5[12]), .B (n_57), .Y (out1[12]));
  NOR2BX1 g3082(.AN (in5[10]), .B (n_57), .Y (out1[10]));
  NOR2BX1 g3062(.AN (in5[9]), .B (n_57), .Y (out1[9]));
  NOR2BX1 g3069(.AN (in5[18]), .B (n_57), .Y (out1[18]));
  AOI221X1 g3051(.A0 (in4[2]), .A1 (n_32), .B0 (in3[2]), .B1 (n_33),
       .C0 (n_17), .Y (n_35));
  AOI221X1 g3052(.A0 (in3[3]), .A1 (n_33), .B0 (in4[3]), .B1 (n_32),
       .C0 (n_24), .Y (n_34));
  AOI221X1 g3083(.A0 (in3[8]), .A1 (n_33), .B0 (in4[8]), .B1 (n_32),
       .C0 (n_23), .Y (n_31));
  AOI221X1 g3084(.A0 (in3[5]), .A1 (n_33), .B0 (in4[5]), .B1 (n_32),
       .C0 (n_12), .Y (n_30));
  AOI221X1 g3057(.A0 (in4[7]), .A1 (n_32), .B0 (in3[7]), .B1 (n_33),
       .C0 (n_16), .Y (n_29));
  AOI221X1 g3053(.A0 (in4[4]), .A1 (n_32), .B0 (in3[4]), .B1 (n_33),
       .C0 (n_18), .Y (n_28));
  AOI221X1 g3056(.A0 (in4[1]), .A1 (n_32), .B0 (in3[1]), .B1 (n_33),
       .C0 (n_14), .Y (n_27));
  AOI221X1 g3055(.A0 (in3[0]), .A1 (n_33), .B0 (in4[0]), .B1 (n_32),
       .C0 (n_15), .Y (n_26));
  AOI221X1 g3058(.A0 (in3[6]), .A1 (n_33), .B0 (in4[6]), .B1 (n_32),
       .C0 (n_13), .Y (n_25));
  NOR2X1 g3095(.A (n_11), .B (n_21), .Y (n_57));
  NAND4XL g3094(.A (n_20), .B (n_10), .C (n_7), .D (n_19), .Y (n_67));
  NOR2BX1 g3086(.AN (in2[3]), .B (n_22), .Y (n_24));
  NOR2BX1 g3085(.AN (in2[8]), .B (n_22), .Y (n_23));
  NAND2X1 g3096(.A (n_20), .B (n_19), .Y (n_21));
  NOR2BX1 g3087(.AN (in2[4]), .B (n_22), .Y (n_18));
  NOR2BX1 g3088(.AN (in2[2]), .B (n_22), .Y (n_17));
  NOR2BX1 g3091(.AN (in2[7]), .B (n_22), .Y (n_16));
  NOR2BX1 g3090(.AN (in2[0]), .B (n_22), .Y (n_15));
  NOR2BX1 g3089(.AN (in2[1]), .B (n_22), .Y (n_14));
  NOR2BX1 g3092(.AN (in2[6]), .B (n_22), .Y (n_13));
  NOR2BX1 g3093(.AN (in2[5]), .B (n_22), .Y (n_12));
  NAND3BXL g3097(.AN (n_8), .B (n_6), .C (n_10), .Y (n_11));
  OA22X1 g3099(.A0 (n_9), .A1 (n_2), .B0 (ctrl1[1]), .B1 (ctrl1[0]), .Y
       (n_19));
  NAND4X1 g3098(.A (n_0), .B (ctrl1[0]), .C (n_9), .D (n_3), .Y (n_22));
  NOR4X1 g3100(.A (n_9), .B (ctrl1[2]), .C (n_8), .D (n_1), .Y (n_32));
  NOR4X1 g3101(.A (n_4), .B (ctrl1[3]), .C (n_8), .D (n_5), .Y (n_33));
  NOR2BX1 g3102(.AN (n_6), .B (n_8), .Y (n_7));
  NAND2X1 g3103(.A (ctrl1[2]), .B (n_5), .Y (n_20));
  NAND3X1 g3104(.A (ctrl1[1]), .B (n_9), .C (n_4), .Y (n_10));
  INVXL g3105(.A (n_8), .Y (n_3));
  INVXL g3108(.A (n_1), .Y (n_2));
  NAND2BX1 g3106(.AN (ctrl1[0]), .B (ctrl1[1]), .Y (n_5));
  NAND2X1 g3107(.A (ctrl1[5]), .B (ctrl1[4]), .Y (n_8));
  NOR2X1 g3109(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_0));
  NAND2X1 g3111(.A (ctrl1[3]), .B (ctrl1[2]), .Y (n_6));
  NAND2X1 g3110(.A (ctrl1[1]), .B (ctrl1[0]), .Y (n_1));
  INVX1 g3113(.A (ctrl1[3]), .Y (n_9));
  INVX1 g3112(.A (ctrl1[2]), .Y (n_4));
endmodule


