`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 12:37:53 CST (May 26 2023 04:37:53 UTC)

module SobelFilter_Add2i30Add3i6u2Mul2i3u2_4(in2, in1, out1);
  input [1:0] in2, in1;
  output [5:0] out1;
  wire [1:0] in2, in1;
  wire [5:0] out1;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_9;
  wire n_10, n_11;
  assign out1[5] = 1'b1;
  XNOR2X1 g230(.A (in2[1]), .B (n_9), .Y (out1[3]));
  XNOR2X1 g229(.A (n_4), .B (n_11), .Y (out1[1]));
  NAND2BXL g231(.AN (n_10), .B (n_6), .Y (out1[2]));
  ADDHX1 g232(.A (in2[1]), .B (n_0), .CO (n_10), .S (n_11));
  NOR2XL g233(.A (n_5), .B (n_7), .Y (n_9));
  AND2XL g234(.A (in2[1]), .B (n_7), .Y (out1[4]));
  NAND3BXL g235(.AN (n_5), .B (n_3), .C (n_4), .Y (n_6));
  NOR2BX1 g236(.AN (n_3), .B (n_4), .Y (n_7));
  NAND2XL g237(.A (in2[1]), .B (n_2), .Y (n_3));
  NOR2X1 g238(.A (in2[1]), .B (n_2), .Y (n_5));
  OA21X1 g240(.A0 (in2[0]), .A1 (in1[0]), .B0 (n_4), .Y (out1[0]));
  OA21X1 g239(.A0 (in2[0]), .A1 (in1[1]), .B0 (n_2), .Y (n_0));
  NAND2X1 g241(.A (in2[0]), .B (in1[1]), .Y (n_2));
  NAND2X1 g242(.A (in2[0]), .B (in1[0]), .Y (n_4));
endmodule


