`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:00:05 CST (May 25 2023 22:00:05 UTC)

module SobelFilter_N_Mux_32_4_48_4(in5, in4, in3, in2, ctrl1, out1);
  input [31:0] in5;
  input [8:0] in4, in3, in2;
  input [5:0] ctrl1;
  output [31:0] out1;
  wire [31:0] in5;
  wire [8:0] in4, in3, in2;
  wire [5:0] ctrl1;
  wire [31:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_43, n_66;
  NOR2BX1 g3180(.AN (in5[16]), .B (n_66), .Y (out1[16]));
  NOR2BX1 g3159(.AN (in5[30]), .B (n_66), .Y (out1[30]));
  NOR2BX1 g3168(.AN (in5[29]), .B (n_66), .Y (out1[29]));
  NOR2BX1 g3165(.AN (in5[28]), .B (n_66), .Y (out1[28]));
  NOR2BX1 g3171(.AN (in5[27]), .B (n_66), .Y (out1[27]));
  NOR2BX1 g3175(.AN (in5[26]), .B (n_66), .Y (out1[26]));
  NOR2BX1 g3154(.AN (in5[25]), .B (n_66), .Y (out1[25]));
  NOR2BX1 g3155(.AN (in5[24]), .B (n_66), .Y (out1[24]));
  NOR2BX1 g3158(.AN (in5[23]), .B (n_66), .Y (out1[23]));
  NOR2BX1 g3160(.AN (in5[22]), .B (n_66), .Y (out1[22]));
  NOR2BX1 g3162(.AN (in5[21]), .B (n_66), .Y (out1[21]));
  NOR2BX1 g3161(.AN (in5[20]), .B (n_66), .Y (out1[20]));
  NOR2BX1 g3163(.AN (in5[19]), .B (n_66), .Y (out1[19]));
  NOR2BX1 g3164(.AN (in5[18]), .B (n_66), .Y (out1[18]));
  NOR2BX1 g3166(.AN (in5[17]), .B (n_66), .Y (out1[17]));
  NOR2BX1 g3157(.AN (in5[31]), .B (n_66), .Y (out1[31]));
  OAI2BB1X1 g3149(.A0N (in5[0]), .A1N (n_43), .B0 (n_33), .Y (out1[0]));
  NOR2BX1 g3170(.AN (in5[14]), .B (n_66), .Y (out1[14]));
  NOR2BX1 g3172(.AN (in5[13]), .B (n_66), .Y (out1[13]));
  NOR2BX1 g3173(.AN (in5[12]), .B (n_66), .Y (out1[12]));
  NOR2BX1 g3174(.AN (in5[11]), .B (n_66), .Y (out1[11]));
  NOR2BX1 g3176(.AN (in5[10]), .B (n_66), .Y (out1[10]));
  NOR2BX1 g3156(.AN (in5[9]), .B (n_66), .Y (out1[9]));
  OAI2BB1X1 g3140(.A0N (in5[8]), .A1N (n_43), .B0 (n_29), .Y (out1[8]));
  OAI2BB1X1 g3150(.A0N (in5[7]), .A1N (n_43), .B0 (n_30), .Y (out1[7]));
  OAI2BB1X1 g3143(.A0N (in5[6]), .A1N (n_43), .B0 (n_26), .Y (out1[6]));
  OAI2BB1X1 g3153(.A0N (in5[5]), .A1N (n_43), .B0 (n_28), .Y (out1[5]));
  OAI2BB1X1 g3144(.A0N (in5[4]), .A1N (n_43), .B0 (n_27), .Y (out1[4]));
  OAI2BB1X1 g3141(.A0N (in5[3]), .A1N (n_43), .B0 (n_34), .Y (out1[3]));
  OAI2BB1X1 g3142(.A0N (in5[2]), .A1N (n_43), .B0 (n_25), .Y (out1[2]));
  OAI2BB1X1 g3151(.A0N (in5[1]), .A1N (n_43), .B0 (n_24), .Y (out1[1]));
  NOR2BX1 g3169(.AN (in5[15]), .B (n_66), .Y (out1[15]));
  AOI221X1 g3146(.A0 (in3[3]), .A1 (n_32), .B0 (in4[3]), .B1 (n_31),
       .C0 (n_22), .Y (n_34));
  AOI221X1 g3178(.A0 (in3[0]), .A1 (n_32), .B0 (in4[0]), .B1 (n_31),
       .C0 (n_13), .Y (n_33));
  AOI221X1 g3179(.A0 (in3[7]), .A1 (n_32), .B0 (in4[7]), .B1 (n_31),
       .C0 (n_14), .Y (n_30));
  AOI221X1 g3145(.A0 (in3[8]), .A1 (n_32), .B0 (in4[8]), .B1 (n_31),
       .C0 (n_12), .Y (n_29));
  AND4X1 g3191(.A (n_19), .B (n_9), .C (n_5), .D (n_23), .Y (n_66));
  AOI221X1 g3167(.A0 (in3[5]), .A1 (n_32), .B0 (in4[5]), .B1 (n_31),
       .C0 (n_10), .Y (n_28));
  AOI221X1 g3147(.A0 (in3[4]), .A1 (n_32), .B0 (in4[4]), .B1 (n_31),
       .C0 (n_16), .Y (n_27));
  AOI221X1 g3152(.A0 (in3[6]), .A1 (n_32), .B0 (in4[6]), .B1 (n_31),
       .C0 (n_11), .Y (n_26));
  AOI221X1 g3148(.A0 (in3[2]), .A1 (n_32), .B0 (in4[2]), .B1 (n_31),
       .C0 (n_21), .Y (n_25));
  AOI221X1 g3177(.A0 (in3[1]), .A1 (n_32), .B0 (in4[1]), .B1 (n_31),
       .C0 (n_15), .Y (n_24));
  NAND4XL g3190(.A (n_18), .B (n_23), .C (n_6), .D (n_17), .Y (n_43));
  NOR2BX1 g3182(.AN (in2[3]), .B (n_20), .Y (n_22));
  NOR2BX1 g3181(.AN (in2[2]), .B (n_20), .Y (n_21));
  AND2XL g3192(.A (n_18), .B (n_17), .Y (n_19));
  NOR2BX1 g3183(.AN (in2[4]), .B (n_20), .Y (n_16));
  NOR2BX1 g3184(.AN (in2[1]), .B (n_20), .Y (n_15));
  NOR2BX1 g3187(.AN (in2[7]), .B (n_20), .Y (n_14));
  NOR2BX1 g3186(.AN (in2[0]), .B (n_20), .Y (n_13));
  NOR2BX1 g3185(.AN (in2[8]), .B (n_20), .Y (n_12));
  NOR2BX1 g3188(.AN (in2[6]), .B (n_20), .Y (n_11));
  NOR2BX1 g3189(.AN (in2[5]), .B (n_20), .Y (n_10));
  NAND4X1 g3193(.A (n_0), .B (ctrl1[0]), .C (n_8), .D (n_9), .Y (n_20));
  OA22X1 g3194(.A0 (n_8), .A1 (n_2), .B0 (ctrl1[1]), .B1 (ctrl1[0]), .Y
       (n_17));
  NOR4X1 g3195(.A (n_8), .B (ctrl1[2]), .C (n_1), .D (n_7), .Y (n_31));
  NOR4X1 g3196(.A (n_3), .B (ctrl1[3]), .C (n_7), .D (n_4), .Y (n_32));
  NOR2BX1 g3197(.AN (n_5), .B (n_7), .Y (n_6));
  NAND2XL g3198(.A (ctrl1[2]), .B (n_4), .Y (n_18));
  NAND3X1 g3199(.A (ctrl1[1]), .B (n_8), .C (n_3), .Y (n_23));
  INVX1 g3200(.A (n_7), .Y (n_9));
  INVXL g3203(.A (n_1), .Y (n_2));
  NAND2BX1 g3201(.AN (ctrl1[0]), .B (ctrl1[1]), .Y (n_4));
  NAND2BX1 g3202(.AN (ctrl1[4]), .B (ctrl1[5]), .Y (n_7));
  NOR2X1 g3204(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_0));
  NAND2X1 g3206(.A (ctrl1[3]), .B (ctrl1[2]), .Y (n_5));
  NAND2X1 g3205(.A (ctrl1[1]), .B (ctrl1[0]), .Y (n_1));
  INVX1 g3207(.A (ctrl1[3]), .Y (n_8));
  INVX1 g3208(.A (ctrl1[2]), .Y (n_3));
endmodule


