`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 12:37:26 CST (May 26 2023 04:37:26 UTC)

module SobelFilter_Add3i6u2Mul2i3u2_4(in2, in1, out1);
  input [1:0] in2, in1;
  output [4:0] out1;
  wire [1:0] in2, in1;
  wire [4:0] out1;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_9;
  wire n_11;
  OAI2BB1X1 g230(.A0N (in2[1]), .A1N (n_11), .B0 (n_6), .Y (out1[3]));
  NOR2X1 g231(.A (n_0), .B (n_11), .Y (out1[4]));
  XNOR2X1 g232(.A (n_7), .B (n_9), .Y (out1[2]));
  NAND2X1 g233(.A (n_5), .B (n_9), .Y (n_11));
  ADDFX1 g234(.A (n_3), .B (in2[1]), .CI (n_1), .CO (n_9), .S
       (out1[1]));
  NAND2X1 g235(.A (n_6), .B (n_5), .Y (n_7));
  NAND2X1 g236(.A (in2[1]), .B (n_4), .Y (n_5));
  OR2X1 g237(.A (in2[1]), .B (n_4), .Y (n_6));
  AO21X1 g239(.A0 (in2[0]), .A1 (in1[1]), .B0 (n_4), .Y (n_3));
  AOI2BB1X1 g238(.A0N (in2[0]), .A1N (in1[0]), .B0 (n_1), .Y (out1[0]));
  NOR2X1 g241(.A (in2[0]), .B (in1[1]), .Y (n_4));
  AND2XL g240(.A (in2[0]), .B (in1[0]), .Y (n_1));
  INVX1 g242(.A (in2[1]), .Y (n_0));
endmodule


