`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:09:23 CST (May 25 2023 22:09:23 UTC)

module SobelFilter_Equal_5Ux4U_1U_1(in2, in1, out1);
  input [4:0] in2;
  input [3:0] in1;
  output out1;
  wire [4:0] in2;
  wire [3:0] in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19;
  NOR2BX1 g58(.AN (n_13), .B (n_19), .Y (out1));
  NAND2X1 g59(.A (n_17), .B (n_18), .Y (n_19));
  NOR2X2 g61(.A (n_16), .B (n_14), .Y (n_18));
  NOR2X2 g60(.A (in2[4]), .B (n_15), .Y (n_17));
  NOR2X2 g63(.A (n_7), .B (n_10), .Y (n_16));
  NOR2X2 g64(.A (n_9), .B (n_11), .Y (n_15));
  NOR2X1 g65(.A (n_8), .B (n_12), .Y (n_14));
  MXI2XL g62(.A (in1[3]), .B (n_3), .S0 (in2[3]), .Y (n_13));
  NOR2X2 g68(.A (n_6), .B (n_2), .Y (n_12));
  NOR2X4 g69(.A (n_4), .B (n_0), .Y (n_11));
  NOR2X6 g66(.A (n_5), .B (n_1), .Y (n_10));
  NOR2X2 g71(.A (in2[0]), .B (in1[0]), .Y (n_9));
  NOR2X2 g70(.A (in2[1]), .B (in1[1]), .Y (n_8));
  NOR2X2 g67(.A (in2[2]), .B (in1[2]), .Y (n_7));
  CLKINVX16 g73(.A (in2[1]), .Y (n_6));
  CLKINVX12 g72(.A (in2[2]), .Y (n_5));
  CLKINVX12 g76(.A (in2[0]), .Y (n_4));
  INVX1 g75(.A (in1[3]), .Y (n_3));
  CLKINVX2 g78(.A (in1[1]), .Y (n_2));
  CLKINVX4 g74(.A (in1[2]), .Y (n_1));
  CLKINVX4 g77(.A (in1[0]), .Y (n_0));
endmodule


