`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 07:01:57 CST (May 25 2023 23:01:57 UTC)

module SobelFilter_Add_6Sx5U_7S_4(in2, in1, out1);
  input [5:0] in2;
  input [4:0] in1;
  output [6:0] out1;
  wire [5:0] in2;
  wire [4:0] in1;
  wire [6:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_9, add_23_2_n_12, add_23_2_n_13,
       add_23_2_n_14, add_23_2_n_16, add_23_2_n_17, add_23_2_n_21;
  XOR2XL add_23_2_g110(.A (in2[5]), .B (add_23_2_n_21), .Y (out1[5]));
  NAND2XL add_23_2_g111(.A (add_23_2_n_3), .B (add_23_2_n_17), .Y
       (add_23_2_n_21));
  AND3XL add_23_2_g112(.A (add_23_2_n_17), .B (in2[5]), .C
       (add_23_2_n_3), .Y (out1[6]));
  XNOR2X1 add_23_2_g113(.A (add_23_2_n_8), .B (add_23_2_n_14), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g114(.A (add_23_2_n_7), .B (add_23_2_n_16), .Y
       (out1[3]));
  NAND2BX1 add_23_2_g115(.AN (add_23_2_n_4), .B (add_23_2_n_14), .Y
       (add_23_2_n_17));
  OAI2BB1X1 add_23_2_g116(.A0N (add_23_2_n_2), .A1N (add_23_2_n_12),
       .B0 (add_23_2_n_0), .Y (add_23_2_n_16));
  XNOR2X1 add_23_2_g117(.A (add_23_2_n_6), .B (add_23_2_n_12), .Y
       (out1[2]));
  OAI211X1 add_23_2_g118(.A0 (add_23_2_n_0), .A1 (add_23_2_n_1), .B0
       (add_23_2_n_13), .C0 (add_23_2_n_5), .Y (add_23_2_n_14));
  NAND3BXL add_23_2_g119(.AN (add_23_2_n_1), .B (add_23_2_n_12), .C
       (add_23_2_n_2), .Y (add_23_2_n_13));
  ADDFX1 add_23_2_g120(.A (add_23_2_n_9), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_12), .S (out1[1]));
  ADDHX1 add_23_2_g121(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_9), .S
       (out1[0]));
  NAND2BX1 add_23_2_g122(.AN (add_23_2_n_4), .B (add_23_2_n_3), .Y
       (add_23_2_n_8));
  NAND2BX1 add_23_2_g123(.AN (add_23_2_n_1), .B (add_23_2_n_5), .Y
       (add_23_2_n_7));
  NAND2X1 add_23_2_g124(.A (add_23_2_n_0), .B (add_23_2_n_2), .Y
       (add_23_2_n_6));
  NAND2X1 add_23_2_g125(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_5));
  NOR2X1 add_23_2_g126(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_4));
  NAND2X1 add_23_2_g127(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_3));
  OR2XL add_23_2_g128(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_2));
  NOR2X1 add_23_2_g129(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_1));
  NAND2X1 add_23_2_g130(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_0));
endmodule


