`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:08:18 CST (May 25 2023 22:08:18 UTC)

module SobelFilter_N_Mux_32_4_54_1(in5, in4, in3, in2, ctrl1, out1);
  input [31:0] in5;
  input [8:0] in4, in3, in2;
  input [5:0] ctrl1;
  output [31:0] out1;
  wire [31:0] in5;
  wire [8:0] in4, in3, in2;
  wire [5:0] ctrl1;
  wire [31:0] out1;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_93, n_94, n_95, n_96, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_206, n_210, n_212, n_216, n_218;
  wire n_233, n_234, n_235;
  OAI2BB1X1 g4508(.A0N (in5[6]), .A1N (n_89), .B0 (n_123), .Y
       (out1[6]));
  OAI2BB1X1 g4509(.A0N (in5[7]), .A1N (n_96), .B0 (n_121), .Y
       (out1[7]));
  OAI2BB1X1 g4510(.A0N (in5[8]), .A1N (n_95), .B0 (n_124), .Y
       (out1[8]));
  OAI2BB1X1 g4511(.A0N (in5[5]), .A1N (n_86), .B0 (n_125), .Y
       (out1[5]));
  OAI2BB1X1 g4512(.A0N (in5[2]), .A1N (n_85), .B0 (n_130), .Y
       (out1[2]));
  OAI2BB1X1 g4513(.A0N (in5[3]), .A1N (n_87), .B0 (n_129), .Y
       (out1[3]));
  OAI2BB1X1 g4514(.A0N (in5[4]), .A1N (n_90), .B0 (n_120), .Y
       (out1[4]));
  OAI2BB1X1 g4515(.A0N (in5[1]), .A1N (n_91), .B0 (n_131), .Y
       (out1[1]));
  OAI2BB1X1 g4516(.A0N (in5[0]), .A1N (n_88), .B0 (n_127), .Y
       (out1[0]));
  AOI221X1 g4533(.A0 (in2[1]), .A1 (n_128), .B0 (in4[1]), .B1 (n_122),
       .C0 (n_68), .Y (n_131));
  NOR3X1 g4547(.A (n_61), .B (n_62), .C (n_65), .Y (n_130));
  AOI221X1 g4546(.A0 (in2[3]), .A1 (n_128), .B0 (in3[3]), .B1 (n_126),
       .C0 (n_66), .Y (n_129));
  AOI221X1 g4540(.A0 (in2[0]), .A1 (n_128), .B0 (in3[0]), .B1 (n_126),
       .C0 (n_79), .Y (n_127));
  NOR3X1 g4544(.A (n_58), .B (n_69), .C (n_84), .Y (n_125));
  AOI221X1 g4541(.A0 (in2[8]), .A1 (n_128), .B0 (in3[8]), .B1 (n_126),
       .C0 (n_78), .Y (n_124));
  AOI221X1 g4543(.A0 (in2[6]), .A1 (n_128), .B0 (in4[6]), .B1 (n_122),
       .C0 (n_75), .Y (n_123));
  AOI221X1 g4542(.A0 (in2[7]), .A1 (n_128), .B0 (in4[7]), .B1 (n_122),
       .C0 (n_76), .Y (n_121));
  AOI221X1 g4545(.A0 (in2[4]), .A1 (n_128), .B0 (in4[4]), .B1 (n_122),
       .C0 (n_63), .Y (n_120));
  NOR2BX1 g4522(.AN (in5[27]), .B (n_46), .Y (out1[27]));
  NOR2BX1 g4527(.AN (in5[31]), .B (n_50), .Y (out1[31]));
  NOR2BX1 g4531(.AN (in5[30]), .B (n_57), .Y (out1[30]));
  NOR2BX1 g4535(.AN (in5[29]), .B (n_80), .Y (out1[29]));
  NOR2BX1 g4532(.AN (in5[28]), .B (n_56), .Y (out1[28]));
  NOR2BX1 g4525(.AN (in5[26]), .B (n_53), .Y (out1[26]));
  NOR2BX1 g4517(.AN (in5[24]), .B (n_71), .Y (out1[24]));
  NOR2BX1 g4537(.AN (in5[23]), .B (n_60), .Y (out1[23]));
  NOR2BX1 g4518(.AN (in5[22]), .B (n_55), .Y (out1[22]));
  NOR2BX1 g4519(.AN (in5[21]), .B (n_48), .Y (out1[21]));
  NOR2BX1 g4521(.AN (in5[20]), .B (n_47), .Y (out1[20]));
  NOR2BX1 g4538(.AN (in5[11]), .B (n_83), .Y (out1[11]));
  NOR2BX1 g4526(.AN (in5[17]), .B (n_45), .Y (out1[17]));
  NOR2BX1 g4528(.AN (in5[16]), .B (n_67), .Y (out1[16]));
  NOR2BX1 g4530(.AN (in5[15]), .B (n_44), .Y (out1[15]));
  NOR2BX1 g4534(.AN (in5[13]), .B (n_52), .Y (out1[13]));
  NOR2BX1 g4536(.AN (in5[12]), .B (n_51), .Y (out1[12]));
  NOR2BX1 g4523(.AN (in5[19]), .B (n_73), .Y (out1[19]));
  NOR2BX1 g4539(.AN (in5[10]), .B (n_54), .Y (out1[10]));
  NOR2BX1 g4529(.AN (in5[25]), .B (n_43), .Y (out1[25]));
  NOR2BX1 g4520(.AN (in5[9]), .B (n_49), .Y (out1[9]));
  NOR2BX1 g4548(.AN (in5[14]), .B (n_42), .Y (out1[14]));
  NOR2BX1 g4524(.AN (in5[18]), .B (n_82), .Y (out1[18]));
  NAND3X1 g4550(.A (n_94), .B (n_93), .C (n_206), .Y (n_96));
  NAND3X1 g4564(.A (n_94), .B (n_93), .C (n_206), .Y (n_95));
  NAND3X1 g4557(.A (n_206), .B (n_94), .C (n_93), .Y (n_91));
  NAND3X1 g4551(.A (n_94), .B (n_93), .C (n_206), .Y (n_90));
  NAND3X1 g4554(.A (n_206), .B (n_94), .C (n_93), .Y (n_89));
  NAND3X1 g4553(.A (n_206), .B (n_94), .C (n_93), .Y (n_88));
  NAND3X1 g4552(.A (n_94), .B (n_93), .C (n_206), .Y (n_87));
  NAND3X1 g4555(.A (n_206), .B (n_94), .C (n_93), .Y (n_86));
  NAND3X1 g4556(.A (n_206), .B (n_94), .C (n_93), .Y (n_85));
  NOR2BX1 g4585(.AN (in2[5]), .B (n_64), .Y (n_84));
  NOR3BX1 g4579(.AN (n_70), .B (n_18), .C (n_212), .Y (n_83));
  NOR3XL g4580(.A (n_31), .B (n_59), .C (n_210), .Y (n_82));
  NOR3BX1 g4558(.AN (n_72), .B (n_36), .C (n_218), .Y (n_80));
  NOR2BX1 g4581(.AN (in4[0]), .B (n_77), .Y (n_79));
  NOR2BX1 g4582(.AN (in4[8]), .B (n_77), .Y (n_78));
  NOR2BX1 g4583(.AN (in3[7]), .B (n_74), .Y (n_76));
  NOR2BX1 g4584(.AN (in3[6]), .B (n_74), .Y (n_75));
  NOR3BX1 g4559(.AN (n_72), .B (n_37), .C (n_218), .Y (n_73));
  NOR3BX1 g4578(.AN (n_70), .B (n_22), .C (n_212), .Y (n_71));
  NOR2BX1 g4586(.AN (in4[5]), .B (n_77), .Y (n_69));
  NOR2BX1 g4587(.AN (in3[1]), .B (n_74), .Y (n_68));
  NOR3BX1 g4560(.AN (n_72), .B (n_35), .C (n_212), .Y (n_67));
  NOR2BX1 g4589(.AN (in4[3]), .B (n_77), .Y (n_66));
  NOR2BX1 g4590(.AN (in2[2]), .B (n_64), .Y (n_65));
  NOR2BX1 g4588(.AN (in3[4]), .B (n_74), .Y (n_63));
  NOR2BX1 g4591(.AN (in4[2]), .B (n_77), .Y (n_62));
  NOR2BX1 g4592(.AN (in3[2]), .B (n_74), .Y (n_61));
  NOR3XL g4569(.A (n_33), .B (n_59), .C (n_210), .Y (n_60));
  NOR2BX1 g4593(.AN (in3[5]), .B (n_74), .Y (n_58));
  NOR3BX1 g4562(.AN (n_72), .B (n_34), .C (n_218), .Y (n_57));
  NOR3XL g4549(.A (n_16), .B (n_59), .C (n_216), .Y (n_56));
  NOR3XL g4563(.A (n_32), .B (n_59), .C (n_216), .Y (n_55));
  NOR3BX1 g4565(.AN (n_70), .B (n_25), .C (n_218), .Y (n_54));
  NOR3XL g4566(.A (n_29), .B (n_59), .C (n_216), .Y (n_53));
  NOR3XL g4567(.A (n_28), .B (n_59), .C (n_216), .Y (n_52));
  NOR3XL g4568(.A (n_30), .B (n_59), .C (n_210), .Y (n_51));
  NOR3BX1 g4561(.AN (n_72), .B (n_39), .C (n_218), .Y (n_50));
  NOR3BX1 g4570(.AN (n_70), .B (n_17), .C (n_218), .Y (n_49));
  NOR3BX1 g4571(.AN (n_70), .B (n_24), .C (n_212), .Y (n_48));
  NOR3BX1 g4572(.AN (n_70), .B (n_23), .C (n_212), .Y (n_47));
  NOR3BX1 g4573(.AN (n_70), .B (n_21), .C (n_212), .Y (n_46));
  NOR3BX1 g4574(.AN (n_70), .B (n_20), .C (n_218), .Y (n_45));
  NOR3BX1 g4575(.AN (n_70), .B (n_40), .C (n_218), .Y (n_44));
  NOR3BX1 g4576(.AN (n_70), .B (n_15), .C (n_212), .Y (n_43));
  NOR3BX1 g4577(.AN (n_70), .B (n_19), .C (n_212), .Y (n_42));
  CLKINVX3 g4594(.A (n_74), .Y (n_126));
  CLKINVX3 g4598(.A (n_77), .Y (n_122));
  NAND2X4 g4596(.A (n_2), .B (n_41), .Y (n_74));
  INVX1 g4599(.A (n_128), .Y (n_64));
  NAND2X4 g4600(.A (n_5), .B (n_27), .Y (n_77));
  OAI21X4 g4597(.A0 (n_234), .A1 (n_11), .B0 (n_9), .Y (n_81));
  CLKAND2X2 g4601(.A (n_14), .B (n_8), .Y (n_128));
  NOR3X2 g4627(.A (ctrl1[0]), .B (ctrl1[5]), .C (n_26), .Y (n_41));
  NAND2XL g4602(.A (n_72), .B (n_38), .Y (n_40));
  NAND2XL g4603(.A (n_70), .B (n_38), .Y (n_39));
  NAND2XL g4604(.A (n_70), .B (n_38), .Y (n_37));
  NAND2XL g4605(.A (n_70), .B (n_38), .Y (n_36));
  NAND2XL g4606(.A (n_70), .B (n_38), .Y (n_35));
  NAND2XL g4607(.A (n_70), .B (n_38), .Y (n_34));
  NAND2X1 g4609(.A (n_72), .B (n_70), .Y (n_33));
  NAND2X1 g4610(.A (n_72), .B (n_70), .Y (n_32));
  NAND2X1 g4611(.A (n_72), .B (n_70), .Y (n_31));
  NAND2X1 g4612(.A (n_72), .B (n_70), .Y (n_30));
  NAND2X1 g4613(.A (n_72), .B (n_70), .Y (n_29));
  NAND2X1 g4614(.A (n_72), .B (n_70), .Y (n_28));
  NOR3X2 g4616(.A (n_10), .B (ctrl1[5]), .C (n_26), .Y (n_27));
  NAND2XL g4617(.A (n_72), .B (n_38), .Y (n_25));
  NAND2XL g4618(.A (n_72), .B (n_38), .Y (n_24));
  NAND2XL g4619(.A (n_72), .B (n_38), .Y (n_23));
  NAND2XL g4620(.A (n_72), .B (n_38), .Y (n_22));
  NAND2XL g4622(.A (n_72), .B (n_38), .Y (n_21));
  NAND2XL g4623(.A (n_72), .B (n_38), .Y (n_20));
  NAND2XL g4624(.A (n_72), .B (n_38), .Y (n_19));
  NAND2XL g4625(.A (n_72), .B (n_38), .Y (n_18));
  NAND2XL g4626(.A (n_72), .B (n_38), .Y (n_17));
  NAND2X1 g4608(.A (n_72), .B (n_70), .Y (n_16));
  NAND2XL g4621(.A (n_72), .B (n_38), .Y (n_15));
  CLKAND2X2 g4629(.A (n_4), .B (n_72), .Y (n_93));
  CLKAND2X2 g4615(.A (n_7), .B (n_70), .Y (n_94));
  NOR3X2 g4628(.A (ctrl1[2]), .B (ctrl1[5]), .C (n_12), .Y (n_14));
  INVX1 g4630(.A (n_38), .Y (n_59));
  AOI21X2 g4631(.A0 (ctrl1[2]), .A1 (n_13), .B0 (n_6), .Y (n_38));
  NAND2X4 g4632(.A (n_13), .B (n_12), .Y (n_72));
  AOI21X4 g4633(.A0 (ctrl1[2]), .A1 (n_10), .B0 (ctrl1[1]), .Y (n_11));
  NAND2X2 g4634(.A (ctrl1[0]), .B (n_1), .Y (n_9));
  NOR2X1 g4642(.A (n_235), .B (ctrl1[4]), .Y (n_8));
  INVXL g4636(.A (n_6), .Y (n_7));
  NOR2X1 g4641(.A (n_0), .B (ctrl1[1]), .Y (n_5));
  NAND2X1 g4643(.A (ctrl1[2]), .B (n_13), .Y (n_4));
  NAND2X8 g4644(.A (ctrl1[4]), .B (n_233), .Y (n_26));
  AOI21X4 g4635(.A0 (ctrl1[4]), .A1 (ctrl1[3]), .B0 (ctrl1[5]), .Y
       (n_70));
  NOR2X1 g4638(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_2));
  NOR2X1 g4640(.A (ctrl1[4]), .B (ctrl1[3]), .Y (n_6));
  NOR2X4 g4637(.A (ctrl1[3]), .B (ctrl1[2]), .Y (n_1));
  NAND2X4 g4639(.A (ctrl1[1]), .B (ctrl1[0]), .Y (n_12));
  INVX1 g4648(.A (ctrl1[2]), .Y (n_0));
  CLKINVX12 g4645(.A (ctrl1[0]), .Y (n_10));
  INVX2 g4647(.A (ctrl1[4]), .Y (n_13));
  CLKINVX2 fopt(.A (n_206), .Y (n_210));
  CLKINVX3 fopt4649(.A (n_206), .Y (n_212));
  CLKINVX3 fopt4650(.A (n_206), .Y (n_216));
  CLKINVX3 fopt4651(.A (n_206), .Y (n_218));
  CLKINVX8 fopt4652(.A (n_81), .Y (n_206));
  CLKINVX8 fopt4659(.A (ctrl1[3]), .Y (n_233));
  CLKINVX2 fopt4660(.A (n_235), .Y (n_234));
  CLKINVX2 fopt4661(.A (ctrl1[3]), .Y (n_235));
endmodule


