`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 12:37:06 CST (May 26 2023 04:37:06 UTC)

module SobelFilter_Add_5U_15_4(in1, out1);
  input [4:0] in1;
  output [4:0] out1;
  wire [4:0] in1;
  wire [4:0] out1;
  wire add_21_2_n_1, add_21_2_n_2, add_21_2_n_3;
  INVX1 g2(.A (in1[0]), .Y (out1[0]));
  XNOR2X1 add_21_2_g68(.A (in1[3]), .B (add_21_2_n_3), .Y (out1[3]));
  XNOR2X1 add_21_2_g69(.A (in1[4]), .B (add_21_2_n_2), .Y (out1[4]));
  XNOR2X1 add_21_2_g70(.A (in1[2]), .B (add_21_2_n_1), .Y (out1[2]));
  NAND2BX1 add_21_2_g71(.AN (add_21_2_n_1), .B (in1[2]), .Y
       (add_21_2_n_3));
  NAND3BXL add_21_2_g72(.AN (add_21_2_n_1), .B (in1[3]), .C (in1[2]),
       .Y (add_21_2_n_2));
  NOR2X1 add_21_2_g75(.A (in1[1]), .B (in1[0]), .Y (add_21_2_n_1));
  AO21XL add_21_2_g2(.A0 (in1[1]), .A1 (in1[0]), .B0 (add_21_2_n_1), .Y
       (out1[1]));
endmodule


