`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 05:59:12 CST (May 25 2023 21:59:12 UTC)

module SobelFilter_N_Mux_32_3_91_4(in4, in3, in2, ctrl1, out1);
  input [31:0] in4;
  input [8:0] in3, in2;
  input [5:0] ctrl1;
  output [31:0] out1;
  wire [31:0] in4;
  wire [8:0] in3, in2;
  wire [5:0] ctrl1;
  wire [31:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_26, n_27, n_28, n_38, n_40, n_41, n_43;
  wire n_49, n_50, n_51, n_52, n_57, n_67;
  OAI2BB1X1 g3140(.A0N (in4[6]), .A1N (n_67), .B0 (n_28), .Y (out1[6]));
  OAI2BB1X1 g3137(.A0N (in4[7]), .A1N (n_67), .B0 (n_26), .Y (out1[7]));
  OAI2BB1X1 g3136(.A0N (in4[8]), .A1N (n_67), .B0 (n_51), .Y (out1[8]));
  OAI2BB1X1 g3139(.A0N (in4[5]), .A1N (n_67), .B0 (n_27), .Y (out1[5]));
  OAI2BB1X1 g3145(.A0N (in4[2]), .A1N (n_67), .B0 (n_43), .Y (out1[2]));
  OAI2BB1X1 g3144(.A0N (in4[3]), .A1N (n_67), .B0 (n_41), .Y (out1[3]));
  OAI2BB1X1 g3142(.A0N (in4[4]), .A1N (n_67), .B0 (n_40), .Y (out1[4]));
  OAI2BB1X1 g3138(.A0N (in4[1]), .A1N (n_67), .B0 (n_52), .Y (out1[1]));
  OAI2BB1X1 g3141(.A0N (in4[0]), .A1N (n_67), .B0 (n_38), .Y (out1[0]));
  AND2XL g3160(.A (in4[22]), .B (n_57), .Y (out1[22]));
  AND2XL g3154(.A (in4[31]), .B (n_57), .Y (out1[31]));
  AND2XL g3166(.A (in4[30]), .B (n_57), .Y (out1[30]));
  AND2XL g3163(.A (in4[29]), .B (n_57), .Y (out1[29]));
  AND2XL g3169(.A (in4[28]), .B (n_57), .Y (out1[28]));
  AND2XL g3173(.A (in4[12]), .B (n_57), .Y (out1[12]));
  AOI221X1 g3143(.A0 (in4[1]), .A1 (n_50), .B0 (in2[1]), .B1 (n_49),
       .C0 (n_20), .Y (n_52));
  AOI221X1 g3146(.A0 (in4[8]), .A1 (n_50), .B0 (in2[8]), .B1 (n_49),
       .C0 (n_17), .Y (n_51));
  AND2XL g3172(.A (in4[27]), .B (n_57), .Y (out1[27]));
  AND2XL g3167(.A (in4[16]), .B (n_57), .Y (out1[16]));
  AND2XL g3156(.A (in4[26]), .B (n_57), .Y (out1[26]));
  AND2XL g3158(.A (in4[25]), .B (n_57), .Y (out1[25]));
  AND2XL g3152(.A (in4[24]), .B (n_57), .Y (out1[24]));
  AOI221X1 g3176(.A0 (in4[2]), .A1 (n_50), .B0 (in2[2]), .B1 (n_49),
       .C0 (n_24), .Y (n_43));
  AND2XL g3157(.A (in4[23]), .B (n_57), .Y (out1[23]));
  AOI221X1 g3175(.A0 (in4[3]), .A1 (n_50), .B0 (in2[3]), .B1 (n_49),
       .C0 (n_23), .Y (n_41));
  AOI221X1 g3151(.A0 (in4[4]), .A1 (n_50), .B0 (in2[4]), .B1 (n_49),
       .C0 (n_21), .Y (n_40));
  AND2XL g3162(.A (in4[20]), .B (n_57), .Y (out1[20]));
  AOI221X1 g3149(.A0 (in4[0]), .A1 (n_50), .B0 (in2[0]), .B1 (n_49),
       .C0 (n_18), .Y (n_38));
  AND2XL g3161(.A (in4[19]), .B (n_57), .Y (out1[19]));
  AND2XL g3164(.A (in4[18]), .B (n_57), .Y (out1[18]));
  AND2XL g3165(.A (in4[17]), .B (n_57), .Y (out1[17]));
  AND2XL g3168(.A (in4[15]), .B (n_57), .Y (out1[15]));
  AND2XL g3170(.A (in4[14]), .B (n_57), .Y (out1[14]));
  AND2XL g3171(.A (in4[13]), .B (n_57), .Y (out1[13]));
  AND2XL g3174(.A (in4[11]), .B (n_57), .Y (out1[11]));
  AND2XL g3155(.A (in4[10]), .B (n_57), .Y (out1[10]));
  AND2XL g3153(.A (in4[9]), .B (n_57), .Y (out1[9]));
  AOI221X1 g3147(.A0 (in4[6]), .A1 (n_50), .B0 (in2[6]), .B1 (n_49),
       .C0 (n_16), .Y (n_28));
  AOI221X1 g3150(.A0 (in4[5]), .A1 (n_50), .B0 (in2[5]), .B1 (n_49),
       .C0 (n_15), .Y (n_27));
  AOI221X1 g3148(.A0 (in4[7]), .A1 (n_50), .B0 (in2[7]), .B1 (n_49),
       .C0 (n_19), .Y (n_26));
  AND2XL g3159(.A (in4[21]), .B (n_57), .Y (out1[21]));
  NAND3X1 g3178(.A (n_14), .B (n_13), .C (n_11), .Y (n_57));
  NOR2BX1 g3181(.AN (in3[2]), .B (n_22), .Y (n_24));
  NOR2BX1 g3180(.AN (in3[3]), .B (n_22), .Y (n_23));
  NOR2BX1 g3179(.AN (in3[4]), .B (n_22), .Y (n_21));
  NOR2BX1 g3182(.AN (in3[1]), .B (n_22), .Y (n_20));
  NOR2BX1 g3185(.AN (in3[7]), .B (n_22), .Y (n_19));
  NOR2BX1 g3184(.AN (in3[0]), .B (n_22), .Y (n_18));
  NOR2BX1 g3183(.AN (in3[8]), .B (n_22), .Y (n_17));
  NOR2BX1 g3186(.AN (in3[6]), .B (n_22), .Y (n_16));
  NOR2BX1 g3187(.AN (in3[5]), .B (n_22), .Y (n_15));
  NOR4X1 g3189(.A (n_10), .B (n_2), .C (n_0), .D (n_50), .Y (n_14));
  NAND3BXL g3177(.AN (n_12), .B (n_9), .C (n_13), .Y (n_67));
  NOR4X1 g3190(.A (ctrl1[4]), .B (ctrl1[1]), .C (ctrl1[0]), .D (n_7),
       .Y (n_49));
  NAND3BX1 g3191(.AN (ctrl1[1]), .B (n_6), .C (ctrl1[0]), .Y (n_22));
  NAND4XL g3188(.A (n_11), .B (n_1), .C (n_8), .D (n_3), .Y (n_12));
  NAND2X1 g3194(.A (n_9), .B (n_8), .Y (n_10));
  OR2XL g3192(.A (ctrl1[5]), .B (n_4), .Y (n_7));
  NOR4X1 g3195(.A (n_5), .B (ctrl1[5]), .C (ctrl1[3]), .D (ctrl1[2]),
       .Y (n_6));
  NAND2X1 g3193(.A (n_5), .B (n_4), .Y (n_13));
  NAND2X1 g3202(.A (ctrl1[0]), .B (n_5), .Y (n_8));
  AOI21X1 g3196(.A0 (ctrl1[4]), .A1 (ctrl1[3]), .B0 (ctrl1[5]), .Y
       (n_11));
  INVXL g3197(.A (n_2), .Y (n_3));
  INVXL g3198(.A (n_0), .Y (n_1));
  NAND2X1 g3203(.A (ctrl1[1]), .B (n_5), .Y (n_9));
  NAND2X1 g3199(.A (ctrl1[3]), .B (ctrl1[2]), .Y (n_4));
  NOR2BX1 g3200(.AN (ctrl1[2]), .B (ctrl1[3]), .Y (n_2));
  NOR2BX1 g3201(.AN (ctrl1[1]), .B (ctrl1[3]), .Y (n_0));
  NOR2X1 g3204(.A (ctrl1[3]), .B (ctrl1[0]), .Y (n_50));
  INVX1 g3205(.A (ctrl1[4]), .Y (n_5));
endmodule


