`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:06:08 CST (May 25 2023 22:06:08 UTC)

module SobelFilter_N_Mux_30_6_0_4(ctrl1, out1);
  input [3:0] ctrl1;
  output [29:0] out1;
  wire [3:0] ctrl1;
  wire [29:0] out1;
  wire n_0, n_1;
  assign out1[0] = out1[19];
  assign out1[1] = out1[19];
  assign out1[2] = 1'b0;
  assign out1[3] = out1[22];
  assign out1[4] = out1[15];
  assign out1[5] = out1[22];
  assign out1[6] = 1'b0;
  assign out1[7] = out1[15];
  assign out1[8] = out1[19];
  assign out1[9] = out1[19];
  assign out1[10] = out1[22];
  assign out1[11] = out1[22];
  assign out1[12] = out1[22];
  assign out1[13] = out1[22];
  assign out1[14] = out1[22];
  assign out1[16] = out1[22];
  assign out1[17] = 1'b0;
  assign out1[18] = 1'b0;
  assign out1[21] = out1[28];
  assign out1[23] = out1[29];
  assign out1[24] = 1'b1;
  assign out1[25] = out1[29];
  assign out1[26] = 1'b1;
  assign out1[27] = 1'b1;
  INVX1 g17(.A (out1[15]), .Y (out1[20]));
  NOR2X1 g18(.A (out1[22]), .B (out1[29]), .Y (out1[15]));
  INVX1 g19(.A (out1[22]), .Y (out1[28]));
  INVX1 g21(.A (out1[19]), .Y (out1[29]));
  OAI21X1 g20(.A0 (ctrl1[0]), .A1 (n_0), .B0 (n_1), .Y (out1[22]));
  NAND3BX1 g22(.AN (ctrl1[0]), .B (n_1), .C (n_0), .Y (out1[19]));
  NOR2BX1 g23(.AN (ctrl1[2]), .B (ctrl1[1]), .Y (n_0));
  INVX1 g24(.A (ctrl1[3]), .Y (n_1));
endmodule


