`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 12:38:09 CST (May 26 2023 04:38:09 UTC)

module SobelFilter_Add_5U_29_1(in1, out1);
  input [4:0] in1;
  output [4:0] out1;
  wire [4:0] in1;
  wire [4:0] out1;
  wire add_21_2_n_2, add_21_2_n_3, add_21_2_n_4, add_21_2_n_5,
       add_21_2_n_7;
  assign out1[0] = in1[0];
  INVX1 g2(.A (in1[1]), .Y (out1[1]));
  MXI2XL add_21_2_g62(.A (in1[3]), .B (add_21_2_n_3), .S0
       (add_21_2_n_4), .Y (out1[3]));
  NOR2BX2 add_21_2_g64(.AN (in1[1]), .B (add_21_2_n_5), .Y
       (add_21_2_n_7));
  MXI2XL add_21_2_g65(.A (add_21_2_n_2), .B (in1[2]), .S0 (in1[1]), .Y
       (out1[2]));
  NAND2X4 add_21_2_g66(.A (in1[3]), .B (in1[2]), .Y (add_21_2_n_5));
  NAND2X1 add_21_2_g67(.A (in1[2]), .B (in1[1]), .Y (add_21_2_n_4));
  INVX1 add_21_2_g68(.A (in1[3]), .Y (add_21_2_n_3));
  INVX1 add_21_2_g70(.A (in1[2]), .Y (add_21_2_n_2));
  XNOR2XL add_21_2_g2(.A (in1[4]), .B (add_21_2_n_7), .Y (out1[4]));
endmodule


