`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:09:46 CST (May 25 2023 22:09:46 UTC)

module SobelFilter_Add_24Ux10U_25S_1(in2, in1, out1);
  input [23:0] in2;
  input [9:0] in1;
  output [24:0] out1;
  wire [23:0] in2;
  wire [9:0] in1;
  wire [24:0] out1;
  wire add_23_2_n_6, add_23_2_n_7, add_23_2_n_8, add_23_2_n_9,
       add_23_2_n_17, add_23_2_n_19, add_23_2_n_20, add_23_2_n_21;
  wire add_23_2_n_22, add_23_2_n_23, add_23_2_n_24, add_23_2_n_25,
       add_23_2_n_26, add_23_2_n_27, add_23_2_n_28, add_23_2_n_29;
  wire add_23_2_n_30, add_23_2_n_31, add_23_2_n_32, add_23_2_n_33,
       add_23_2_n_34, add_23_2_n_35, add_23_2_n_36, add_23_2_n_37;
  wire add_23_2_n_38, add_23_2_n_39, add_23_2_n_40, add_23_2_n_41,
       add_23_2_n_42, add_23_2_n_43, add_23_2_n_44, add_23_2_n_45;
  wire add_23_2_n_46, add_23_2_n_47, add_23_2_n_48, add_23_2_n_49,
       add_23_2_n_50, add_23_2_n_51, add_23_2_n_52, add_23_2_n_53;
  wire add_23_2_n_54, add_23_2_n_55, add_23_2_n_56, add_23_2_n_57,
       add_23_2_n_58, add_23_2_n_59, add_23_2_n_60, add_23_2_n_61;
  wire add_23_2_n_62, add_23_2_n_63, add_23_2_n_64, add_23_2_n_65,
       add_23_2_n_66, add_23_2_n_67, add_23_2_n_68, add_23_2_n_69;
  wire add_23_2_n_70, add_23_2_n_71, add_23_2_n_72, add_23_2_n_73,
       add_23_2_n_74, add_23_2_n_75, add_23_2_n_76, add_23_2_n_77;
  wire add_23_2_n_78, add_23_2_n_79, add_23_2_n_80, add_23_2_n_81,
       add_23_2_n_82, add_23_2_n_83, add_23_2_n_84, add_23_2_n_85;
  wire add_23_2_n_86, add_23_2_n_87, add_23_2_n_88, add_23_2_n_89,
       add_23_2_n_90, add_23_2_n_91, add_23_2_n_92, add_23_2_n_93;
  wire add_23_2_n_94, add_23_2_n_95, add_23_2_n_96, add_23_2_n_97,
       add_23_2_n_98, add_23_2_n_99, add_23_2_n_100, add_23_2_n_101;
  wire add_23_2_n_102, add_23_2_n_103, add_23_2_n_104, add_23_2_n_105,
       add_23_2_n_106, add_23_2_n_107, add_23_2_n_108, add_23_2_n_109;
  wire add_23_2_n_110, add_23_2_n_111, add_23_2_n_112, add_23_2_n_113,
       add_23_2_n_114, add_23_2_n_115, add_23_2_n_116, add_23_2_n_117;
  wire add_23_2_n_118, add_23_2_n_119, add_23_2_n_120, add_23_2_n_121,
       add_23_2_n_122, add_23_2_n_123, add_23_2_n_124, add_23_2_n_125;
  wire add_23_2_n_126, add_23_2_n_127, add_23_2_n_128, add_23_2_n_129,
       add_23_2_n_130, add_23_2_n_131, add_23_2_n_132, add_23_2_n_133;
  wire add_23_2_n_135, add_23_2_n_136, add_23_2_n_137, n_182, n_183,
       n_184, n_190, n_191;
  wire n_192, n_194, n_196, n_197, n_198, n_199, n_201, n_204;
  wire n_205, n_206, n_211;
  MXI2X1 add_23_2_g576(.A (add_23_2_n_27), .B (in2[17]), .S0
       (add_23_2_n_135), .Y (out1[17]));
  MXI2X1 add_23_2_g577(.A (add_23_2_n_24), .B (in2[21]), .S0
       (add_23_2_n_133), .Y (out1[21]));
  MXI2X1 add_23_2_g578(.A (add_23_2_n_26), .B (in2[19]), .S0
       (add_23_2_n_131), .Y (out1[19]));
  MXI2X1 add_23_2_g579(.A (add_23_2_n_25), .B (in2[23]), .S0
       (add_23_2_n_130), .Y (out1[23]));
  MXI2X1 add_23_2_g580(.A (add_23_2_n_23), .B (in2[22]), .S0
       (add_23_2_n_132), .Y (out1[22]));
  MXI2X1 add_23_2_g581(.A (add_23_2_n_21), .B (in2[20]), .S0
       (add_23_2_n_136), .Y (out1[20]));
  MXI2X1 add_23_2_g582(.A (add_23_2_n_20), .B (in2[18]), .S0
       (add_23_2_n_137), .Y (out1[18]));
  MXI2XL add_23_2_g586(.A (add_23_2_n_55), .B (add_23_2_n_56), .S0
       (add_23_2_n_129), .Y (out1[9]));
  MXI2XL add_23_2_g589(.A (in2[16]), .B (add_23_2_n_19), .S0
       (add_23_2_n_124), .Y (out1[16]));
  MXI2XL add_23_2_g590(.A (in2[14]), .B (add_23_2_n_22), .S0
       (add_23_2_n_122), .Y (out1[14]));
  NOR2X1 add_23_2_g591(.A (add_23_2_n_33), .B (add_23_2_n_124), .Y
       (add_23_2_n_137));
  NOR2X1 add_23_2_g592(.A (add_23_2_n_52), .B (add_23_2_n_124), .Y
       (add_23_2_n_136));
  NOR2X1 add_23_2_g593(.A (add_23_2_n_19), .B (add_23_2_n_124), .Y
       (add_23_2_n_135));
  NOR2X1 add_23_2_g594(.A (add_23_2_n_77), .B (n_211), .Y (out1[24]));
  NOR2X1 add_23_2_g595(.A (add_23_2_n_85), .B (add_23_2_n_124), .Y
       (add_23_2_n_133));
  NOR2X1 add_23_2_g596(.A (add_23_2_n_82), .B (add_23_2_n_124), .Y
       (add_23_2_n_132));
  NOR2X1 add_23_2_g597(.A (add_23_2_n_64), .B (add_23_2_n_124), .Y
       (add_23_2_n_131));
  NOR2X1 add_23_2_g598(.A (add_23_2_n_75), .B (add_23_2_n_124), .Y
       (add_23_2_n_130));
  NOR2BX1 add_23_2_g600(.AN (add_23_2_n_34), .B (add_23_2_n_120), .Y
       (add_23_2_n_129));
  NOR2X1 add_23_2_g601(.A (add_23_2_n_91), .B (add_23_2_n_119), .Y
       (add_23_2_n_128));
  NOR2BX1 add_23_2_g602(.AN (add_23_2_n_94), .B (add_23_2_n_117), .Y
       (add_23_2_n_127));
  NOR2BX1 add_23_2_g603(.AN (add_23_2_n_101), .B (add_23_2_n_118), .Y
       (add_23_2_n_126));
  NOR2X1 add_23_2_g604(.A (add_23_2_n_81), .B (add_23_2_n_121), .Y
       (add_23_2_n_125));
  NOR2X1 add_23_2_g608(.A (add_23_2_n_100), .B (add_23_2_n_114), .Y
       (add_23_2_n_123));
  NOR2X1 add_23_2_g609(.A (add_23_2_n_103), .B (add_23_2_n_115), .Y
       (add_23_2_n_122));
  NOR2X4 add_23_2_g610(.A (add_23_2_n_102), .B (add_23_2_n_116), .Y
       (add_23_2_n_124));
  NOR2X1 add_23_2_g611(.A (add_23_2_n_68), .B (add_23_2_n_113), .Y
       (add_23_2_n_121));
  NOR2X1 add_23_2_g612(.A (add_23_2_n_44), .B (add_23_2_n_113), .Y
       (add_23_2_n_120));
  NOR2X1 add_23_2_g613(.A (add_23_2_n_87), .B (add_23_2_n_113), .Y
       (add_23_2_n_119));
  NOR2X1 add_23_2_g614(.A (add_23_2_n_95), .B (add_23_2_n_113), .Y
       (add_23_2_n_118));
  NOR2X1 add_23_2_g615(.A (add_23_2_n_86), .B (add_23_2_n_113), .Y
       (add_23_2_n_117));
  NOR2X4 add_23_2_g616(.A (add_23_2_n_93), .B (add_23_2_n_113), .Y
       (add_23_2_n_116));
  NOR2X1 add_23_2_g617(.A (add_23_2_n_96), .B (add_23_2_n_113), .Y
       (add_23_2_n_115));
  NOR2X1 add_23_2_g618(.A (add_23_2_n_89), .B (add_23_2_n_113), .Y
       (add_23_2_n_114));
  NOR2X6 add_23_2_g619(.A (add_23_2_n_98), .B (add_23_2_n_108), .Y
       (add_23_2_n_113));
  NOR2BX1 add_23_2_g621(.AN (add_23_2_n_46), .B (add_23_2_n_109), .Y
       (add_23_2_n_112));
  NOR2X1 add_23_2_g624(.A (add_23_2_n_99), .B (add_23_2_n_107), .Y
       (add_23_2_n_111));
  NOR2X1 add_23_2_g625(.A (add_23_2_n_70), .B (n_201), .Y
       (add_23_2_n_110));
  NOR2X1 add_23_2_g626(.A (add_23_2_n_47), .B (n_201), .Y
       (add_23_2_n_109));
  NOR2X6 add_23_2_g627(.A (add_23_2_n_84), .B (add_23_2_n_105), .Y
       (add_23_2_n_108));
  NOR2X1 add_23_2_g628(.A (add_23_2_n_83), .B (n_201), .Y
       (add_23_2_n_107));
  NOR2BX1 add_23_2_g629(.AN (add_23_2_n_32), .B (add_23_2_n_9), .Y
       (add_23_2_n_106));
  NOR2X6 add_23_2_g631(.A (add_23_2_n_78), .B (add_23_2_n_104), .Y
       (add_23_2_n_105));
  NOR2X6 add_23_2_g633(.A (add_23_2_n_97), .B (add_23_2_n_65), .Y
       (add_23_2_n_104));
  NOR2X1 add_23_2_g634(.A (add_23_2_n_41), .B (add_23_2_n_90), .Y
       (add_23_2_n_103));
  NOR2X2 add_23_2_g635(.A (add_23_2_n_54), .B (add_23_2_n_90), .Y
       (add_23_2_n_102));
  NAND2X1 add_23_2_g636(.A (in2[12]), .B (add_23_2_n_91), .Y
       (add_23_2_n_101));
  NOR2X1 add_23_2_g637(.A (add_23_2_n_74), .B (add_23_2_n_90), .Y
       (add_23_2_n_100));
  OAI21X1 add_23_2_g638(.A0 (n_197), .A1 (n_191), .B0 (add_23_2_n_36),
       .Y (add_23_2_n_99));
  OAI21X4 add_23_2_g639(.A0 (add_23_2_n_62), .A1 (add_23_2_n_79), .B0
       (add_23_2_n_76), .Y (add_23_2_n_98));
  NOR2X6 add_23_2_g640(.A (add_23_2_n_7), .B (add_23_2_n_92), .Y
       (add_23_2_n_97));
  OR2XL add_23_2_g642(.A (add_23_2_n_41), .B (add_23_2_n_87), .Y
       (add_23_2_n_96));
  NAND2X1 add_23_2_g643(.A (in2[12]), .B (add_23_2_n_88), .Y
       (add_23_2_n_95));
  NAND2XL add_23_2_g644(.A (in2[10]), .B (add_23_2_n_81), .Y
       (add_23_2_n_94));
  NAND2BX2 add_23_2_g645(.AN (add_23_2_n_54), .B (add_23_2_n_88), .Y
       (add_23_2_n_93));
  NOR2X6 add_23_2_g646(.A (add_23_2_n_49), .B (add_23_2_n_29), .Y
       (add_23_2_n_92));
  INVX1 add_23_2_g647(.A (add_23_2_n_91), .Y (add_23_2_n_90));
  NOR2X2 add_23_2_g648(.A (add_23_2_n_50), .B (add_23_2_n_80), .Y
       (add_23_2_n_91));
  NAND2BX1 add_23_2_g649(.AN (add_23_2_n_74), .B (add_23_2_n_88), .Y
       (add_23_2_n_89));
  INVX1 add_23_2_g651(.A (add_23_2_n_88), .Y (add_23_2_n_87));
  NAND2X1 add_23_2_g652(.A (in2[10]), .B (add_23_2_n_67), .Y
       (add_23_2_n_86));
  NAND2X1 add_23_2_g653(.A (in2[20]), .B (add_23_2_n_53), .Y
       (add_23_2_n_85));
  NAND2X2 add_23_2_g654(.A (add_23_2_n_61), .B (add_23_2_n_69), .Y
       (add_23_2_n_84));
  OR2XL add_23_2_g655(.A (n_199), .B (add_23_2_n_70), .Y
       (add_23_2_n_83));
  OR2XL add_23_2_g656(.A (add_23_2_n_43), .B (add_23_2_n_52), .Y
       (add_23_2_n_82));
  NOR2X4 add_23_2_g657(.A (add_23_2_n_50), .B (add_23_2_n_68), .Y
       (add_23_2_n_88));
  INVX1 add_23_2_g658(.A (add_23_2_n_80), .Y (add_23_2_n_81));
  OAI21X2 add_23_2_g660(.A0 (add_23_2_n_32), .A1 (add_23_2_n_30), .B0
       (add_23_2_n_37), .Y (add_23_2_n_78));
  NAND4BX1 add_23_2_g661(.AN (add_23_2_n_43), .B (add_23_2_n_53), .C
       (in2[23]), .D (in2[22]), .Y (add_23_2_n_77));
  AOI2BB1X4 add_23_2_g662(.A0N (add_23_2_n_36), .A1N (add_23_2_n_48),
       .B0 (add_23_2_n_38), .Y (add_23_2_n_76));
  NAND3BXL add_23_2_g663(.AN (add_23_2_n_43), .B (add_23_2_n_53), .C
       (in2[22]), .Y (add_23_2_n_75));
  NOR2BX1 add_23_2_g664(.AN (add_23_2_n_39), .B (add_23_2_n_66), .Y
       (add_23_2_n_80));
  NOR2X2 add_23_2_g665(.A (add_23_2_n_6), .B (add_23_2_n_51), .Y
       (add_23_2_n_79));
  INVX1 add_23_2_g669(.A (add_23_2_n_69), .Y (add_23_2_n_70));
  INVX1 add_23_2_g670(.A (add_23_2_n_67), .Y (add_23_2_n_68));
  NOR2X1 add_23_2_g671(.A (add_23_2_n_34), .B (add_23_2_n_45), .Y
       (add_23_2_n_66));
  NAND2X6 add_23_2_g672(.A (add_23_2_n_31), .B (add_23_2_n_8), .Y
       (add_23_2_n_65));
  OR2XL add_23_2_g673(.A (add_23_2_n_20), .B (add_23_2_n_33), .Y
       (add_23_2_n_64));
  OR2XL add_23_2_g674(.A (add_23_2_n_22), .B (add_23_2_n_41), .Y
       (add_23_2_n_74));
  NOR2X1 add_23_2_g675(.A (add_23_2_n_6), .B (add_23_2_n_35), .Y
       (add_23_2_n_73));
  NAND2BX1 add_23_2_g676(.AN (n_196), .B (add_23_2_n_36), .Y
       (add_23_2_n_72));
  NOR2X1 add_23_2_g677(.A (add_23_2_n_7), .B (add_23_2_n_49), .Y
       (add_23_2_n_63));
  NOR2X1 add_23_2_g678(.A (add_23_2_n_38), .B (n_194), .Y
       (add_23_2_n_71));
  NOR2X2 add_23_2_g679(.A (add_23_2_n_35), .B (add_23_2_n_47), .Y
       (add_23_2_n_69));
  NOR2X1 add_23_2_g680(.A (add_23_2_n_45), .B (add_23_2_n_44), .Y
       (add_23_2_n_67));
  INVX1 add_23_2_g681(.A (add_23_2_n_61), .Y (add_23_2_n_62));
  INVX1 add_23_2_g686(.A (add_23_2_n_55), .Y (add_23_2_n_56));
  INVX1 add_23_2_g687(.A (add_23_2_n_53), .Y (add_23_2_n_52));
  NOR2X2 add_23_2_g688(.A (add_23_2_n_46), .B (add_23_2_n_35), .Y
       (add_23_2_n_51));
  NOR2X2 add_23_2_g690(.A (add_23_2_n_48), .B (add_23_2_n_42), .Y
       (add_23_2_n_61));
  NAND2X1 add_23_2_g691(.A (add_23_2_n_37), .B (add_23_2_n_31), .Y
       (add_23_2_n_60));
  NAND2BX1 add_23_2_g692(.AN (add_23_2_n_44), .B (add_23_2_n_34), .Y
       (add_23_2_n_59));
  NAND2X1 add_23_2_g693(.A (add_23_2_n_32), .B (n_204), .Y
       (add_23_2_n_58));
  NAND2BX1 add_23_2_g694(.AN (add_23_2_n_47), .B (add_23_2_n_46), .Y
       (add_23_2_n_57));
  NOR2BX1 add_23_2_g695(.AN (add_23_2_n_39), .B (add_23_2_n_45), .Y
       (add_23_2_n_55));
  OR2XL add_23_2_g696(.A (add_23_2_n_28), .B (add_23_2_n_41), .Y
       (add_23_2_n_54));
  NOR2X1 add_23_2_g697(.A (add_23_2_n_40), .B (add_23_2_n_33), .Y
       (add_23_2_n_53));
  NAND2X1 add_23_2_g698(.A (in2[19]), .B (in2[18]), .Y (add_23_2_n_40));
  NAND2X1 add_23_2_g699(.A (in2[11]), .B (in2[10]), .Y (add_23_2_n_50));
  NOR2X6 add_23_2_g701(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_49));
  NOR2X4 add_23_2_g702(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_48));
  NOR2X1 add_23_2_g703(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_47));
  NAND2X2 add_23_2_g704(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_46));
  NOR2X2 add_23_2_g705(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_45));
  NOR2X2 add_23_2_g706(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_44));
  NAND2X1 add_23_2_g707(.A (in2[21]), .B (in2[20]), .Y (add_23_2_n_43));
  NOR2X2 add_23_2_g708(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_42));
  NAND2X2 add_23_2_g709(.A (in2[13]), .B (in2[12]), .Y (add_23_2_n_41));
  INVX2 add_23_2_g710(.A (add_23_2_n_30), .Y (add_23_2_n_31));
  NAND2X1 add_23_2_g712(.A (in2[15]), .B (in2[14]), .Y (add_23_2_n_28));
  NAND2X1 add_23_2_g713(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_39));
  AND2X1 add_23_2_g715(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_38));
  NAND2X1 add_23_2_g716(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_37));
  NAND2X4 add_23_2_g717(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_36));
  NOR2X4 add_23_2_g718(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_35));
  NAND2X2 add_23_2_g719(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_34));
  NAND2X1 add_23_2_g720(.A (in2[17]), .B (in2[16]), .Y (add_23_2_n_33));
  NAND2X2 add_23_2_g721(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_32));
  NOR2X6 add_23_2_g722(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_30));
  NAND2X8 add_23_2_g723(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_29));
  INVXL add_23_2_g730(.A (in2[17]), .Y (add_23_2_n_27));
  INVXL add_23_2_g733(.A (in2[19]), .Y (add_23_2_n_26));
  INVXL add_23_2_g735(.A (in2[23]), .Y (add_23_2_n_25));
  INVXL add_23_2_g739(.A (in2[21]), .Y (add_23_2_n_24));
  INVXL add_23_2_g740(.A (in2[22]), .Y (add_23_2_n_23));
  INVX1 add_23_2_g741(.A (in2[14]), .Y (add_23_2_n_22));
  INVXL add_23_2_g742(.A (in2[20]), .Y (add_23_2_n_21));
  INVX1 add_23_2_g743(.A (in2[18]), .Y (add_23_2_n_20));
  INVX1 add_23_2_g744(.A (in2[16]), .Y (add_23_2_n_19));
  XNOR2X1 add_23_2_g2(.A (add_23_2_n_29), .B (add_23_2_n_63), .Y
       (out1[1]));
  NOR2BX1 add_23_2_g746(.AN (n_190), .B (add_23_2_n_110), .Y
       (add_23_2_n_17));
  XNOR2X1 add_23_2_g747(.A (add_23_2_n_73), .B (add_23_2_n_112), .Y
       (out1[5]));
  CLKXOR2X1 add_23_2_g748(.A (add_23_2_n_72), .B (add_23_2_n_17), .Y
       (out1[6]));
  XNOR2X1 add_23_2_g749(.A (add_23_2_n_71), .B (add_23_2_n_111), .Y
       (out1[7]));
  CLKXOR2X1 add_23_2_g750(.A (add_23_2_n_60), .B (add_23_2_n_106), .Y
       (out1[3]));
  CLKXOR2X1 add_23_2_g751(.A (add_23_2_n_59), .B (add_23_2_n_113), .Y
       (out1[8]));
  CLKXOR2X1 add_23_2_g752(.A (add_23_2_n_58), .B (n_182), .Y (out1[2]));
  CLKXOR2X1 add_23_2_g753(.A (add_23_2_n_57), .B (n_201), .Y (out1[4]));
  NOR2BX1 add_23_2_g754(.AN (n_205), .B (n_183), .Y (add_23_2_n_9));
  OR2X6 add_23_2_g755(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_8));
  CLKAND2X6 add_23_2_g756(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_7));
  AND2X1 add_23_2_g757(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_6));
  CLKXOR2X1 add_23_2_g758(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  XNOR2XL add_23_2_g759(.A (in2[11]), .B (add_23_2_n_127), .Y
       (out1[11]));
  XNOR2XL add_23_2_g760(.A (in2[13]), .B (add_23_2_n_126), .Y
       (out1[13]));
  XNOR2XL add_23_2_g761(.A (in2[15]), .B (add_23_2_n_123), .Y
       (out1[15]));
  XNOR2XL add_23_2_g762(.A (in2[10]), .B (add_23_2_n_125), .Y
       (out1[10]));
  XNOR2XL add_23_2_g763(.A (in2[12]), .B (add_23_2_n_128), .Y
       (out1[12]));
  INVXL fopt(.A (n_184), .Y (n_182));
  INVXL fopt764(.A (n_184), .Y (n_183));
  INVXL fopt765(.A (add_23_2_n_97), .Y (n_184));
  INVXL fopt768(.A (n_192), .Y (n_190));
  INVXL fopt769(.A (n_192), .Y (n_191));
  INVXL fopt770(.A (add_23_2_n_79), .Y (n_192));
  BUFX2 fopt771(.A (add_23_2_n_48), .Y (n_194));
  INVXL fopt772(.A (n_198), .Y (n_196));
  INVXL fopt773(.A (n_198), .Y (n_197));
  INVXL fopt774(.A (n_199), .Y (n_198));
  BUFX2 fopt775(.A (add_23_2_n_42), .Y (n_199));
  BUFX3 fopt776(.A (add_23_2_n_105), .Y (n_201));
  INVXL fopt777(.A (n_206), .Y (n_204));
  INVXL fopt778(.A (n_206), .Y (n_205));
  INVXL fopt779(.A (add_23_2_n_8), .Y (n_206));
  BUFX2 fopt780(.A (add_23_2_n_124), .Y (n_211));
endmodule


