`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:06:13 CST (May 25 2023 22:06:13 UTC)

module SobelFilter_N_Mux_16_2_117_1(in2, ctrl1, out1);
  input [15:0] in2;
  input ctrl1;
  output [15:0] out1;
  wire [15:0] in2;
  wire ctrl1;
  wire [15:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_23;
  NOR2X1 g95(.A (ctrl1), .B (n_2), .Y (out1[11]));
  NOR2X1 g90(.A (ctrl1), .B (n_11), .Y (out1[14]));
  NOR2X1 g98(.A (ctrl1), .B (n_7), .Y (out1[13]));
  NOR2X1 g91(.A (ctrl1), .B (n_5), .Y (out1[12]));
  NOR2X1 g93(.A (ctrl1), .B (n_14), .Y (out1[15]));
  NAND2X1 g97(.A (n_13), .B (n_23), .Y (out1[3]));
  NOR2X1 g99(.A (ctrl1), .B (n_3), .Y (out1[10]));
  NOR2X1 g102(.A (ctrl1), .B (n_4), .Y (out1[9]));
  NAND2X1 g100(.A (n_0), .B (n_23), .Y (out1[4]));
  NAND2X1 g94(.A (n_10), .B (n_23), .Y (out1[7]));
  NAND2X1 g96(.A (n_6), .B (n_23), .Y (out1[6]));
  NAND2X1 g101(.A (n_12), .B (n_23), .Y (out1[5]));
  NOR2X1 g92(.A (ctrl1), .B (n_9), .Y (out1[8]));
  NAND2X1 g103(.A (n_8), .B (n_23), .Y (out1[2]));
  NAND2X1 g104(.A (n_1), .B (n_23), .Y (out1[1]));
  NAND2X1 g89(.A (n_15), .B (n_23), .Y (out1[0]));
  CLKINVX4 g115(.A (in2[0]), .Y (n_15));
  INVX2 g114(.A (in2[15]), .Y (n_14));
  CLKINVX4 g113(.A (in2[3]), .Y (n_13));
  CLKINVX4 g105(.A (in2[5]), .Y (n_12));
  INVX2 g120(.A (in2[14]), .Y (n_11));
  CLKINVX4 g109(.A (in2[7]), .Y (n_10));
  INVX2 g107(.A (in2[8]), .Y (n_9));
  CLKINVX12 g121(.A (ctrl1), .Y (n_23));
  CLKINVX4 g112(.A (in2[2]), .Y (n_8));
  INVX2 g118(.A (in2[13]), .Y (n_7));
  CLKINVX4 g116(.A (in2[6]), .Y (n_6));
  INVX2 g106(.A (in2[12]), .Y (n_5));
  INVX2 g117(.A (in2[9]), .Y (n_4));
  INVX2 g111(.A (in2[10]), .Y (n_3));
  INVX2 g108(.A (in2[11]), .Y (n_2));
  CLKINVX4 g119(.A (in2[1]), .Y (n_1));
  CLKINVX4 g110(.A (in2[4]), .Y (n_0));
endmodule


