`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 05:58:52 CST (May 25 2023 21:58:52 UTC)

module SobelFilter_N_Mux_32_2_109_4(in3, in2, ctrl1, out1);
  input [31:0] in3;
  input [8:0] in2;
  input ctrl1;
  output [31:0] out1;
  wire [31:0] in3;
  wire [8:0] in2;
  wire ctrl1;
  wire [31:0] out1;
  MX2XL g305(.A (in3[6]), .B (in2[6]), .S0 (ctrl1), .Y (out1[6]));
  MX2XL g302(.A (in3[7]), .B (in2[7]), .S0 (ctrl1), .Y (out1[7]));
  MX2XL g300(.A (in3[8]), .B (in2[8]), .S0 (ctrl1), .Y (out1[8]));
  MX2XL g306(.A (in3[5]), .B (in2[5]), .S0 (ctrl1), .Y (out1[5]));
  MX2XL g301(.A (in3[2]), .B (in2[2]), .S0 (ctrl1), .Y (out1[2]));
  MX2XL g298(.A (in3[3]), .B (in2[3]), .S0 (ctrl1), .Y (out1[3]));
  MX2XL g299(.A (in3[4]), .B (in2[4]), .S0 (ctrl1), .Y (out1[4]));
  MX2XL g304(.A (in3[1]), .B (in2[1]), .S0 (ctrl1), .Y (out1[1]));
  MX2XL g303(.A (in3[0]), .B (in2[0]), .S0 (ctrl1), .Y (out1[0]));
  NOR2BX1 g317(.AN (in3[12]), .B (ctrl1), .Y (out1[12]));
  NOR2BX1 g308(.AN (in3[16]), .B (ctrl1), .Y (out1[16]));
  NOR2BX1 g310(.AN (in3[15]), .B (ctrl1), .Y (out1[15]));
  NOR2BX1 g307(.AN (in3[14]), .B (ctrl1), .Y (out1[14]));
  NOR2BX1 g314(.AN (in3[13]), .B (ctrl1), .Y (out1[13]));
  NOR2BX1 g326(.AN (in3[19]), .B (ctrl1), .Y (out1[19]));
  NOR2BX1 g328(.AN (in3[18]), .B (ctrl1), .Y (out1[18]));
  NOR2BX1 g324(.AN (in3[11]), .B (ctrl1), .Y (out1[11]));
  NOR2BX1 g320(.AN (in3[10]), .B (ctrl1), .Y (out1[10]));
  NOR2BX1 g321(.AN (in3[9]), .B (ctrl1), .Y (out1[9]));
  NOR2BX1 g329(.AN (in3[17]), .B (ctrl1), .Y (out1[17]));
  NOR2BX1 g323(.AN (in3[26]), .B (ctrl1), .Y (out1[26]));
  NOR2BX1 g313(.AN (in3[30]), .B (ctrl1), .Y (out1[30]));
  NOR2BX1 g318(.AN (in3[20]), .B (ctrl1), .Y (out1[20]));
  NOR2BX1 g325(.AN (in3[29]), .B (ctrl1), .Y (out1[29]));
  NOR2BX1 g312(.AN (in3[28]), .B (ctrl1), .Y (out1[28]));
  NOR2BX1 g315(.AN (in3[27]), .B (ctrl1), .Y (out1[27]));
  NOR2BX1 g322(.AN (in3[31]), .B (ctrl1), .Y (out1[31]));
  NOR2BX1 g327(.AN (in3[25]), .B (ctrl1), .Y (out1[25]));
  NOR2BX1 g309(.AN (in3[24]), .B (ctrl1), .Y (out1[24]));
  NOR2BX1 g311(.AN (in3[23]), .B (ctrl1), .Y (out1[23]));
  NOR2BX1 g316(.AN (in3[22]), .B (ctrl1), .Y (out1[22]));
  NOR2BX1 g319(.AN (in3[21]), .B (ctrl1), .Y (out1[21]));
endmodule


