`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 07:02:35 CST (May 25 2023 23:02:35 UTC)

module SobelFilter_Add_32Sx5U_32S_4(in2, in1, out1);
  input [31:0] in2;
  input [4:0] in1;
  output [31:0] out1;
  wire [31:0] in2;
  wire [4:0] in1;
  wire [31:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_9, add_23_2_n_10, add_23_2_n_11,
       add_23_2_n_12, add_23_2_n_13, add_23_2_n_14, add_23_2_n_15;
  wire add_23_2_n_16, add_23_2_n_17, add_23_2_n_18, add_23_2_n_19,
       add_23_2_n_20, add_23_2_n_21, add_23_2_n_22, add_23_2_n_25;
  wire add_23_2_n_26, add_23_2_n_27, add_23_2_n_28, add_23_2_n_30,
       add_23_2_n_31, add_23_2_n_34, add_23_2_n_35, add_23_2_n_36;
  wire add_23_2_n_37, add_23_2_n_38, add_23_2_n_39, add_23_2_n_40,
       add_23_2_n_44, add_23_2_n_45, add_23_2_n_46, add_23_2_n_47;
  wire add_23_2_n_48, add_23_2_n_49, add_23_2_n_50, add_23_2_n_51,
       add_23_2_n_55, add_23_2_n_56, add_23_2_n_57, add_23_2_n_58;
  wire add_23_2_n_59, add_23_2_n_60, add_23_2_n_65, add_23_2_n_66,
       add_23_2_n_67, add_23_2_n_68, add_23_2_n_74;
  XNOR2X1 add_23_2_g622(.A (in2[31]), .B (add_23_2_n_74), .Y
       (out1[31]));
  XNOR2X1 add_23_2_g623(.A (in2[23]), .B (add_23_2_n_66), .Y
       (out1[23]));
  XNOR2X1 add_23_2_g624(.A (in2[27]), .B (add_23_2_n_67), .Y
       (out1[27]));
  XNOR2X1 add_23_2_g625(.A (in2[29]), .B (add_23_2_n_65), .Y
       (out1[29]));
  XNOR2X1 add_23_2_g626(.A (in2[15]), .B (add_23_2_n_58), .Y
       (out1[15]));
  XNOR2X1 add_23_2_g627(.A (in2[19]), .B (add_23_2_n_56), .Y
       (out1[19]));
  XNOR2X1 add_23_2_g628(.A (in2[21]), .B (add_23_2_n_57), .Y
       (out1[21]));
  XNOR2X1 add_23_2_g629(.A (in2[25]), .B (add_23_2_n_51), .Y
       (out1[25]));
  XNOR2X1 add_23_2_g630(.A (in2[30]), .B (add_23_2_n_68), .Y
       (out1[30]));
  XNOR2X1 add_23_2_g631(.A (in2[17]), .B (add_23_2_n_47), .Y
       (out1[17]));
  XNOR2X1 add_23_2_g632(.A (in2[13]), .B (add_23_2_n_46), .Y
       (out1[13]));
  XNOR2X1 add_23_2_g633(.A (in2[11]), .B (add_23_2_n_45), .Y
       (out1[11]));
  NAND2BX1 add_23_2_g634(.AN (add_23_2_n_68), .B (in2[30]), .Y
       (add_23_2_n_74));
  XNOR2X1 add_23_2_g635(.A (in2[28]), .B (add_23_2_n_55), .Y
       (out1[28]));
  XNOR2X1 add_23_2_g636(.A (in2[9]), .B (add_23_2_n_0), .Y (out1[9]));
  XNOR2X1 add_23_2_g637(.A (in2[7]), .B (add_23_2_n_38), .Y (out1[7]));
  XNOR2X1 add_23_2_g638(.A (in2[22]), .B (add_23_2_n_59), .Y
       (out1[22]));
  XNOR2X1 add_23_2_g639(.A (in2[26]), .B (add_23_2_n_60), .Y
       (out1[26]));
  NAND2BX1 add_23_2_g640(.AN (add_23_2_n_60), .B (in2[26]), .Y
       (add_23_2_n_67));
  NAND2BX1 add_23_2_g641(.AN (add_23_2_n_59), .B (in2[22]), .Y
       (add_23_2_n_66));
  NAND2BX1 add_23_2_g642(.AN (add_23_2_n_55), .B (in2[28]), .Y
       (add_23_2_n_65));
  NAND3BXL add_23_2_g643(.AN (add_23_2_n_55), .B (in2[29]), .C
       (in2[28]), .Y (add_23_2_n_68));
  XNOR2X1 add_23_2_g644(.A (in2[18]), .B (add_23_2_n_50), .Y
       (out1[18]));
  XOR2XL add_23_2_g645(.A (in2[24]), .B (add_23_2_n_44), .Y (out1[24]));
  XNOR2X1 add_23_2_g646(.A (in2[14]), .B (add_23_2_n_49), .Y
       (out1[14]));
  XNOR2X1 add_23_2_g647(.A (in2[20]), .B (add_23_2_n_48), .Y
       (out1[20]));
  NAND2BX1 add_23_2_g648(.AN (add_23_2_n_49), .B (in2[14]), .Y
       (add_23_2_n_58));
  NAND2BX1 add_23_2_g649(.AN (add_23_2_n_48), .B (in2[20]), .Y
       (add_23_2_n_57));
  NAND2BX1 add_23_2_g650(.AN (add_23_2_n_50), .B (in2[18]), .Y
       (add_23_2_n_56));
  NAND2BX1 add_23_2_g651(.AN (add_23_2_n_4), .B (add_23_2_n_44), .Y
       (add_23_2_n_60));
  OR2XL add_23_2_g652(.A (add_23_2_n_14), .B (add_23_2_n_48), .Y
       (add_23_2_n_59));
  XNOR2X1 add_23_2_g653(.A (in2[16]), .B (add_23_2_n_37), .Y
       (out1[16]));
  XOR2XL add_23_2_g654(.A (in2[10]), .B (add_23_2_n_39), .Y (out1[10]));
  XOR2XL add_23_2_g655(.A (in2[12]), .B (add_23_2_n_40), .Y (out1[12]));
  NAND2X1 add_23_2_g656(.A (in2[24]), .B (add_23_2_n_44), .Y
       (add_23_2_n_51));
  NAND4BX1 add_23_2_g657(.AN (add_23_2_n_4), .B (add_23_2_n_44), .C
       (in2[27]), .D (in2[26]), .Y (add_23_2_n_55));
  OR2XL add_23_2_g658(.A (add_23_2_n_5), .B (add_23_2_n_37), .Y
       (add_23_2_n_50));
  NAND2BX1 add_23_2_g659(.AN (add_23_2_n_7), .B (add_23_2_n_40), .Y
       (add_23_2_n_49));
  OR2XL add_23_2_g660(.A (add_23_2_n_15), .B (add_23_2_n_37), .Y
       (add_23_2_n_48));
  NAND2X1 add_23_2_g661(.A (in2[16]), .B (add_23_2_n_36), .Y
       (add_23_2_n_47));
  NAND2X1 add_23_2_g662(.A (in2[12]), .B (add_23_2_n_40), .Y
       (add_23_2_n_46));
  NAND2X1 add_23_2_g663(.A (in2[10]), .B (add_23_2_n_39), .Y
       (add_23_2_n_45));
  NOR4X1 add_23_2_g664(.A (add_23_2_n_37), .B (add_23_2_n_15), .C
       (add_23_2_n_9), .D (add_23_2_n_14), .Y (add_23_2_n_44));
  XNOR2X1 add_23_2_g665(.A (in2[8]), .B (add_23_2_n_31), .Y (out1[8]));
  XNOR2X1 add_23_2_g666(.A (in2[6]), .B (add_23_2_n_34), .Y (out1[6]));
  XOR2XL add_23_2_g667(.A (in2[5]), .B (add_23_2_n_35), .Y (out1[5]));
  NOR2X1 add_23_2_g668(.A (add_23_2_n_16), .B (add_23_2_n_31), .Y
       (add_23_2_n_40));
  NOR2X1 add_23_2_g669(.A (add_23_2_n_6), .B (add_23_2_n_31), .Y
       (add_23_2_n_39));
  NAND2BX1 add_23_2_g671(.AN (add_23_2_n_34), .B (in2[6]), .Y
       (add_23_2_n_38));
  INVX1 add_23_2_g672(.A (add_23_2_n_36), .Y (add_23_2_n_37));
  NOR4X1 add_23_2_g673(.A (add_23_2_n_31), .B (add_23_2_n_16), .C
       (add_23_2_n_8), .D (add_23_2_n_7), .Y (add_23_2_n_36));
  OAI21X1 add_23_2_g674(.A0 (add_23_2_n_1), .A1 (add_23_2_n_27), .B0
       (add_23_2_n_2), .Y (add_23_2_n_35));
  AOI21X1 add_23_2_g675(.A0 (add_23_2_n_17), .A1 (add_23_2_n_28), .B0
       (add_23_2_n_20), .Y (add_23_2_n_34));
  XNOR2X1 add_23_2_g676(.A (add_23_2_n_21), .B (add_23_2_n_27), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g677(.A (add_23_2_n_19), .B (add_23_2_n_30), .Y
       (out1[3]));
  AOI32X1 add_23_2_g679(.A0 (add_23_2_n_28), .A1 (add_23_2_n_3), .A2
       (add_23_2_n_17), .B0 (add_23_2_n_3), .B1 (add_23_2_n_20), .Y
       (add_23_2_n_31));
  OAI2BB1X1 add_23_2_g680(.A0N (add_23_2_n_12), .A1N (add_23_2_n_25),
       .B0 (add_23_2_n_11), .Y (add_23_2_n_30));
  XNOR2X1 add_23_2_g681(.A (add_23_2_n_18), .B (add_23_2_n_25), .Y
       (out1[2]));
  INVX1 add_23_2_g682(.A (add_23_2_n_28), .Y (add_23_2_n_27));
  OAI211X1 add_23_2_g683(.A0 (add_23_2_n_11), .A1 (add_23_2_n_10), .B0
       (add_23_2_n_26), .C0 (add_23_2_n_13), .Y (add_23_2_n_28));
  NAND3BXL add_23_2_g684(.AN (add_23_2_n_10), .B (add_23_2_n_25), .C
       (add_23_2_n_12), .Y (add_23_2_n_26));
  ADDFX1 add_23_2_g685(.A (add_23_2_n_22), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_25), .S (out1[1]));
  ADDHX1 add_23_2_g686(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_22),
       .S (out1[0]));
  NOR2BX1 add_23_2_g687(.AN (add_23_2_n_2), .B (add_23_2_n_1), .Y
       (add_23_2_n_21));
  NOR2BX1 add_23_2_g688(.AN (in2[5]), .B (add_23_2_n_2), .Y
       (add_23_2_n_20));
  NAND2BX1 add_23_2_g689(.AN (add_23_2_n_10), .B (add_23_2_n_13), .Y
       (add_23_2_n_19));
  NAND2X1 add_23_2_g690(.A (add_23_2_n_11), .B (add_23_2_n_12), .Y
       (add_23_2_n_18));
  NOR2BX1 add_23_2_g691(.AN (in2[5]), .B (add_23_2_n_1), .Y
       (add_23_2_n_17));
  NAND3BXL add_23_2_g692(.AN (add_23_2_n_6), .B (in2[11]), .C
       (in2[10]), .Y (add_23_2_n_16));
  NAND3BXL add_23_2_g693(.AN (add_23_2_n_5), .B (in2[19]), .C
       (in2[18]), .Y (add_23_2_n_15));
  NAND2X1 add_23_2_g694(.A (in2[23]), .B (in2[22]), .Y (add_23_2_n_9));
  NAND2X1 add_23_2_g695(.A (in2[15]), .B (in2[14]), .Y (add_23_2_n_8));
  NAND2X1 add_23_2_g696(.A (in2[21]), .B (in2[20]), .Y (add_23_2_n_14));
  NAND2X1 add_23_2_g697(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_13));
  OR2X1 add_23_2_g698(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_12));
  NAND2X1 add_23_2_g699(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_11));
  NOR2X1 add_23_2_g700(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_10));
  NAND2X1 add_23_2_g701(.A (in2[13]), .B (in2[12]), .Y (add_23_2_n_7));
  NAND2X1 add_23_2_g702(.A (in2[9]), .B (in2[8]), .Y (add_23_2_n_6));
  NAND2X1 add_23_2_g703(.A (in2[17]), .B (in2[16]), .Y (add_23_2_n_5));
  NAND2X1 add_23_2_g704(.A (in2[25]), .B (in2[24]), .Y (add_23_2_n_4));
  AND2XL add_23_2_g705(.A (in2[7]), .B (in2[6]), .Y (add_23_2_n_3));
  NAND2X1 add_23_2_g706(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_2));
  NOR2X1 add_23_2_g707(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_1));
  NAND2BX1 add_23_2_g2(.AN (add_23_2_n_31), .B (in2[8]), .Y
       (add_23_2_n_0));
endmodule


