`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:08:35 CST (May 25 2023 22:08:35 UTC)

module SobelFilter_N_Mux_32_4_44_1(in5, in4, in3, in2, ctrl1, out1);
  input [31:0] in5;
  input [8:0] in4, in3, in2;
  input [5:0] ctrl1;
  output [31:0] out1;
  wire [31:0] in5;
  wire [8:0] in4, in3, in2;
  wire [5:0] ctrl1;
  wire [31:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_13, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_98, n_100, n_102, n_195, n_196;
  wire n_202;
  NAND3X1 g4027(.A (n_41), .B (n_61), .C (n_76), .Y (out1[7]));
  NAND3X1 g4026(.A (n_50), .B (n_55), .C (n_102), .Y (out1[4]));
  NAND3X1 g4029(.A (n_51), .B (n_58), .C (n_100), .Y (out1[3]));
  NAND3X1 g4028(.A (n_49), .B (n_60), .C (n_69), .Y (out1[8]));
  NAND3X1 g4033(.A (n_54), .B (n_67), .C (n_68), .Y (out1[6]));
  NAND3X1 g4034(.A (n_42), .B (n_66), .C (n_74), .Y (out1[5]));
  NAND3X1 g4032(.A (n_45), .B (n_57), .C (n_70), .Y (out1[2]));
  NAND3X1 g4031(.A (n_43), .B (n_56), .C (n_75), .Y (out1[1]));
  NAND3X1 g4030(.A (n_53), .B (n_59), .C (n_71), .Y (out1[0]));
  NOR2BX1 g4058(.AN (n_48), .B (n_64), .Y (n_102));
  NOR2BXL g4055(.AN (in5[11]), .B (n_98), .Y (out1[11]));
  NOR2BX1 g4060(.AN (n_47), .B (n_63), .Y (n_100));
  NOR2BXL g4038(.AN (in5[31]), .B (n_98), .Y (out1[31]));
  NOR2BXL g4040(.AN (in5[30]), .B (n_98), .Y (out1[30]));
  NOR2BXL g4049(.AN (in5[29]), .B (n_98), .Y (out1[29]));
  NOR2BXL g4044(.AN (in5[19]), .B (n_98), .Y (out1[19]));
  NOR2BXL g4046(.AN (in5[28]), .B (n_98), .Y (out1[28]));
  NOR2BXL g4056(.AN (in5[27]), .B (n_98), .Y (out1[27]));
  NOR2BXL g4054(.AN (in5[26]), .B (n_98), .Y (out1[26]));
  NOR2BXL g4050(.AN (in5[25]), .B (n_98), .Y (out1[25]));
  NOR2BXL g4036(.AN (in5[24]), .B (n_98), .Y (out1[24]));
  NOR2BXL g4039(.AN (in5[23]), .B (n_98), .Y (out1[23]));
  NOR2BXL g4041(.AN (in5[22]), .B (n_98), .Y (out1[22]));
  NOR2BXL g4043(.AN (in5[21]), .B (n_98), .Y (out1[21]));
  NOR2BXL g4042(.AN (in5[20]), .B (n_98), .Y (out1[20]));
  NOR2BXL g4048(.AN (in5[16]), .B (n_98), .Y (out1[16]));
  NOR2BXL g4066(.AN (in5[15]), .B (n_98), .Y (out1[15]));
  NOR2BXL g4035(.AN (in5[14]), .B (n_98), .Y (out1[14]));
  NOR2BXL g4052(.AN (in5[13]), .B (n_98), .Y (out1[13]));
  NOR2BXL g4053(.AN (in5[12]), .B (n_98), .Y (out1[12]));
  NOR2BXL g4047(.AN (in5[17]), .B (n_98), .Y (out1[17]));
  NOR2BXL g4057(.AN (in5[10]), .B (n_98), .Y (out1[10]));
  NOR2BXL g4037(.AN (in5[9]), .B (n_98), .Y (out1[9]));
  NOR2BXL g4045(.AN (in5[18]), .B (n_98), .Y (out1[18]));
  NOR2BX1 g4064(.AN (n_44), .B (n_62), .Y (n_76));
  AOI221X1 g4062(.A0 (in2[1]), .A1 (n_73), .B0 (in3[1]), .B1 (n_72),
       .C0 (n_34), .Y (n_75));
  AOI221X1 g4051(.A0 (in2[5]), .A1 (n_73), .B0 (in3[5]), .B1 (n_72),
       .C0 (n_40), .Y (n_74));
  AOI221X1 g4063(.A0 (in2[0]), .A1 (n_73), .B0 (in3[0]), .B1 (n_72),
       .C0 (n_36), .Y (n_71));
  AOI221X1 g4061(.A0 (in2[2]), .A1 (n_73), .B0 (in3[2]), .B1 (n_72),
       .C0 (n_32), .Y (n_70));
  AOI221X1 g4059(.A0 (in2[8]), .A1 (n_73), .B0 (in3[8]), .B1 (n_72),
       .C0 (n_38), .Y (n_69));
  AOI221X1 g4065(.A0 (in2[6]), .A1 (n_73), .B0 (in3[6]), .B1 (n_72),
       .C0 (n_31), .Y (n_68));
  NAND2XL g4082(.A (in5[6]), .B (n_65), .Y (n_67));
  NAND2X1 g4084(.A (in5[5]), .B (n_65), .Y (n_66));
  OAI2BB1X1 g4085(.A0N (in2[4]), .A1N (n_73), .B0 (n_39), .Y (n_64));
  OAI2BB1X1 g4086(.A0N (in2[3]), .A1N (n_73), .B0 (n_33), .Y (n_63));
  OAI2BB1X1 g4087(.A0N (in2[7]), .A1N (n_73), .B0 (n_35), .Y (n_62));
  NOR2X4 g4088(.A (n_28), .B (n_30), .Y (n_98));
  NAND2XL g4080(.A (in5[7]), .B (n_65), .Y (n_61));
  NAND2X1 g4071(.A (in5[8]), .B (n_65), .Y (n_60));
  NAND2X1 g4072(.A (in5[0]), .B (n_65), .Y (n_59));
  NAND2XL g4073(.A (in5[3]), .B (n_65), .Y (n_58));
  NAND2XL g4075(.A (in5[2]), .B (n_65), .Y (n_57));
  NAND2XL g4077(.A (in5[1]), .B (n_65), .Y (n_56));
  NAND2XL g4070(.A (in5[4]), .B (n_65), .Y (n_55));
  NAND2XL g4081(.A (in5[6]), .B (n_52), .Y (n_54));
  NAND2X1 g4083(.A (in5[0]), .B (n_52), .Y (n_53));
  NAND2XL g4067(.A (in5[3]), .B (n_52), .Y (n_51));
  NAND2XL g4068(.A (in5[4]), .B (n_52), .Y (n_50));
  NAND2X1 g4069(.A (in5[8]), .B (n_52), .Y (n_49));
  NAND2X1 g4090(.A (in4[4]), .B (n_46), .Y (n_48));
  NAND2X1 g4093(.A (in4[3]), .B (n_46), .Y (n_47));
  NAND2XL g4074(.A (in5[2]), .B (n_52), .Y (n_45));
  NAND2X1 g4099(.A (in4[7]), .B (n_46), .Y (n_44));
  NAND2XL g4076(.A (in5[1]), .B (n_52), .Y (n_43));
  NAND2X1 g4078(.A (in5[5]), .B (n_52), .Y (n_42));
  NAND2XL g4079(.A (in5[7]), .B (n_52), .Y (n_41));
  NOR2BX1 g4092(.AN (in4[5]), .B (n_37), .Y (n_40));
  NAND2X1 g4091(.A (in3[4]), .B (n_72), .Y (n_39));
  NOR2BX1 g4089(.AN (in4[8]), .B (n_37), .Y (n_38));
  NOR2BX1 g4097(.AN (in4[0]), .B (n_37), .Y (n_36));
  NAND2X4 g4095(.A (n_16), .B (n_29), .Y (n_65));
  NAND2X1 g4096(.A (in3[7]), .B (n_72), .Y (n_35));
  NOR2BX1 g4098(.AN (in4[1]), .B (n_37), .Y (n_34));
  NAND2X1 g4094(.A (in3[3]), .B (n_72), .Y (n_33));
  NOR2BX1 g4100(.AN (in4[2]), .B (n_37), .Y (n_32));
  NOR2BX1 g4101(.AN (in4[6]), .B (n_37), .Y (n_31));
  NAND2X2 g4102(.A (n_24), .B (n_29), .Y (n_30));
  NAND2X4 g4103(.A (n_27), .B (n_25), .Y (n_52));
  CLKINVX3 g4107(.A (n_37), .Y (n_46));
  NAND2X2 g4105(.A (n_27), .B (n_18), .Y (n_28));
  NOR2X4 g4108(.A (n_2), .B (n_19), .Y (n_29));
  NAND2X8 g4111(.A (n_27), .B (n_22), .Y (n_37));
  NOR2X4 g4110(.A (n_26), .B (n_21), .Y (n_72));
  NOR2X4 g4109(.A (n_26), .B (n_20), .Y (n_73));
  NOR2X4 g4104(.A (n_23), .B (n_17), .Y (n_25));
  NOR2X2 g4106(.A (n_23), .B (n_15), .Y (n_24));
  NOR2X8 g4117(.A (n_4), .B (n_202), .Y (n_22));
  NAND2X4 g4118(.A (n_10), .B (n_13), .Y (n_21));
  NAND2X4 g4119(.A (n_1), .B (n_8), .Y (n_20));
  NOR2X2 g4114(.A (n_196), .B (n_11), .Y (n_19));
  INVX1 g4112(.A (n_17), .Y (n_18));
  INVX1 g4113(.A (n_15), .Y (n_16));
  NOR2X2 g4115(.A (n_6), .B (n_5), .Y (n_17));
  NOR2X1 g4116(.A (ctrl1[0]), .B (n_3), .Y (n_15));
  NOR2X6 g4123(.A (n_195), .B (n_7), .Y (n_13));
  CLKINVX4 g4121(.A (n_26), .Y (n_27));
  NAND2X2 g4132(.A (ctrl1[1]), .B (n_9), .Y (n_11));
  NOR2X6 g4131(.A (ctrl1[3]), .B (n_9), .Y (n_10));
  NOR2X6 g4130(.A (ctrl1[0]), .B (n_7), .Y (n_8));
  NOR2X2 g4133(.A (ctrl1[2]), .B (n_6), .Y (n_23));
  NOR2X4 g4124(.A (ctrl1[1]), .B (ctrl1[0]), .Y (n_5));
  NAND2X6 g4125(.A (ctrl1[3]), .B (ctrl1[2]), .Y (n_4));
  NAND2X1 g4126(.A (ctrl1[2]), .B (ctrl1[1]), .Y (n_3));
  NOR2X1 g4129(.A (ctrl1[3]), .B (ctrl1[1]), .Y (n_2));
  NOR2X4 g4128(.A (ctrl1[3]), .B (ctrl1[2]), .Y (n_1));
  NOR2X6 g4122(.A (ctrl1[1]), .B (ctrl1[0]), .Y (n_0));
  NAND2X8 g4127(.A (ctrl1[5]), .B (ctrl1[4]), .Y (n_26));
  CLKINVX3 g4137(.A (ctrl1[3]), .Y (n_6));
  CLKINVX12 g4136(.A (ctrl1[2]), .Y (n_9));
  CLKINVX12 g4134(.A (ctrl1[1]), .Y (n_7));
  CLKINVX12 fopt(.A (ctrl1[0]), .Y (n_195));
  CLKINVX1 fopt4142(.A (ctrl1[0]), .Y (n_196));
  CLKINVX4 fopt4145(.A (n_0), .Y (n_202));
endmodule


