`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 07:04:11 CST (May 25 2023 23:04:11 UTC)

module SobelFilter_Add_6Sx3U_6S_1(in2, in1, out1);
  input [5:0] in2;
  input [2:0] in1;
  output [5:0] out1;
  wire [5:0] in2;
  wire [2:0] in1;
  wire [5:0] out1;
  wire add_23_2_n_1, add_23_2_n_2, add_23_2_n_4, add_23_2_n_5,
       add_23_2_n_6, add_23_2_n_7, add_23_2_n_8, add_23_2_n_9;
  wire add_23_2_n_10, add_23_2_n_11, add_23_2_n_12, add_23_2_n_13,
       add_23_2_n_14, add_23_2_n_15, add_23_2_n_16, add_23_2_n_18;
  wire add_23_2_n_20, add_23_2_n_21, n_34, n_35, n_36, n_38;
  MXI2XL add_23_2_g98(.A (add_23_2_n_7), .B (in2[5]), .S0
       (add_23_2_n_4), .Y (out1[5]));
  MXI2XL add_23_2_g99(.A (add_23_2_n_5), .B (in2[4]), .S0 (n_38), .Y
       (out1[4]));
  MXI2X1 add_23_2_g100(.A (add_23_2_n_6), .B (in2[3]), .S0
       (add_23_2_n_21), .Y (out1[3]));
  OAI21X1 add_23_2_g102(.A0 (add_23_2_n_9), .A1 (n_35), .B0
       (add_23_2_n_10), .Y (add_23_2_n_21));
  NAND2X1 add_23_2_g104(.A (add_23_2_n_14), .B (add_23_2_n_18), .Y
       (add_23_2_n_20));
  MXI2XL add_23_2_g105(.A (add_23_2_n_1), .B (add_23_2_n_15), .S0
       (n_34), .Y (out1[2]));
  NAND2X1 add_23_2_g106(.A (add_23_2_n_13), .B (add_23_2_n_16), .Y
       (add_23_2_n_18));
  OAI21X4 add_23_2_g108(.A0 (add_23_2_n_11), .A1 (add_23_2_n_8), .B0
       (add_23_2_n_12), .Y (add_23_2_n_16));
  INVX1 add_23_2_g112(.A (add_23_2_n_1), .Y (add_23_2_n_15));
  OR2XL add_23_2_g114(.A (add_23_2_n_6), .B (add_23_2_n_10), .Y
       (add_23_2_n_14));
  NOR2X1 add_23_2_g115(.A (add_23_2_n_6), .B (add_23_2_n_9), .Y
       (add_23_2_n_13));
  NAND2X2 add_23_2_g118(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_12));
  NOR2X8 add_23_2_g119(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_11));
  NAND2X1 add_23_2_g120(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_10));
  NOR2X1 add_23_2_g122(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_9));
  NAND2X6 add_23_2_g123(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_8));
  INVXL add_23_2_g124(.A (in2[5]), .Y (add_23_2_n_7));
  INVX1 add_23_2_g125(.A (in2[3]), .Y (add_23_2_n_6));
  INVX1 add_23_2_g127(.A (in2[4]), .Y (add_23_2_n_5));
  NOR2BX1 add_23_2_g2(.AN (add_23_2_n_20), .B (add_23_2_n_5), .Y
       (add_23_2_n_4));
  XNOR2X1 add_23_2_g128(.A (add_23_2_n_8), .B (add_23_2_n_2), .Y
       (out1[1]));
  NOR2BX1 add_23_2_g129(.AN (add_23_2_n_12), .B (add_23_2_n_11), .Y
       (add_23_2_n_2));
  NAND2BX1 add_23_2_g130(.AN (add_23_2_n_9), .B (add_23_2_n_10), .Y
       (add_23_2_n_1));
  XOR2XL add_23_2_g131(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  BUFX2 fopt(.A (n_36), .Y (n_34));
  CLKINVX1 fopt132(.A (n_36), .Y (n_35));
  BUFX2 fopt133(.A (add_23_2_n_16), .Y (n_36));
  BUFX2 fopt134(.A (add_23_2_n_20), .Y (n_38));
endmodule


