`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 06:00:21 CST (May 25 2023 22:00:21 UTC)

module SobelFilter_N_Mux_32_4_33_4(in5, in4, in3, in2, ctrl1, out1);
  input [31:0] in5;
  input [8:0] in4, in3, in2;
  input [5:0] ctrl1;
  output [31:0] out1;
  wire [31:0] in5;
  wire [8:0] in4, in3, in2;
  wire [5:0] ctrl1;
  wire [31:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_59, n_83;
  AND2XL g2861(.A (in5[26]), .B (n_83), .Y (out1[26]));
  AND2XL g2866(.A (in5[30]), .B (n_83), .Y (out1[30]));
  AND2XL g2857(.A (in5[29]), .B (n_83), .Y (out1[29]));
  AND2XL g2858(.A (in5[28]), .B (n_83), .Y (out1[28]));
  AND2XL g2859(.A (in5[27]), .B (n_83), .Y (out1[27]));
  AND2XL g2852(.A (in5[31]), .B (n_83), .Y (out1[31]));
  AND2XL g2869(.A (in5[25]), .B (n_83), .Y (out1[25]));
  AND2XL g2862(.A (in5[24]), .B (n_83), .Y (out1[24]));
  AND2XL g2864(.A (in5[23]), .B (n_83), .Y (out1[23]));
  AND2XL g2865(.A (in5[22]), .B (n_83), .Y (out1[22]));
  AND2XL g2868(.A (in5[21]), .B (n_83), .Y (out1[21]));
  AND2XL g2874(.A (in5[14]), .B (n_83), .Y (out1[14]));
  AND2XL g2863(.A (in5[19]), .B (n_83), .Y (out1[19]));
  AND2XL g2870(.A (in5[18]), .B (n_83), .Y (out1[18]));
  AND2XL g2872(.A (in5[17]), .B (n_83), .Y (out1[17]));
  AND2XL g2871(.A (in5[16]), .B (n_83), .Y (out1[16]));
  AND2XL g2873(.A (in5[15]), .B (n_83), .Y (out1[15]));
  AND2XL g2867(.A (in5[20]), .B (n_83), .Y (out1[20]));
  AND2XL g2853(.A (in5[13]), .B (n_83), .Y (out1[13]));
  AND2XL g2854(.A (in5[12]), .B (n_83), .Y (out1[12]));
  AND2XL g2855(.A (in5[11]), .B (n_83), .Y (out1[11]));
  AND2XL g2856(.A (in5[10]), .B (n_83), .Y (out1[10]));
  AND2XL g2860(.A (in5[9]), .B (n_83), .Y (out1[9]));
  OAI211X1 g2851(.A0 (n_5), .A1 (n_59), .B0 (n_31), .C0 (n_47), .Y
       (out1[6]));
  OAI211X1 g2847(.A0 (n_4), .A1 (n_59), .B0 (n_32), .C0 (n_41), .Y
       (out1[7]));
  OAI211X1 g2845(.A0 (n_3), .A1 (n_59), .B0 (n_37), .C0 (n_43), .Y
       (out1[8]));
  OAI211X1 g2844(.A0 (n_2), .A1 (n_59), .B0 (n_33), .C0 (n_51), .Y
       (out1[5]));
  OAI211X1 g2849(.A0 (n_0), .A1 (n_59), .B0 (n_30), .C0 (n_45), .Y
       (out1[2]));
  OAI211X1 g2846(.A0 (n_6), .A1 (n_59), .B0 (n_36), .C0 (n_46), .Y
       (out1[3]));
  OAI211X1 g2843(.A0 (n_7), .A1 (n_59), .B0 (n_27), .C0 (n_50), .Y
       (out1[4]));
  OAI211X1 g2848(.A0 (n_8), .A1 (n_59), .B0 (n_28), .C0 (n_42), .Y
       (out1[1]));
  OAI211X1 g2850(.A0 (n_1), .A1 (n_59), .B0 (n_29), .C0 (n_44), .Y
       (out1[0]));
  OR4X1 g2879(.A (n_38), .B (n_39), .C (n_40), .D (n_23), .Y (n_83));
  AOI22X1 g2877(.A0 (in2[5]), .A1 (n_49), .B0 (in3[5]), .B1 (n_48), .Y
       (n_51));
  AOI22X1 g2876(.A0 (in2[4]), .A1 (n_49), .B0 (in3[4]), .B1 (n_48), .Y
       (n_50));
  AOI22X1 g2875(.A0 (in2[6]), .A1 (n_49), .B0 (in3[6]), .B1 (n_48), .Y
       (n_47));
  AOI22X1 g2880(.A0 (in2[3]), .A1 (n_49), .B0 (in3[3]), .B1 (n_48), .Y
       (n_46));
  AOI22X1 g2881(.A0 (in2[2]), .A1 (n_49), .B0 (in3[2]), .B1 (n_48), .Y
       (n_45));
  AOI22X1 g2884(.A0 (in2[0]), .A1 (n_49), .B0 (in3[0]), .B1 (n_48), .Y
       (n_44));
  AOI22X1 g2882(.A0 (in2[8]), .A1 (n_49), .B0 (in3[8]), .B1 (n_48), .Y
       (n_43));
  AOI22X1 g2883(.A0 (in2[1]), .A1 (n_49), .B0 (in3[1]), .B1 (n_48), .Y
       (n_42));
  AOI22X1 g2885(.A0 (in2[7]), .A1 (n_49), .B0 (in3[7]), .B1 (n_48), .Y
       (n_41));
  NOR4X1 g2878(.A (n_40), .B (n_39), .C (n_26), .D (n_24), .Y (n_59));
  NAND4XL g2895(.A (n_20), .B (n_25), .C (n_22), .D (n_21), .Y (n_38));
  AOI22X1 g2890(.A0 (in4[8]), .A1 (n_35), .B0 (in5[8]), .B1 (n_34), .Y
       (n_37));
  AOI22X1 g2889(.A0 (in4[3]), .A1 (n_35), .B0 (in5[3]), .B1 (n_34), .Y
       (n_36));
  AOI22X1 g2888(.A0 (in4[5]), .A1 (n_35), .B0 (in5[5]), .B1 (n_34), .Y
       (n_33));
  AOI22X1 g2891(.A0 (in4[7]), .A1 (n_35), .B0 (in5[7]), .B1 (n_34), .Y
       (n_32));
  AOI22X1 g2894(.A0 (in4[6]), .A1 (n_35), .B0 (in5[6]), .B1 (n_34), .Y
       (n_31));
  AOI22X1 g2893(.A0 (in4[2]), .A1 (n_35), .B0 (in5[2]), .B1 (n_34), .Y
       (n_30));
  AOI22X1 g2892(.A0 (in4[0]), .A1 (n_35), .B0 (in5[0]), .B1 (n_34), .Y
       (n_29));
  AOI22X1 g2886(.A0 (in4[1]), .A1 (n_35), .B0 (in5[1]), .B1 (n_34), .Y
       (n_28));
  AOI22X1 g2887(.A0 (in4[4]), .A1 (n_35), .B0 (in5[4]), .B1 (n_34), .Y
       (n_27));
  NOR4X1 g2898(.A (ctrl1[2]), .B (ctrl1[1]), .C (ctrl1[0]), .D (n_14),
       .Y (n_49));
  NAND3BXL g2900(.AN (n_19), .B (n_25), .C (n_17), .Y (n_26));
  NOR4X1 g2897(.A (n_10), .B (ctrl1[1]), .C (n_18), .D (n_15), .Y
       (n_48));
  NAND3BXL g2896(.AN (n_23), .B (n_22), .C (n_21), .Y (n_24));
  NOR3X1 g2901(.A (n_34), .B (n_16), .C (n_19), .Y (n_20));
  AND3XL g2899(.A (n_9), .B (ctrl1[1]), .C (n_18), .Y (n_35));
  INVXL g2911(.A (n_16), .Y (n_17));
  NOR3X1 g2907(.A (n_18), .B (n_12), .C (ctrl1[2]), .Y (n_23));
  NAND2BX1 g2902(.AN (n_13), .B (ctrl1[3]), .Y (n_15));
  NAND2BX1 g2903(.AN (n_13), .B (ctrl1[3]), .Y (n_14));
  OAI22X1 g2906(.A0 (n_12), .A1 (ctrl1[3]), .B0 (n_11), .B1 (ctrl1[4]),
       .Y (n_39));
  NAND2X1 g2908(.A (ctrl1[3]), .B (n_11), .Y (n_25));
  NOR2X1 g2912(.A (n_10), .B (ctrl1[5]), .Y (n_16));
  NAND2X1 g2913(.A (ctrl1[4]), .B (n_11), .Y (n_22));
  NOR4X1 g2905(.A (ctrl1[5]), .B (ctrl1[4]), .C (ctrl1[3]), .D
       (ctrl1[2]), .Y (n_9));
  NAND3X1 g2904(.A (n_18), .B (ctrl1[4]), .C (ctrl1[2]), .Y (n_21));
  NOR2X1 g2915(.A (n_18), .B (ctrl1[5]), .Y (n_34));
  NOR2X1 g2909(.A (ctrl1[5]), .B (ctrl1[1]), .Y (n_19));
  AND2X1 g2910(.A (ctrl1[4]), .B (ctrl1[1]), .Y (n_40));
  NAND2X1 g2914(.A (ctrl1[5]), .B (ctrl1[4]), .Y (n_13));
  INVX1 g2926(.A (in5[1]), .Y (n_8));
  INVX1 g2927(.A (in5[4]), .Y (n_7));
  INVX1 g2916(.A (in5[3]), .Y (n_6));
  INVX1 g2918(.A (in5[6]), .Y (n_5));
  INVX1 g2928(.A (ctrl1[4]), .Y (n_12));
  INVX1 g2922(.A (ctrl1[5]), .Y (n_11));
  INVX1 g2917(.A (in5[7]), .Y (n_4));
  INVX1 g2923(.A (in5[8]), .Y (n_3));
  INVX1 g2924(.A (in5[5]), .Y (n_2));
  INVX1 g2925(.A (in5[0]), .Y (n_1));
  INVX1 g2919(.A (in5[2]), .Y (n_0));
  INVX1 g2921(.A (ctrl1[2]), .Y (n_10));
  INVX1 g2920(.A (ctrl1[0]), .Y (n_18));
endmodule


