`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 12:39:12 CST (May 26 2023 04:39:12 UTC)

module SobelFilter_Add2i15Add3i3u2Mul2i3u2_1(in2, in1, out1);
  input [1:0] in2, in1;
  output [5:0] out1;
  wire [1:0] in2, in1;
  wire [5:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, n_10, n_11, n_12, n_14, n_15;
  assign out1[4] = 1'b1;
  assign out1[5] = 1'b0;
  NAND2X1 g339(.A (n_10), .B (n_15), .Y (out1[2]));
  MXI2X1 g340(.A (n_14), .B (n_4), .S0 (n_12), .Y (out1[1]));
  AOI21X1 g341(.A0 (n_11), .A1 (n_14), .B0 (n_6), .Y (n_15));
  NAND2X1 g346(.A (n_2), .B (n_5), .Y (out1[0]));
  NAND2X1 g347(.A (n_11), .B (n_9), .Y (n_12));
  NAND2BX1 g344(.AN (n_7), .B (n_9), .Y (n_10));
  OAI21X1 g343(.A0 (n_0), .A1 (n_7), .B0 (n_3), .Y (out1[3]));
  NOR2X1 g345(.A (in2[0]), .B (n_9), .Y (n_6));
  INVX1 g350(.A (n_14), .Y (n_5));
  INVX1 g342(.A (n_14), .Y (n_4));
  NAND2X4 g352(.A (in1[1]), .B (n_3), .Y (n_9));
  NOR2X4 g353(.A (in1[0]), .B (n_1), .Y (n_14));
  NAND2X1 g348(.A (in1[0]), .B (n_1), .Y (n_2));
  NAND2X4 g349(.A (in2[1]), .B (n_0), .Y (n_11));
  NAND2X2 g351(.A (in2[0]), .B (in1[0]), .Y (n_7));
  CLKINVX12 g355(.A (in1[1]), .Y (n_0));
  INVX3 g356(.A (in2[0]), .Y (n_1));
  CLKINVX16 g354(.A (in2[1]), .Y (n_3));
endmodule


