`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 12:37:58 CST (May 26 2023 04:37:58 UTC)

module SobelFilter_Add2i9Add2u2Mul2i3u2_4(in2, in1, out1);
  input [1:0] in2, in1;
  output [4:0] out1;
  wire [1:0] in2, in1;
  wire [4:0] out1;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_8;
  INVX1 g192(.A (out1[4]), .Y (out1[3]));
  XOR2XL g191(.A (n_6), .B (n_8), .Y (out1[2]));
  NOR2BX1 g193(.AN (n_8), .B (n_5), .Y (out1[4]));
  ADDFX1 g194(.A (n_1), .B (in2[1]), .CI (n_4), .CO (n_8), .S
       (out1[1]));
  ADDHX1 g195(.A (n_0), .B (n_3), .CO (n_5), .S (n_6));
  OA21X1 g196(.A0 (in2[0]), .A1 (in1[1]), .B0 (n_3), .Y (n_4));
  OAI2BB1X1 g197(.A0N (in2[0]), .A1N (in1[0]), .B0 (n_1), .Y (out1[0]));
  NAND2X1 g198(.A (in2[0]), .B (in1[1]), .Y (n_3));
  OR2X1 g199(.A (in2[0]), .B (in1[0]), .Y (n_1));
  INVX1 g200(.A (in2[1]), .Y (n_0));
endmodule


