`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 12:38:07 CST (May 26 2023 04:38:07 UTC)

module SobelFilter_Add_5U_15_1(in1, out1);
  input [4:0] in1;
  output [4:0] out1;
  wire [4:0] in1;
  wire [4:0] out1;
  wire add_21_2_n_0, add_21_2_n_1, add_21_2_n_2, add_21_2_n_3,
       add_21_2_n_4, add_21_2_n_5, add_21_2_n_7, add_21_2_n_8;
  INVX1 g2(.A (in1[0]), .Y (out1[0]));
  MXI2X1 add_21_2_g70(.A (add_21_2_n_1), .B (in1[3]), .S0
       (add_21_2_n_8), .Y (out1[3]));
  MXI2X1 add_21_2_g71(.A (add_21_2_n_2), .B (in1[4]), .S0
       (add_21_2_n_7), .Y (out1[4]));
  MXI2XL add_21_2_g72(.A (in1[2]), .B (add_21_2_n_3), .S0
       (add_21_2_n_4), .Y (out1[2]));
  NOR2X2 add_21_2_g73(.A (add_21_2_n_3), .B (add_21_2_n_4), .Y
       (add_21_2_n_8));
  NOR2X2 add_21_2_g74(.A (add_21_2_n_4), .B (add_21_2_n_5), .Y
       (add_21_2_n_7));
  MXI2XL add_21_2_g75(.A (in1[1]), .B (add_21_2_n_0), .S0 (in1[0]), .Y
       (out1[1]));
  NAND2X8 add_21_2_g76(.A (in1[3]), .B (in1[2]), .Y (add_21_2_n_5));
  NOR2X8 add_21_2_g77(.A (in1[1]), .B (in1[0]), .Y (add_21_2_n_4));
  INVX1 add_21_2_g78(.A (in1[2]), .Y (add_21_2_n_3));
  INVX1 add_21_2_g79(.A (in1[4]), .Y (add_21_2_n_2));
  INVX1 add_21_2_g80(.A (in1[3]), .Y (add_21_2_n_1));
  INVX1 add_21_2_g81(.A (in1[1]), .Y (add_21_2_n_0));
endmodule


