`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 12:37:27 CST (May 26 2023 04:37:27 UTC)

module SobelFilter_Mul2i3Subi10s6_4(in1, out1);
  input [5:0] in1;
  output [5:0] out1;
  wire [5:0] in1;
  wire [5:0] out1;
  wire asc002_2_, asc002_3_, asc002_4_, asc002_5_, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, sub_22_2_n_1;
  wire sub_22_2_n_2, sub_22_2_n_3, sub_22_2_n_5;
  assign out1[0] = in1[0];
  XNOR2X1 g266(.A (n_5), .B (n_10), .Y (out1[5]));
  ADDFX1 g267(.A (n_9), .B (asc002_3_), .CI (asc002_4_), .CO (n_10), .S
       (out1[4]));
  XNOR2X1 g268(.A (n_8), .B (n_7), .Y (out1[3]));
  OAI211X1 g269(.A0 (n_1), .A1 (n_2), .B0 (n_4), .C0 (n_3), .Y (n_9));
  XNOR2X1 g270(.A (n_1), .B (n_6), .Y (out1[2]));
  NAND2X1 g271(.A (n_1), .B (n_3), .Y (n_8));
  NAND2BX1 g272(.AN (n_2), .B (n_4), .Y (n_7));
  OA21X1 g273(.A0 (n_0), .A1 (asc002_2_), .B0 (n_3), .Y (n_6));
  OA21X1 g274(.A0 (n_0), .A1 (in1[0]), .B0 (n_1), .Y (out1[1]));
  XNOR2X1 g275(.A (asc002_4_), .B (asc002_5_), .Y (n_5));
  NAND2X1 g276(.A (asc002_3_), .B (asc002_2_), .Y (n_4));
  NAND2X1 g277(.A (asc002_2_), .B (n_0), .Y (n_3));
  NOR2X1 g278(.A (asc002_3_), .B (asc002_2_), .Y (n_2));
  NAND2X1 g279(.A (in1[0]), .B (n_0), .Y (n_1));
  INVX1 g280(.A (in1[1]), .Y (n_0));
  XNOR2X1 sub_22_2_g94(.A (in1[5]), .B (sub_22_2_n_5), .Y (asc002_5_));
  XNOR2X1 sub_22_2_g95(.A (in1[3]), .B (sub_22_2_n_1), .Y (asc002_3_));
  OAI2BB1X1 sub_22_2_g96(.A0N (in1[4]), .A1N (sub_22_2_n_3), .B0
       (sub_22_2_n_5), .Y (asc002_4_));
  NAND2BX1 sub_22_2_g97(.AN (in1[4]), .B (sub_22_2_n_2), .Y
       (sub_22_2_n_5));
  AO21X1 sub_22_2_g98(.A0 (in1[2]), .A1 (in1[1]), .B0 (sub_22_2_n_1),
       .Y (asc002_2_));
  INVXL sub_22_2_g99(.A (sub_22_2_n_2), .Y (sub_22_2_n_3));
  AOI22X1 sub_22_2_g100(.A0 (in1[3]), .A1 (in1[1]), .B0 (in1[3]), .B1
       (in1[2]), .Y (sub_22_2_n_2));
  NOR2X1 sub_22_2_g101(.A (in1[2]), .B (in1[1]), .Y (sub_22_2_n_1));
endmodule

