`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 12:39:25 CST (May 26 2023 04:39:25 UTC)

module SobelFilter_Add2i18u4_1(in1, out1);
  input [3:0] in1;
  output [4:0] out1;
  wire [3:0] in1;
  wire [4:0] out1;
  wire add_21_2_n_1, add_21_2_n_2, add_21_2_n_3;
  assign out1[0] = in1[0];
  INVX1 g2(.A (in1[1]), .Y (out1[1]));
  MXI2X1 add_21_2_g59(.A (in1[3]), .B (add_21_2_n_1), .S0
       (add_21_2_n_3), .Y (out1[3]));
  NAND3X1 add_21_2_g60(.A (in1[1]), .B (in1[3]), .C (in1[2]), .Y
       (out1[4]));
  MXI2XL add_21_2_g61(.A (add_21_2_n_2), .B (in1[2]), .S0 (in1[1]), .Y
       (out1[2]));
  NAND2X8 add_21_2_g62(.A (in1[2]), .B (in1[1]), .Y (add_21_2_n_3));
  INVX1 add_21_2_g63(.A (in1[2]), .Y (add_21_2_n_2));
  INVX1 add_21_2_g64(.A (in1[3]), .Y (add_21_2_n_1));
endmodule

