`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 19.16-s111_1
// Generated on: May 26 2023 12:37:59 CST (May 26 2023 04:37:59 UTC)

module SobelFilter_Lti3u2_4(in1, out1);
  input [1:0] in1;
  output out1;
  wire [1:0] in1;
  wire out1;
  NAND2X1 gt_19_28_g21(.A (in1[1]), .B (in1[0]), .Y (out1));
endmodule

